/* eslint-disable @typescript-eslint/no-explicit-any */
import { Ad } from '@/types/ad';
import { Restaurant, MenuItem } from '@/types/restaurant';
import { Recipe } from '@/types/recipe';

export const mockAds: Ad[] = [
  {
    id: 'ad-home-hero',
    name: 'Pizzavika 2026',
    client: 'Pizzan ehf.',
    format: '1018x360',
    creatives: {
      '1018x360': 'https://images.unsplash.com/photo-1590947132387-155cc3dd2671?q=80&w=1018&h=360&fit=crop'
    },
    image_url: 'https://images.unsplash.com/photo-1590947132387-155cc3dd2671?q=80&w=1018&h=360&fit=crop',
    target_url: '#',
    status: 'active',
    placements: ['home_hero'],
    start_date: null as any,
    end_date: null as any,
  },
  {
    id: 'ad-home-featured',
    name: 'Súkkulaði Mousse',
    client: 'Sælgætisgerðin',
    format: '310x400',
    creatives: {
      '310x400': 'https://images.unsplash.com/photo-1542010589005-d1eabd394997?q=80&w=310&h=400&fit=crop'
    },
    image_url: 'https://images.unsplash.com/photo-1542010589005-d1eabd394997?q=80&w=310&h=400&fit=crop',
    target_url: '#',
    status: 'active',
    placements: ['home_featured'],
    start_date: null as any,
    end_date: null as any,
  }
];

export const mockRestaurants: Restaurant[] = [
  // ─── REYKJAVÍK ───
  {
    id: 'flatey-pizza',
    name: 'Flatey Pizza',
    slug: 'flatey-pizza',
    description_is: 'Ekkta napólísk pizza úr súrdeigi bakað í 500 gráðu viðarofni á 90 sekúndum. Ferskt frá bæ.',
    description_en: 'Authentic Neapolitan sourdough pizza baked in a 500°C wood fire oven in 90 seconds. Farm fresh.',
    address: 'Grandagarður 11',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1539, longitude: -21.9392 } as any,
    phone: '588 5555',
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '11-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Súrdeig'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    google_place_id: 'ChIJ_flatey_rvk', tripadvisor_url: 'https://tripadvisor.com/flatey-pizza',
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Súrdeig', 'Viðarofn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'olifa-la-madre',
    name: 'Olifa La Madre',
    slug: 'olifa-la-madre',
    description_is: 'Fyrsti Pala pizza staðurinn á Íslandi. Rómversk pizzustíll með lífrænum hráefnum og krispandi súrdeigsbotn.',
    description_en: 'Iceland\'s first Pala pizza restaurant. Roman-style with organic ingredients and crispy sourdough crust.',
    address: 'Laugavegur 2b',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1466, longitude: -21.9331 } as any,
    phone: '551 0100',
    website: 'https://olifa.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '11:30-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Lífrænt'],
    image_urls: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Rómversk', 'Pala', 'Lífræn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'daddis-pizza',
    name: 'Daddi\'s Pizza',
    slug: 'daddis-pizza',
    description_is: 'Fjölskyldurekin pizzería í hjarta Reykjavíkur. Handýtt deig og yfir 30 áleggsval. Klassískt andrúmsloft.',
    description_en: 'Family-owned pizzeria in the heart of Reykjavik. Hand-tossed dough with 30+ topping choices.',
    address: 'Hafnarstræti 8',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1482, longitude: -21.9382 } as any,
    phone: '561 2345',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Fjölskyldu-vænlegt'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Klassísk', 'Fjölskylda', 'Handýtt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'eldofninn',
    name: 'Eldofninn',
    slug: 'eldofninn',
    description_is: 'Vinsælt takeaway. Steinofn fluttur frá Ítalíu. Þunnar og krispaðar pizzur gerðar frá grunni.',
    description_en: 'Popular takeaway spot. Stone oven imported from Italy. Thin and crispy scratch-made pizzas.',
    address: 'Bragagata 38a',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1459, longitude: -21.9385 } as any,
    phone: '562 3838',
    website: 'https://eldofninn.is',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Takeaway', 'Delivery', 'Steinofn'],
    image_urls: ['https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Takeaway', 'Steinofn', 'Þunn skorpa'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'hornid',
    name: 'Hornið',
    slug: 'hornid',
    description_is: 'Elsta ítalska veitingahúsið í Reykjavík, stofnað 1979. Höfnarglæsileiki, rausnarlegar skammtir og klassískar pizzur.',
    description_en: 'Reykjavik\'s oldest Italian restaurant, established 1979. Harbor-side charm, generous portions, classic pizzas.',
    address: 'Hafnarstræti 15',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1489, longitude: -21.9369 } as any,
    phone: '551 3340',
    website: 'https://hornid.is',
    opening_hours: { mán: '11:30-23', þri: '11:30-23', mið: '11:30-23', fim: '11:30-23', fös: '11:30-01', lau: '12-01', sun: '12-23' },
    price_level: 3,
    features: ['Dine-in', 'Bar', 'Sögulegt'],
    image_urls: ['https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Sögulegt', 'Klassískt', 'Höfn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'reykjavik-pizzeria',
    name: 'Reykjavik Pizzeria',
    slug: 'reykjavik-pizzeria',
    description_is: 'Eldbakaðar pizzur á hagstæðu verði. Stórt úrval af hefðbundnum og nýstárlegum pizzum.',
    description_en: 'Fire-baked pizzas at affordable prices. Wide selection of traditional and unique pies.',
    address: 'Háteigsvegur 9',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1412, longitude: -21.9120 } as any,
    phone: '562 4444',
    website: 'https://reykjavikpizzeria.is',
    opening_hours: { mán: '11:30-21:30', þri: '11:30-21:30', mið: '11:30-21:30', fim: '11:30-21:30', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Eldbakað', 'Hagstætt', 'Vegan'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'bakabaka',
    name: 'BakaBaka',
    slug: 'bakabaka',
    description_is: 'Bakarí að degi, pizzería að kvöldi. Langur hefunartími gefur djúpan og flókinn bragð.',
    description_en: 'Bakery by day, pizzeria by evening. Long fermentation creates deep, complex flavors.',
    address: 'Skólavörðustígur 36',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1440, longitude: -21.9274 } as any,
    opening_hours: { mán: '17-21', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '17-22', sun: 'Lokað' },
    price_level: 3,
    features: ['Dine-in', 'Bakarí', 'Súrdeig'],
    image_urls: ['https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.7, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Súrdeig', 'Bakarí', 'Hefun'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'blackbox-pizzeria',
    name: 'Blackbox Pizzeria',
    slug: 'blackbox-pizzeria',
    description_is: 'Klassísk pizzería. Deigið hvílir í sólarhring og er bakað á undir 2 mínútum.',
    description_en: 'Classic-style pizzeria. Dough proves for a full day and bakes in under 2 minutes.',
    address: 'Borgartún 26',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1437, longitude: -21.9098 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Fljótt'],
    image_urls: ['https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Klassísk', 'Fljótt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'coocoos-nest',
    name: 'The Coocoo\'s Nest',
    slug: 'coocoos-nest',
    description_is: 'Huggulegt brúnsjstaður og pizza bar. Þunn, krispaðir og sviðnir kantar. Frábær kokteill.',
    description_en: 'Cozy brunch spot and pizza bar. Thin, crispy, and charred crust. Excellent cocktails.',
    address: 'Grandagarður 23',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1545, longitude: -21.9410 } as any,
    website: 'https://coocoosnest.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '10-23', sun: '10-22' },
    price_level: 3,
    features: ['Dine-in', 'Bar', 'Brúnsj', 'Kokteill'],
    image_urls: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Brúnsj', 'Kokteill', 'Grandi'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'kaffi-laugalaekur',
    name: 'Kaffi Laugalækur',
    slug: 'kaffi-laugalaekur',
    description_is: 'Hverfis gastro bar með verðlaunuðum súrdeigs pizzum. Huggulegt og staðbundið.',
    description_en: 'Neighborhood gastro bar with award-winning sourdough pizzas. Cozy and local.',
    address: 'Laugalækur 6',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1404, longitude: -21.8985 } as any,
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Bar', 'Súrdeig', 'Verðlaunað'],
    image_urls: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Gastro bar', 'Súrdeig', 'Verðlaunað'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'rossopomodoro',
    name: 'Rossopomodoro',
    slug: 'rossopomodoro',
    description_is: 'Napólítönskt keðjuveitingahús á Laugavegi. Ekta ítölsk pizza, pasta og vín.',
    description_en: 'Neapolitan chain restaurant on Laugavegur. Authentic Italian pizza, pasta, and wine.',
    address: 'Laugavegur 40',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1448, longitude: -21.9256 } as any,
    website: 'https://rossopomodoro.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 3,
    features: ['Dine-in', 'Vín', 'Napólí'],
    image_urls: ['https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Keðja', 'Vín'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-with-no-name',
    name: 'Pizza With No Name',
    slug: 'pizza-with-no-name',
    description_is: 'Leyndarmálið á Hlemmi. Frábærar pizzur, gott andrúmsloft í nýja mathöllinni.',
    description_en: 'The secret at Hlemmur. Great pizzas, good atmosphere in the new food hall.',
    address: 'Hlemmur Mathöll',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1432, longitude: -21.9145 } as any,
    opening_hours: { daglega: '11:30-22:00' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Mathöll'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Hlemmur', 'Mathöll', 'Casual'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'napoli-pizza-rvk',
    name: 'Napoli Pizza',
    slug: 'napoli-pizza-rvk',
    description_is: 'Hefðbundin napólítönsk pizza á Reykjavíkurbestu matarsvæðinu. Ferskt deig daglega.',
    description_en: 'Traditional Neapolitan pizza in Reykjavik\'s best food district. Fresh dough daily.',
    address: 'Tryggvagata 14',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1495, longitude: -21.9392 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Napólí', 'Hefðbundin'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'glosteinnn',
    name: 'Glósteinn',
    slug: 'glosteinn',
    description_is: 'Steinbakað pizza á hagstæðu verði. Stórt úrval og góðir hádegisréttir.',
    description_en: 'Stone-baked pizza at affordable prices. Wide selection and great lunch deals.',
    address: 'Hringbraut 119',
    city: 'Reykjavík',
    postal_code: '107',
    location: { latitude: 64.1390, longitude: -21.9280 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 1,
    features: ['Takeaway', 'Delivery', 'Hagstætt'],
    image_urls: ['https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Hagstætt', 'Steinbakað', 'Delivery'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-popolare',
    name: 'Pizza Popolare Pósthús',
    slug: 'pizza-popolare',
    description_is: 'Í gömlu pósthúsinu á Austurstræti. Viðarofnsbakað og ítalskt andrúmsloft.',
    description_en: 'In the old post office on Austurstræti. Wood-fired and Italian atmosphere.',
    address: 'Austurstræti 13',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1477, longitude: -21.9351 } as any,
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 3,
    features: ['Dine-in', 'Viðarofn', 'Sögulegt hús'],
    image_urls: ['https://images.unsplash.com/photo-1625631980560-4aeeed597e9f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Miðborg', 'Sögulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── AKUREYRI ───
  {
    id: 'pizzasmidjan-akureyri',
    name: 'Pizzasmiðjan',
    slug: 'pizzasmidjan-akureyri',
    description_is: 'Viðarofnspizza í hjarta Akureyrar. Rólegt og huggulegt andrúmsloft.',
    description_en: 'Wood-fired pizza in the heart of Akureyri. Relaxed and cozy atmosphere.',
    address: 'Kaupvangsstræti 6',
    city: 'Akureyri',
    postal_code: '600',
    location: { latitude: 65.6835, longitude: -18.0878 } as any,
    website: 'https://pizzasmidjan.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1585238342024-78d387f4a707?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Viðarofn', 'Akureyri', 'Norðurland'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'greifinn-akureyri',
    name: 'Greifinn',
    slug: 'greifinn-akureyri',
    description_is: 'Vinsæll staður í Akureyri þar sem hægt er að borða pizzur, borgara og íslensku rétti. Fjölskylduvænlegt.',
    description_en: 'Popular Akureyri spot serving pizzas, burgers, and Icelandic dishes. Family-friendly.',
    address: 'Glerárgata 20',
    city: 'Akureyri',
    postal_code: '600',
    location: { latitude: 65.6810, longitude: -18.0930 } as any,
    phone: '460 1600',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Fjölskylduvænlegt', 'Bar'],
    image_urls: ['https://images.unsplash.com/photo-1552539618-7eee9b73b4e8?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Fjölskylda', 'Akureyri'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── KEFLAVÍK ───
  {
    id: 'antons-mamma-mia',
    name: 'Antons Mamma Mia',
    slug: 'antons-mamma-mia',
    description_is: 'Steinofnspizzur í Keflavík. Huggulegt og rólegt andrúmsloft með ítalska matseðil.',
    description_en: 'Stone-oven pizzas in Keflavik. Cozy atmosphere with a full Italian menu.',
    address: 'Hafnargata 32',
    city: 'Keflavík',
    postal_code: '230',
    location: { latitude: 64.0048, longitude: -22.5631 } as any,
    phone: '421 5533',
    website: 'https://antons.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Steinofn', 'Pasta'],
    image_urls: ['https://images.unsplash.com/photo-1548365328-8b849b3e5b18?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Steinofn', 'Keflavík', 'Ítalía'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'fernandos-keflavik',
    name: 'Fernando\'s',
    slug: 'fernandos-keflavik',
    description_is: 'Vinsælt ítalsk veitingahús í Keflavík. Ferskar pizzur og pasta með íslensku ívafi.',
    description_en: 'Popular Italian restaurant in Keflavik. Fresh pizzas and pasta with an Icelandic twist.',
    address: 'Hafnargata 5',
    city: 'Keflavík',
    postal_code: '230',
    location: { latitude: 64.0052, longitude: -22.5580 } as any,
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1590947132387-155cc3dd2671?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Keflavík', 'Ítalía'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── AUSTFIRÐIR ───
  {
    id: 'pizzafjordur',
    name: 'Pizzafjörður',
    slug: 'pizzafjordur',
    description_is: 'Smá pizzería í Eskifirði með frábæra pizza og vinalegt fólk. Ferskt deig, mörg áleggsval, og rólegt andrúmsloft á Austfjörðum.',
    description_en: 'Small pizzeria in Eskifjörður with amazing pizza and friendly staff. Fresh dough, lots of toppings, and calm East Iceland vibes.',
    address: 'Strandgata 25',
    city: 'Eskifjörður',
    postal_code: '735',
    location: { latitude: 65.0712, longitude: -14.0131 } as any,
    opening_hours: { sun: '17-21', mán: '17-21', þri: '17-21', mið: '17-21', fim: 'Lokað', fös: 'Lokað', lau: 'Lokað' },
    price_level: 2,
    features: ['Takeaway', 'Glutenlaust val'],
    image_urls: ['https://images.unsplash.com/photo-1600628421055-4d30de868b8f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.7, rating_tripadvisor: 5.0,
    likes_count: 0, is_verified: false, tags: ['Austfirðir', 'Eskifjörður', 'Huggulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── SELFOSS ───
  {
    id: 'flatey-pizza-selfoss',
    name: 'Flatey Pizza Selfoss',
    slug: 'flatey-pizza-selfoss',
    description_is: 'Útibú Flatey Pizza á Selfossi. Sömu einkennandi napólítönsku pizzurnar í viðarofni.',
    description_en: 'Flatey Pizza branch in Selfoss. Same signature Neapolitan wood-fired pizzas.',
    address: 'Austurvegur 1',
    city: 'Selfoss',
    postal_code: '800',
    location: { latitude: 63.9355, longitude: -21.0035 } as any,
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Viðarofn', 'Selfoss'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'kaffi-krus',
    name: 'Kaffi Krús',
    slug: 'kaffi-krus',
    description_is: 'Huggulegt kaffihús á Selfossi. Krispaðar pizzur og borgarar ásamt gróbökuðu brauði.',
    description_en: 'Cozy café in Selfoss. Crispy pizzas, burgers, and artisan bread.',
    address: 'Austurvegur 7',
    city: 'Selfoss',
    postal_code: '800',
    location: { latitude: 63.9353, longitude: -21.0020 } as any,
    website: 'https://kaffikrus.is',
    opening_hours: { mán: '08-22', þri: '08-22', mið: '08-22', fim: '08-22', fös: '08-23', lau: '09-23', sun: '09-22' },
    price_level: 2,
    features: ['Dine-in', 'Kaffi', 'Brauð'],
    image_urls: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Kaffi', 'Selfoss', 'Huggulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── HÚSAVÍK ───
  {
    id: 'pizza-kofinn',
    name: 'Pizza Kofinn',
    slug: 'pizza-kofinn',
    description_is: 'Viðarofnspizza í bæjarkjarna Húsavíkur. Staðbundið, vinalegt og gott. Margherita, pepperóní og Parma.',
    description_en: 'Wood-fired pizza in the heart of Húsavík. Local, friendly, and delicious. Margherita, pepperoni, and Parma.',
    address: 'Hafnarstétt 9',
    city: 'Húsavík',
    postal_code: '640',
    location: { latitude: 66.0449, longitude: -17.3389 } as any,
    website: 'https://pizzakofinn.is',
    opening_hours: { mán: '12-21', þri: '12-21', mið: '12-21', fim: '12-21', fös: '12-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Húsavík', 'Norðurland'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── VESTMANNAEYJAR ───
  {
    id: 'pitsugerdin',
    name: 'Pítsugerðin',
    slug: 'pitsugerdin',
    description_is: 'Ekta viðarofnspizza í Vestmannaeyjum. San Marzano tómatar, súrdeig, og staðbundið bjór á krana.',
    description_en: 'Authentic wood-fired pizza in the Westman Islands. San Marzano tomatoes, sourdough, and local craft beer.',
    address: 'Vestmannabraut 28',
    city: 'Vestmannaeyjar',
    postal_code: '900',
    location: { latitude: 63.4427, longitude: -20.2690 } as any,
    opening_hours: { mán: 'Lokað', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Viðarofn', 'Bjór'],
    image_urls: ['https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Vestmannaeyjar', 'Súrdeig'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-67-vestmannaeyjar',
    name: 'Pizza 67',
    slug: 'pizza-67-vestmannaeyjar',
    description_is: 'Ítölsk pizza á Eyjum. Stórt úrval á hagstæðu verði.',
    description_en: 'Italian pizza in the Westman Islands. Wide selection at affordable prices.',
    address: 'Bárustígur 11',
    city: 'Vestmannaeyjar',
    postal_code: '900',
    location: { latitude: 63.4420, longitude: -20.2680 } as any,
    opening_hours: { mán: '17-21', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '12-22', sun: '12-21' },
    price_level: 1,
    features: ['Takeaway', 'Delivery', 'Hagstætt'],
    image_urls: ['https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2,
    likes_count: 0, is_verified: false, tags: ['Hagstætt', 'Vestmannaeyjar'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── ÍSAFJÖRÐUR ───
  {
    id: 'hamraborg-isafjordur',
    name: 'Hamraborg',
    slug: 'hamraborg-isafjordur',
    description_is: 'Pizzería á Ísafirði. 12 tommu pizzur með þremur áleggsvalkostum. Einfalt og gott.',
    description_en: '12-inch pizzas with three toppings in Ísafjörður. Simple and delicious.',
    address: 'Hafnarstræti 7',
    city: 'Ísafjörður',
    postal_code: '400',
    location: { latitude: 66.0742, longitude: -23.1350 } as any,
    website: 'https://hamraborg.com',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3,
    likes_count: 0, is_verified: false, tags: ['Ísafjörður', 'Vestfirðir'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── EGILSSTAÐIR ───
  {
    id: 'askur-pizzeria',
    name: 'Askur Pizzeria',
    slug: 'askur-pizzeria',
    description_is: 'Staðbundin brugghúspizzería á Egilsstöðum. Búðu til þína eigin pizzu eða veldu af matseðli.',
    description_en: 'Local brewery pizzeria in Egilsstaðir. Build your own pizza or choose from the menu.',
    address: 'Fagradalsbraut 1',
    city: 'Egilsstaðir',
    postal_code: '700',
    location: { latitude: 65.2535, longitude: -14.3948 } as any,
    website: 'https://askurpizzeria.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Brugghús', 'Sérsniðið'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Brugghús', 'Egilsstaðir', 'Austfirðir'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── STYKKISHÓLMUR ───
  {
    id: 'stykkid-pizzeria',
    name: 'Stykkið Pizzeria',
    slug: 'stykkid-pizzeria',
    description_is: 'Pizzería í fallegasta bæ Vesturlands. Ferskt deig og staðbundin hráefni.',
    description_en: 'Pizzeria in western Iceland\'s most beautiful town. Fresh dough and local ingredients.',
    address: 'Aðalgata 3',
    city: 'Stykkishólmur',
    postal_code: '340',
    location: { latitude: 65.0758, longitude: -22.7300 } as any,
    opening_hours: { mán: '12-21', þri: '12-21', mið: '12-21', fim: '12-21', fös: '12-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Stykkishólmur', 'Snæfellsnes'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── HÖFUÐBORGARSVÆÐIÐ ───
  {
    id: 'pizzan-hafnarfjordur',
    name: 'Pizzan Hafnarfjörður',
    slug: 'pizzan-hafnarfjordur',
    description_is: 'Pizzan útibúið á Fjarðargötu. Vinsælar pizzur og sýður.',
    description_en: 'Pizzan branch on Fjarðargata. Popular pizzas and sides.',
    address: 'Fjarðargata 13-15',
    city: 'Hafnarfjörður',
    postal_code: '220',
    location: { latitude: 64.0671, longitude: -21.9549 } as any,
    website: 'https://pizzan.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1,
    likes_count: 0, is_verified: false, tags: ['Hafnarfjörður', 'Keðja'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'flatey-pizza-gardabaer',
    name: 'Flatey Pizza Garðatorg',
    slug: 'flatey-pizza-gardabaer',
    description_is: 'Flatey Pizza útibú á Garðatorgi í Garðabæ. Sömu napólítönsku pizzurnar í viðarofni.',
    description_en: 'Flatey Pizza branch at Garðatorg in Garðabær. Same Neapolitan wood-fired pizzas.',
    address: 'Garðatorg 7',
    city: 'Garðabær',
    postal_code: '210',
    location: { latitude: 64.0897, longitude: -21.9230 } as any,
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '11-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Viðarofn', 'Garðabær'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'italiano-kopavogur',
    name: 'Italiano Pizzeria',
    slug: 'italiano-kopavogur',
    description_is: 'Ítölsk pizzería í Kópavogi. Rausnarlegir skammtar og klassískar pizzur.',
    description_en: 'Italian pizzeria in Kópavogur. Generous portions and classic pizzas.',
    address: 'Smáratorg',
    city: 'Kópavogur',
    postal_code: '201',
    location: { latitude: 64.1069, longitude: -21.8822 } as any,
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2,
    likes_count: 0, is_verified: false, tags: ['Kópavogur', 'Klassísk'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'islenska-flatbakan',
    name: 'Íslenska Flatbakan',
    slug: 'islenska-flatbakan',
    description_is: 'Íslensku flatbökurnar — pizzur með íslensku ívafi. Stórt úrval og fjölskylduvænlegt.',
    description_en: 'The Icelandic Flatbread — pizzas with an Icelandic twist. Wide selection and family-friendly.',
    address: 'Dalshraun 1',
    city: 'Kópavogur',
    postal_code: '201',
    location: { latitude: 64.1049, longitude: -21.8900 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Takeaway', 'Delivery', 'Fjölskylduvænlegt'],
    image_urls: ['https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0,
    likes_count: 0, is_verified: false, tags: ['Kópavogur', 'Íslensku'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-braedur-mosfellsbaer',
    name: 'Pizza Bræður',
    slug: 'pizza-braedur-mosfellsbaer',
    description_is: 'Nýtt pizzahús í Mosfellsbæ. Bræðurnir baka ferskar pizzur daglega.',
    description_en: 'New pizza spot in Mosfellsbær. The brothers bake fresh pizzas daily.',
    address: 'Háholt 13',
    city: 'Mosfellsbær',
    postal_code: '270',
    location: { latitude: 64.1666, longitude: -21.6966 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3,
    likes_count: 0, is_verified: false, tags: ['Mosfellsbær', 'Nýtt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'castello-hafnarfjordur',
    name: 'Castello Pizzeria',
    slug: 'castello-hafnarfjordur',
    description_is: 'Klassísk pizzería í Hafnarfirði. Þykk og þunn skorpa, stórt áleggsval.',
    description_en: 'Classic pizzeria in Hafnarfjörður. Thick and thin crust options, wide topping selection.',
    address: 'Strandgata 55',
    city: 'Hafnarfjörður',
    postal_code: '220',
    location: { latitude: 64.0650, longitude: -21.9580 } as any,
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1,
    likes_count: 0, is_verified: false, tags: ['Hafnarfjörður', 'Klassísk'],
    created_at: null as any, updated_at: null as any,
  },
];

export const mockMenuItems: MenuItem[] = [
  // Flatey Pizza
  { id: '1', restaurant_id: 'flatey-pizza', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano tómatar, fior di latte, basil, ólífuolía', description_en: 'San Marzano tomatoes, fior di latte, basil, olive oil', price: 2590, category: 'Pizzur', sort_order: 1 },
  { id: '2', restaurant_id: 'flatey-pizza', name_is: 'Diavola', name_en: 'Diavola', description_is: 'Tómatar, mozzarella, spicy pepperóní, chili flögur', description_en: 'Tomatoes, mozzarella, spicy pepperoni, chili flakes', price: 3190, category: 'Pizzur', sort_order: 2 },
  { id: '3', restaurant_id: 'flatey-pizza', name_is: 'Quattro Formaggi', name_en: 'Quattro Formaggi', description_is: 'Mozzarella, gorgonzola, parmesan, ricotta', description_en: 'Mozzarella, gorgonzola, parmesan, ricotta', price: 3390, category: 'Pizzur', sort_order: 3 },
  { id: '4', restaurant_id: 'flatey-pizza', name_is: 'Fungi e Tartufo', name_en: 'Mushroom & Truffle', description_is: 'Mozzarella, sveppablöndun, trufflolía', description_en: 'Mozzarella, mixed mushrooms, truffle oil', price: 3490, category: 'Pizzur', sort_order: 4 },
  { id: '5', restaurant_id: 'flatey-pizza', name_is: 'Ostabrauð', name_en: 'Cheese bread', description_is: 'Hlýtt ostabrauð úr ofninum', description_en: 'Warm cheese bread from the oven', price: 1890, category: 'Meðlæti', sort_order: 10 },
  // Eldofninn
  { id: '10', restaurant_id: 'eldofninn', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatar, mozzarella, basil', description_en: 'Tomatoes, mozzarella, basil', price: 2190, category: 'Pizzur', sort_order: 1 },
  { id: '11', restaurant_id: 'eldofninn', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatar, mozzarella, pepperóní', description_en: 'Tomatoes, mozzarella, pepperoni', price: 2490, category: 'Pizzur', sort_order: 2 },
  { id: '12', restaurant_id: 'eldofninn', name_is: 'Hawaii', name_en: 'Hawaiian', description_is: 'Tómatar, mozzarella, skinku, ananas', description_en: 'Tomatoes, mozzarella, ham, pineapple', price: 2490, category: 'Pizzur', sort_order: 3 },
  // Hornið
  { id: '20', restaurant_id: 'hornid', name_is: 'Pizza Classica', name_en: 'Classic Pizza', description_is: 'Tómat, mozzarella, sveppir, paprika, ólífur', description_en: 'Tomato, mozzarella, mushrooms, peppers, olives', price: 2990, category: 'Pizzur', sort_order: 1 },
  { id: '21', restaurant_id: 'hornid', name_is: 'Pizza Hornið', name_en: 'Pizza Hornið', description_is: 'Sérmerkja pizzan okkar með sölsu og jalapeno', description_en: 'Our signature pizza with salsa and jalapeño', price: 3290, category: 'Pizzur', sort_order: 2 },
];

export { allRecipes as mockRecipes } from './recipeData';

