/* eslint-disable @typescript-eslint/no-explicit-any */
import { Ad } from '@/types/ad';
import { Restaurant, MenuItem } from '@/types/restaurant';
import { Recipe } from '@/types/recipe';

export const mockAds: Ad[] = [
  {
    id: 'ad-home-hero',
    name: 'Pizzavika 2026',
    client: 'Pizzan ehf.',
    format: '1018x360',
    creatives: {
      '1018x360': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1018&h=360&fit=crop'
    },
    image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1018&h=360&fit=crop',
    target_url: '#',
    status: 'active',
    placements: ['home_hero'],
    start_date: null as any,
    end_date: null as any,
  },
  {
    id: 'ad-home-featured',
    name: 'Súkkulaði Mousse',
    client: 'Sælgætisgerðin',
    format: '310x400',
    creatives: {
      '310x400': 'https://images.unsplash.com/photo-1555992336-03a23c7b20ee?q=80&w=310&h=400&fit=crop'
    },
    image_url: 'https://images.unsplash.com/photo-1555992336-03a23c7b20ee?q=80&w=310&h=400&fit=crop',
    target_url: '#',
    status: 'active',
    placements: ['home_featured'],
    start_date: null as any,
    end_date: null as any,
  }
];

export const mockRestaurants: Restaurant[] = [
  // ─── REYKJAVÍK ───
  {
    id: 'flatey-pizza',
    name: 'Flatey Pizza',
    slug: 'flatey-pizza',
    description_is: 'Ekta napólísk súrdeigspizza, bökuð í 500 gráða viðarofni á 90 sekúndum. Beint úr sveitinni.',
    description_en: 'Authentic Neapolitan sourdough pizza baked in a 500°C wood fire oven in 90 seconds. Farm fresh.',
    address: 'Grandagarður 11',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1539, longitude: -21.9392 } as any,
    phone: '588 5555',
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '11-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Súrdeig'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    google_place_id: 'ChIJ_flatey_rvk', tripadvisor_url: 'https://tripadvisor.com/flatey-pizza',
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Súrdeig', 'Viðarofn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'olifa-la-madre',
    name: 'Olifa La Madre',
    slug: 'olifa-la-madre',
    description_is: 'Fyrsti Pala pizzustaðurinn á Íslandi. Rómversk pizza með lífrænum hráefnum og stökkum súrdeigsbotni.',
    description_en: 'Iceland\'s first Pala pizza restaurant. Roman-style with organic ingredients and crispy sourdough crust.',
    address: 'Laugavegur 2b',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1466, longitude: -21.9331 } as any,
    phone: '551 0100',
    website: 'https://olifa.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '11:30-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Lífrænt'],
    image_urls: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Rómversk', 'Pala', 'Lífræn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'daddis-pizza',
    name: 'Daddi\'s Pizza',
    slug: 'daddis-pizza',
    description_is: 'Fjölskyldurekin pizzería í hjarta Reykjavíkur. Handflet deig og yfir 30 tegundir af áleggi. Klassískt andrúmsloft.',
    description_en: 'Family-owned pizzeria in the heart of Reykjavik. Hand-tossed dough with 30+ topping choices.',
    address: 'Hafnarstræti 8',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1482, longitude: -21.9382 } as any,
    phone: '561 2345',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Fjölskyldu-vænlegt'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Klassísk', 'Fjölskylda', 'Handýtt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'eldofninn',
    name: 'Eldofninn',
    slug: 'eldofninn',
    description_is: 'Vinsælt takeaway. Steinofn fluttur frá Ítalíu. Þunnar og stökkar pizzur gerðar frá grunni.',
    description_en: 'Popular takeaway spot. Stone oven imported from Italy. Thin and crispy scratch-made pizzas.',
    address: 'Bragagata 38a',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1459, longitude: -21.9385 } as any,
    phone: '562 3838',
    website: 'https://eldofninn.is',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Takeaway', 'Delivery', 'Steinofn'],
    image_urls: ['https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Takeaway', 'Steinofn', 'Þunn skorpa'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'hornid',
    name: 'Hornið',
    slug: 'hornid',
    description_is: 'Elsta ítalska veitingahúsið í Reykjavík, stofnað 1979. Hafnarglæsileiki, vænir skammtar og klassískar pizzur.',
    description_en: 'Reykjavik\'s oldest Italian restaurant, established 1979. Harbor-side charm, generous portions, classic pizzas.',
    address: 'Hafnarstræti 15',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1489, longitude: -21.9369 } as any,
    phone: '551 3340',
    website: 'https://hornid.is',
    opening_hours: { mán: '11:30-23', þri: '11:30-23', mið: '11:30-23', fim: '11:30-23', fös: '11:30-01', lau: '12-01', sun: '12-23' },
    price_level: 3,
    features: ['Dine-in', 'Bar', 'Sögulegt'],
    image_urls: ['https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Sögulegt', 'Klassískt', 'Höfn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'reykjavik-pizzeria',
    name: 'Reykjavik Pizzeria',
    slug: 'reykjavik-pizzeria',
    description_is: 'Eldbakaðar pizzur á hagstæðu verði. Stórt úrval af hefðbundnum og nýstárlegum pizzum.',
    description_en: 'Fire-baked pizzas at affordable prices. Wide selection of traditional and unique pies.',
    address: 'Háteigsvegur 9',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1412, longitude: -21.9120 } as any,
    phone: '562 4444',
    website: 'https://reykjavikpizzeria.is',
    opening_hours: { mán: '11:30-21:30', þri: '11:30-21:30', mið: '11:30-21:30', fim: '11:30-21:30', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Eldbakað', 'Hagstætt', 'Vegan'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'bakabaka',
    name: 'BakaBaka',
    slug: 'bakabaka',
    description_is: 'Bakarí að degi, pizzería að kvöldi. Langur hefunartími gefur djúpt og flókið bragð.',
    description_en: 'Bakery by day, pizzeria by evening. Long fermentation creates deep, complex flavors.',
    address: 'Skólavörðustígur 36',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1440, longitude: -21.9274 } as any,
    opening_hours: { mán: '17-21', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '17-22', sun: 'Lokað' },
    price_level: 3,
    features: ['Dine-in', 'Bakarí', 'Súrdeig'],
    image_urls: ['https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.7, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Súrdeig', 'Bakarí', 'Hefun'],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'kaffi-laugalaekur',
    name: 'Kaffi Laugalækur',
    slug: 'kaffi-laugalaekur',
    description_is: 'Hverfis-gastrobar með verðlaunuðum súrdeigspizzum. Huggulegt og staðbundið.',
    description_en: 'Neighborhood gastro bar with award-winning sourdough pizzas. Cozy and local.',
    address: 'Laugalækur 6',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1404, longitude: -21.8985 } as any,
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Bar', 'Súrdeig', 'Verðlaunað'],
    image_urls: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Gastro bar', 'Súrdeig', 'Verðlaunað'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'rossopomodoro',
    name: 'Rossopomodoro',
    slug: 'rossopomodoro',
    description_is: 'Napólískur veitingastaður á Laugavegi. Ekta ítölsk pizza, pasta og vín.',
    description_en: 'Neapolitan chain restaurant on Laugavegur. Authentic Italian pizza, pasta, and wine.',
    address: 'Laugavegur 40',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1448, longitude: -21.9256 } as any,
    website: 'https://rossopomodoro.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 3,
    features: ['Dine-in', 'Vín', 'Napólí'],
    image_urls: ['https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Keðja', 'Vín'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'napoli-pizza-rvk',
    name: 'Napoli Pizza',
    slug: 'napoli-pizza-rvk',
    description_is: 'Hefðbundin napólísk pizza á besta matarsvæði Reykjavíkur. Ferskt deig daglega.',
    description_en: 'Traditional Neapolitan pizza in Reykjavik\'s best food district. Fresh dough daily.',
    address: 'Tryggvagata 14',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1495, longitude: -21.9392 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Napólí', 'Hefðbundin'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'glosteinnn',
    name: 'Glósteinn',
    slug: 'glosteinn',
    description_is: 'Steinbökuð pizza á hagstæðu verði. Stórt úrval og góðir hádegisréttir.',
    description_en: 'Stone-baked pizza at affordable prices. Wide selection and great lunch deals.',
    address: 'Hringbraut 119',
    city: 'Reykjavík',
    postal_code: '107',
    location: { latitude: 64.1390, longitude: -21.9280 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 1,
    features: ['Takeaway', 'Delivery', 'Hagstætt'],
    image_urls: ['https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Hagstætt', 'Steinbakað', 'Delivery'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-popolare',
    name: 'Pizza Popolare Pósthús',
    slug: 'pizza-popolare',
    description_is: 'Í gamla pósthúsinu í Austurstræti. Viðarofnsbakaðar pizzur og ítalskt andrúmsloft.',
    description_en: 'In the old post office on Austurstræti. Wood-fired and Italian atmosphere.',
    address: 'Austurstræti 13',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1477, longitude: -21.9351 } as any,
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 3,
    features: ['Dine-in', 'Viðarofn', 'Sögulegt hús'],
    image_urls: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Miðborg', 'Sögulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── AKUREYRI ───
  {
    id: 'pizzasmidjan-akureyri',
    name: 'Pizzasmiðjan',
    slug: 'pizzasmidjan-akureyri',
    description_is: 'Viðarofnspizza í hjarta Akureyrar. Rólegt og huggulegt andrúmsloft.',
    description_en: 'Wood-fired pizza in the heart of Akureyri. Relaxed and cozy atmosphere.',
    address: 'Kaupvangsstræti 6',
    city: 'Akureyri',
    postal_code: '600',
    location: { latitude: 65.6835, longitude: -18.0878 } as any,
    website: 'https://pizzasmidjan.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1585238342024-78d387f4a707?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Viðarofn', 'Akureyri', 'Norðurland'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'greifinn-akureyri',
    name: 'Greifinn',
    slug: 'greifinn-akureyri',
    description_is: 'Vinsæll staður á Akureyri þar sem hægt er að borða pizzur, borgara og íslenska rétti. Fjölskylduvænlegt.',
    description_en: 'Popular Akureyri spot serving pizzas, burgers, and Icelandic dishes. Family-friendly.',
    address: 'Glerárgata 20',
    city: 'Akureyri',
    postal_code: '600',
    location: { latitude: 65.6810, longitude: -18.0930 } as any,
    phone: '460 1600',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Fjölskylduvænlegt', 'Bar'],
    image_urls: ['https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Fjölskylda', 'Akureyri'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── HÖFUÐBORGARSVÆÐIÐ ───
  {
    id: 'islenska-flatbakan',
    name: 'Íslenska Flatbakan',
    slug: 'islenska-flatbakan',
    description_is: 'Íslensku flatbökurnar — pizzur með íslensku ívafi. Stórt úrval og fjölskylduvænlegt.',
    description_en: 'The Icelandic Flatbread — pizzas with an Icelandic twist. Wide selection and family-friendly.',
    address: 'Dalshraun 1',
    city: 'Kópavogur',
    postal_code: '201',
    location: { latitude: 64.1049, longitude: -21.8900 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Takeaway', 'Delivery', 'Fjölskylduvænlegt'],
    image_urls: ['https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0,
    likes_count: 0, is_verified: false, tags: ['Kópavogur', 'Íslensku'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'castello-hafnarfjordur',
    name: 'Castello Pizzeria',
    slug: 'castello-hafnarfjordur',
    description_is: 'Klassísk pizzería í Hafnarfirði. Þykk og þunn skorpa, stórt áleggsval.',
    description_en: 'Classic pizzeria in Hafnarfjörður. Thick and thin crust options, wide topping selection.',
    address: 'Strandgata 55',
    city: 'Hafnarfjörður',
    postal_code: '220',
    location: { latitude: 64.0650, longitude: -21.9580 } as any,
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1,
    likes_count: 0, is_verified: false, tags: ['Hafnarfjörður', 'Klassísk'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── KEFLAVÍK ───
  {
    id: 'antons-mamma-mia',
    name: 'Antons Mamma Mia',
    slug: 'antons-mamma-mia',
    description_is: 'Steinofnspizzur í Keflavík. Huggulegt og rólegt andrúmsloft með ítölskum matseðli.',
    description_en: 'Stone-oven pizzas in Keflavik. Cozy atmosphere with a full Italian menu.',
    address: 'Hafnargata 32',
    city: 'Keflavík',
    postal_code: '230',
    location: { latitude: 64.0048, longitude: -22.5631 } as any,
    phone: '421 5533',
    website: 'https://antons.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Steinofn', 'Pasta'],
    image_urls: ['https://images.unsplash.com/photo-1485182708500-e8f1f318ba72?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Steinofn', 'Keflavík', 'Ítalía'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'fernandos-keflavik',
    name: 'Fernando\'s',
    slug: 'fernandos-keflavik',
    description_is: 'Vinsæll ítalskur veitingastaður í Keflavík. Ferskar pizzur og pasta með íslensku ívafi.',
    description_en: 'Popular Italian restaurant in Keflavik. Fresh pizzas and pasta with an Icelandic twist.',
    address: 'Hafnargata 5',
    city: 'Keflavík',
    postal_code: '230',
    location: { latitude: 64.0052, longitude: -22.5580 } as any,
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Keflavík', 'Ítalía'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'italiano-kopavogur',
    name: 'Italiano Pizzeria',
    slug: 'italiano-kopavogur',
    description_is: 'Ítölsk pizzería í Kópavogi. Vænir skammtar og klassískar pizzur.',
    description_en: 'Italian pizzeria in Kópavogur. Generous portions and classic pizzas.',
    address: 'Smáratorg',
    city: 'Kópavogur',
    postal_code: '201',
    location: { latitude: 64.1069, longitude: -21.8822 } as any,
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2,
    likes_count: 0, is_verified: false, tags: ['Kópavogur', 'Klassísk'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-braedur-mosfellsbaer',
    name: 'Pizza Bræður',
    slug: 'pizza-braedur-mosfellsbaer',
    description_is: 'Nýtt pizzahús í Mosfellsbæ. Bræðurnir baka ferskar pizzur daglega.',
    description_en: 'New pizza spot in Mosfellsbær. The brothers bake fresh pizzas daily.',
    address: 'Háholt 13',
    city: 'Mosfellsbær',
    postal_code: '270',
    location: { latitude: 64.1666, longitude: -21.6966 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3,
    likes_count: 0, is_verified: false, tags: ['Mosfellsbær', 'Nýtt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── AUSTURLAND (Höfn) ───
  {
    id: 'ishusid-pizzeria-hofn',
    name: 'Íshúsið Pizzeria',
    slug: 'ishusid-pizzeria-hofn',
    description_is: 'Þekkt fyrir sígildar steinofnspizzur í gamla íshúsinu á Höfn. Humarinn þeirra er goðsagnakenndur!',
    description_en: 'Famous for classic stone-oven pizzas in the old icehouse in Höfn. Their local langoustine is legendary!',
    address: 'Heppuvegur 2a',
    city: 'Höfn í Hornafirði',
    postal_code: '780',
    location: { latitude: 64.2505, longitude: -15.2078 } as any,
    phone: '478 1220',
    website: 'https://ishusidpizzeria.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Steinofn', 'Humar'],
    image_urls: ['https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.7, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Höfn', 'Humar', 'Steinofn'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── LANDSBYGGÐIN (Lota 4) ───
  {
    id: 'pizzafjordur',
    name: 'Pizzafjörður',
    slug: 'pizzafjordur',
    description_is: 'Lítil pizzería á Eskifirði með frábærar pizzur og vinalegt fólk. Ferskt deig, mikið áleggsúrval og rólegt andrúmsloft á Austfjörðum.',
    description_en: 'Small pizzeria in Eskifjörður with amazing pizza and friendly staff. Fresh dough, lots of toppings, and calm East Iceland vibes.',
    address: 'Strandgata 25',
    city: 'Eskifjörður',
    postal_code: '735',
    location: { latitude: 65.0712, longitude: -14.0131 } as any,
    opening_hours: { sun: '17-21', mán: '17-21', þri: '17-21', mið: '17-21', fim: 'Lokað', fös: 'Lokað', lau: 'Lokað' },
    price_level: 2,
    features: ['Takeaway', 'Glutenlaust val'],
    image_urls: ['https://images.unsplash.com/photo-1600628421055-4d30de868b8f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.7, rating_tripadvisor: 5.0,
    likes_count: 0, is_verified: false, tags: ['Austfirðir', 'Eskifjörður', 'Huggulegt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-kofinn',
    name: 'Pizza Kofinn',
    slug: 'pizza-kofinn',
    description_is: 'Viðarofnspizza í bæjarkjarna Húsavíkur. Staðbundið, vinalegt og gott. Margherita, pepperóní og Parma.',
    description_en: 'Wood-fired pizza in the heart of Húsavík. Local, friendly, and delicious. Margherita, pepperoni, and Parma.',
    address: 'Hafnarstétt 9',
    city: 'Húsavík',
    postal_code: '640',
    location: { latitude: 66.0449, longitude: -17.3389 } as any,
    website: 'https://pizzakofinn.is',
    opening_hours: { mán: '12-21', þri: '12-21', mið: '12-21', fim: '12-21', fös: '12-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Húsavík', 'Norðurland'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'askur-pizzeria',
    name: 'Askur Pizzeria',
    slug: 'askur-pizzeria',
    description_is: 'Staðbundin brugghús-pizzería á Egilsstöðum. Búðu til þína eigin pizzu eða veldu af matseðli.',
    description_en: 'Local brewery pizzeria in Egilsstaðir. Build your own pizza or choose from the menu.',
    address: 'Fagradalsbraut 25',
    city: 'Egilsstaðir',
    postal_code: '700',
    location: { latitude: 65.2535, longitude: -14.3948 } as any,
    phone: '470 6070',
    website: 'https://askurpizzeria.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-21', lau: '11:30-21', sun: '11:30-21' },
    price_level: 2,
    features: ['Dine-in', 'Brugghús', 'Sérsniðið'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Brugghús', 'Egilsstaðir', 'Austfirðir'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'stykkid-pizzeria',
    name: 'Stykkið Pizzeria',
    slug: 'stykkid-pizzeria',
    description_is: 'Pizzería í fallegasta bæ Vesturlands. Ferskt deig og staðbundin hráefni.',
    description_en: 'Pizzeria in western Iceland\'s most beautiful town. Fresh dough and local ingredients.',
    address: 'Aðalgata 3',
    city: 'Stykkishólmur',
    postal_code: '340',
    location: { latitude: 65.0758, longitude: -22.7300 } as any,
    opening_hours: { mán: '12-21', þri: '12-21', mið: '12-21', fim: '12-21', fös: '12-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Stykkishólmur', 'Snæfellsnes'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── SELFOSS ───
  {
    id: 'flatey-pizza-selfoss',
    name: 'Flatey Pizza Selfoss',
    slug: 'flatey-pizza-selfoss',
    description_is: 'Útibú Flatey Pizza á Selfossi. Sömu einkennandi napólísku pizzurnar úr viðarofni.',
    description_en: 'Flatey Pizza branch in Selfoss. Same signature Neapolitan wood-fired pizzas.',
    address: 'Austurvegur 1',
    city: 'Selfoss',
    postal_code: '800',
    location: { latitude: 63.9355, longitude: -21.0035 } as any,
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Viðarofn', 'Selfoss'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'kaffi-krus',
    name: 'Kaffi Krús',
    slug: 'kaffi-krus',
    description_is: 'Huggulegt kaffihús á Selfossi. Stökkar pizzur og borgarar ásamt steinbökuðu brauði.',
    description_en: 'Cozy café in Selfoss. Crispy pizzas, burgers, and artisan bread.',
    address: 'Austurvegur 7',
    city: 'Selfoss',
    postal_code: '800',
    location: { latitude: 63.9353, longitude: -21.0020 } as any,
    website: 'https://kaffikrus.is',
    opening_hours: { mán: '08-22', þri: '08-22', mið: '08-22', fim: '08-22', fös: '08-23', lau: '09-23', sun: '09-22' },
    price_level: 2,
    features: ['Dine-in', 'Kaffi', 'Brauð'],
    image_urls: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Kaffi', 'Selfoss', 'Huggulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── VESTMANNAEYJAR ───
  {
    id: 'pitsugerdin',
    name: 'Pítsugerðin',
    slug: 'pitsugerdin',
    description_is: 'Ekta viðarofnspizza í Vestmannaeyjum. San Marzano tómatar, súrdeig og staðbundinn bjór á krana.',
    description_en: 'Authentic wood-fired pizza in the Westman Islands. San Marzano tomatoes, sourdough, and local craft beer.',
    address: 'Vestmannabraut 28',
    city: 'Vestmannaeyjar',
    postal_code: '900',
    location: { latitude: 63.4427, longitude: -20.2690 } as any,
    opening_hours: { mán: 'Lokað', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Viðarofn', 'Bjór'],
    image_urls: ['https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Vestmannaeyjar', 'Súrdeig'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-67-vestmannaeyjar',
    name: 'Pizza 67',
    slug: 'pizza-67-vestmannaeyjar',
    description_is: 'Ítölsk pizza í Eyjum. Stórt úrval á hagstæðu verði.',
    description_en: 'Italian pizza in the Westman Islands. Wide selection at affordable prices.',
    address: 'Bárustígur 11',
    city: 'Vestmannaeyjar',
    postal_code: '900',
    location: { latitude: 63.4420, longitude: -20.2680 } as any,
    opening_hours: { mán: '17-21', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '12-22', sun: '12-21' },
    price_level: 1,
    features: ['Takeaway', 'Delivery', 'Hagstætt'],
    image_urls: ['https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2,
    likes_count: 0, is_verified: false, tags: ['Hagstætt', 'Vestmannaeyjar'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── ÍSAFJÖRÐUR ───
  {
    id: 'hamraborg-isafjordur',
    name: 'Hamraborg',
    slug: 'hamraborg-isafjordur',
    description_is: 'Pizzería á Ísafirði. 12 tommu pizzur með þremur áleggsvalkostum. Einfalt og gott.',
    description_en: '12-inch pizzas with three toppings in Ísafjörður. Simple and delicious.',
    address: 'Hafnarstræti 7',
    city: 'Ísafjörður',
    postal_code: '400',
    location: { latitude: 66.0742, longitude: -23.1350 } as any,
    website: 'https://hamraborg.com',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3,
    likes_count: 0, is_verified: false, tags: ['Ísafjörður', 'Vestfirðir'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── HÖFUÐBORGARSVÆÐIÐ ───
  {
    id: 'pizzan-hafnarfjordur',
    name: 'Pizzan Hafnarfjörður',
    slug: 'pizzan-hafnarfjordur',
    description_is: 'Útibú Pizzunnar á Fjarðargötu. Vinsælar pizzur og meðlæti.',
    description_en: 'Pizzan branch on Fjarðargata. Popular pizzas and sides.',
    address: 'Fjarðargata 13-15',
    city: 'Hafnarfjörður',
    postal_code: '220',
    location: { latitude: 64.0671, longitude: -21.9549 } as any,
    website: 'https://pizzan.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1,
    likes_count: 0, is_verified: false, tags: ['Hafnarfjörður', 'Keðja'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'flatey-pizza-gardabaer',
    name: 'Flatey Pizza Garðatorg',
    slug: 'flatey-pizza-gardabaer',
    description_is: 'Flatey Pizza útibú á Garðatorgi í Garðabæ. Sömu napólísku pizzurnar úr viðarofni.',
    description_en: 'Flatey Pizza branch at Garðatorg in Garðabær. Same Neapolitan wood-fired pizzas.',
    address: 'Garðatorg 7',
    city: 'Garðabær',
    postal_code: '210',
    location: { latitude: 64.0897, longitude: -21.9230 } as any,
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '11-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Viðarofn', 'Garðabær'],
    created_at: null as any, updated_at: null as any,
  },

];

export const mockMenuItems: MenuItem[] = [
  // ─── Flatey Pizza (Scraped 2026-03) ───
  { id: 'fp-1', restaurant_id: 'flatey-pizza', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano tómatar, Ferskur mozzarella, Basilíka, Ólífuolía', description_en: '', price: 3090, category: 'Pizzur', sort_order: 1 },
  { id: 'fp-2', restaurant_id: 'flatey-pizza', name_is: 'Diavola', name_en: 'Diavola', description_is: 'Pepperoni (smáskorið) á Margheritu-grunni', description_en: '', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'fp-3', restaurant_id: 'flatey-pizza', name_is: 'Monella', name_en: 'Monella', description_is: 'San Marzano tómatar, Ferskur mozzarella, Parmesan, Oregano, Chili flögur, Basilíka, Ólífuolía', description_en: '', price: 3290, category: 'Pizzur', sort_order: 3 },
  { id: 'fp-4', restaurant_id: 'flatey-pizza', name_is: 'Cotto', name_en: 'Cotto', description_is: 'San Marzano tómatar, Ferskur mozzarella, Silkiskorin skinka, Sveppir, Mascarpone rjómaostur, Ólífuolía og Basilíka', description_en: '', price: 3590, category: 'Pizzur', sort_order: 4 },
  { id: 'fp-5', restaurant_id: 'flatey-pizza', name_is: 'Padrino', name_en: 'Padrino', description_is: 'San Marzano tómatar, Ferskur mozzarella, Pepperoni, Pikklaður chili, Hunang, Basilíka', description_en: '', price: 3590, category: 'Pizzur', sort_order: 5 },
  { id: 'fp-6', restaurant_id: 'flatey-pizza', name_is: 'Umberto', name_en: 'Umberto', description_is: 'San Marzano tómatar, Ferskur mozzarella, Pepperoni, Döðlur, Mascarpone rjómaostur, Basilíka', description_en: '', price: 3590, category: 'Pizzur', sort_order: 6 },
  { id: 'fp-7', restaurant_id: 'flatey-pizza', name_is: 'Mánaðarins: Chili Crisp', name_en: 'Chili Crisp', description_is: 'Hvít pizza, mozzarella, cheddar, kartöflur, hvítlaukur, crispy chili olía, mascarpone', description_en: '', price: 3590, category: 'Pizzur', sort_order: 7 },
  { id: 'fp-8', restaurant_id: 'flatey-pizza', name_is: 'Bianca', name_en: 'Bianca', description_is: 'Mozzarella, Parmesan, Ricotta, Pepperoni, Hvítlaukur og Mike\'s Hot Honey.', description_en: '', price: 3690, category: 'Pizzur', sort_order: 8 },
  { id: 'fp-9', restaurant_id: 'flatey-pizza', name_is: 'Nduja', name_en: 'Nduja', description_is: 'Nduja kryddpylsa, Ricotta á Margheritu-grunni', description_en: '', price: 3790, category: 'Pizzur', sort_order: 9 },
  { id: 'fp-10', restaurant_id: 'flatey-pizza', name_is: 'Parma', name_en: 'Parma', description_is: 'San Marzano tómatar, Ferskur mozzarella, Hráskinka, Klettasalat, Parmesan, Basilíka, Ólífuolía', description_en: '', price: 3990, category: 'Pizzur', sort_order: 10 },
  { id: 'fp-11', restaurant_id: 'flatey-pizza', name_is: 'Stracciatella', name_en: 'Stracciatella', description_is: 'Hvít pizza, Hráskinka, Mozzarella, Stracciatella ostur, Basilolía og Parmesan', description_en: '', price: 3990, category: 'Pizzur', sort_order: 11 },
  { id: 'fp-12', restaurant_id: 'flatey-pizza', name_is: 'Nutella Pizza', name_en: 'Nutella', description_is: 'Nutella Pizza með mascarpone og flórsykri', description_en: '', price: 2190, category: 'Eftirréttir', sort_order: 12 },
  // ─── Olifa La Madre (Scraped 2026-03) ───
  { id: 'ol-1', restaurant_id: 'olifa-la-madre', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Pelati tomato sauce, mozzarella, fresh basil', description_en: '', price: 2899, category: 'Pizzur', sort_order: 1 },
  { id: 'ol-2', restaurant_id: 'olifa-la-madre', name_is: 'Pancetta', name_en: 'Pancetta', description_is: 'Mozzarella, Parmigiano cheese, Pancetta ham, caramelised red onion, balsamic vinegar', description_en: '', price: 2899, category: 'Pizzur', sort_order: 2 },
  { id: 'ol-3', restaurant_id: 'olifa-la-madre', name_is: 'Speck', name_en: 'Speck', description_is: 'Mozzarella, cream cheese, Speck seasoned dry ham, caramelised red onion', description_en: '', price: 2899, category: 'Pizzur', sort_order: 3 },
  { id: 'ol-4', restaurant_id: 'olifa-la-madre', name_is: 'Crudo e Burrata', name_en: 'Crudo e Burrata', description_is: 'Parma Crudo riserva 24 months, ruccola, burrata cheese', description_en: '', price: 2899, category: 'Pizzur', sort_order: 4 },
  { id: 'ol-5', restaurant_id: 'olifa-la-madre', name_is: '4 Formaggi', name_en: '4 Formaggi', description_is: 'Mozzarella, Asiago, Gorgonzola, Parmigiano, Savani truffles', description_en: '', price: 2899, category: 'Pizzur', sort_order: 5 },
  { id: 'ol-6', restaurant_id: 'olifa-la-madre', name_is: 'Cotto', name_en: 'Cotto', description_is: 'Mozzarella, burrata, Parmigiano, Cotto cooked ham, oven baked mushrooms', description_en: '', price: 2899, category: 'Pizzur', sort_order: 6 },
  { id: 'ol-7', restaurant_id: 'olifa-la-madre', name_is: 'Super Piccante', name_en: 'Super Piccante', description_is: 'Pelati, mozzarella, Spianata Calabrese, Nduja, caramelised red onion', description_en: '', price: 2899, category: 'Pizzur', sort_order: 7 },
  { id: 'ol-8', restaurant_id: 'olifa-la-madre', name_is: 'Spianata e Funghi', name_en: 'Spianata e Funghi', description_is: 'Pelati, mozzarella, Spianata Calabrese, oven baked mushrooms, Olifa chili honey', description_en: '', price: 2899, category: 'Pizzur', sort_order: 8 },
  // ─── Daddi's Pizza (Scraped 2026-03) ───
  { id: 'dp-1', restaurant_id: 'daddis-pizza', name_is: 'Mýfluga', name_en: 'Mýfluga', description_is: 'Tomato sauce, cheese, smoked trout, pine nuts, cream cheese', description_en: '', price: 3315, category: 'Pizzur', sort_order: 1 },
  { id: 'dp-2', restaurant_id: 'daddis-pizza', name_is: 'Mjaltakonan', name_en: 'Mjaltakonan', description_is: 'Tomato sauce, cheese, tomatoes, mozzarella, fresh basil', description_en: '', price: 3315, category: 'Pizzur', sort_order: 2 },
  { id: 'dp-3', restaurant_id: 'daddis-pizza', name_is: 'Námaskarð', name_en: 'Námaskarð', description_is: 'Tomato sauce, cheese, spicy salami, extra cheese, mini salami, chili flakes', description_en: '', price: 3200, category: 'Pizzur', sort_order: 3 },
  { id: 'dp-4', restaurant_id: 'daddis-pizza', name_is: 'Vogar', name_en: 'Vogar', description_is: 'BBQ-sauce, cheese, salami, onion, mushrooms, sun-dried tomatoes', description_en: '', price: 3315, category: 'Pizzur', sort_order: 4 },
  { id: 'dp-5', restaurant_id: 'daddis-pizza', name_is: 'Lónið', name_en: 'Lónið', description_is: 'Tomato sauce, cheese, ham, salami, beef, minced bacon', description_en: '', price: 3200, category: 'Pizzur', sort_order: 5 },
  { id: 'dp-6', restaurant_id: 'daddis-pizza', name_is: 'Hverfjall', name_en: 'Hverfjall', description_is: 'Garlic oil, cheese, ham, salami, mushrooms, onion, sliced bacon', description_en: '', price: 3315, category: 'Pizzur', sort_order: 6 },
  { id: 'dp-7', restaurant_id: 'daddis-pizza', name_is: 'Dimmuborgir', name_en: 'Dimmuborgir', description_is: 'Tomato sauce, cheese, ham, salami, onion, pineapple', description_en: '', price: 3080, category: 'Pizzur', sort_order: 7 },
  { id: 'dp-8', restaurant_id: 'daddis-pizza', name_is: 'Krafla', name_en: 'Krafla', description_is: 'Tomato sauce, cheese, blue cheese, cream cheese, pepper cheese, parmesan', description_en: '', price: 3200, category: 'Pizzur', sort_order: 8 },
  // ─── Eldofninn (Scraped 2026-03) ───
  { id: 'el-1', restaurant_id: 'eldofninn', name_is: 'Naut & Benni', name_en: 'Naut & Benni', description_is: 'Ostur, ruccola, roast beef, pikklaður laukur, súrar gúrkur, bernaise sósa, steiktur laukur, svartur pipar, salt', description_en: '', price: 4300, category: 'Pizzur', sort_order: 1 },
  { id: 'el-2', restaurant_id: 'eldofninn', name_is: 'A - Margarita', name_en: 'Margarita', description_is: 'Eldofnssósa, ostur, oregano', description_en: '', price: 2450, category: 'Pizzur', sort_order: 2 },
  { id: 'el-3', restaurant_id: 'eldofninn', name_is: 'C2 - Pepperoni Trio', name_en: 'Pepperoni Trio', description_is: 'Ostur, pepperoni, sveppir, rjómaostur', description_en: '', price: 3700, category: 'Pizzur', sort_order: 3 },
  { id: 'el-4', restaurant_id: 'eldofninn', name_is: 'E - Eldofninn', name_en: 'Eldofninn', description_is: 'Ostur, jalapeno, bl. ólífur, gr. piparkorn, piparostur', description_en: '', price: 3440, category: 'Pizzur', sort_order: 4 },
  { id: 'el-5', restaurant_id: 'eldofninn', name_is: 'N - Kjötveisla', name_en: 'Meat Feast', description_is: 'Ostur, skinka, nautahakk, pepperoni', description_en: '', price: 3950, category: 'Pizzur', sort_order: 5 },
  { id: 'el-6', restaurant_id: 'eldofninn', name_is: 'O - Ostaveisla', name_en: 'Cheese Feast', description_is: 'Ostur, rjómaostur, piparostur, gráðaostur (sulta fylgir)', description_en: '', price: 4050, category: 'Pizzur', sort_order: 6 },
  { id: 'el-7', restaurant_id: 'eldofninn', name_is: 'S - Salat Pizza', name_en: 'Salad Pizza', description_is: 'Ostur, ruccola, rauðlaukur, paprika, ólífur, parmesan, eldofnsolía', description_en: '', price: 4350, category: 'Pizzur', sort_order: 7 },
  { id: 'el-8', restaurant_id: 'eldofninn', name_is: 'U - Surf’n Turf', name_en: 'Surf’n Turf', description_is: 'Ostur, nautahakk, rækjur, rauðlaukur', description_en: '', price: 3750, category: 'Pizzur', sort_order: 8 },
  // ─── Hornið (Scraped 2026-03) ───
  { id: 'ho-1', restaurant_id: 'hornid', name_is: 'Pizza Margherita', name_en: 'Margherita', description_is: 'Cheese, sauce.', description_en: '', price: 2890, category: 'Pizzur', sort_order: 1 },
  { id: 'ho-2', restaurant_id: 'hornid', name_is: 'Pizza Roma', name_en: 'Roma', description_is: 'Cheese, pepperoni, blue cheese, pineapple, green peppercorns.', description_en: '', price: 4290, category: 'Pizzur', sort_order: 2 },
  { id: 'ho-3', restaurant_id: 'hornid', name_is: 'Pizza Pescatore', name_en: 'Pescatore', description_is: 'Cheese, shrimps, mussels.', description_en: '', price: 3790, category: 'Pizzur', sort_order: 3 },
  { id: 'ho-4', restaurant_id: 'hornid', name_is: 'Pizza Quattro Formaggi', name_en: 'Four Cheese', description_is: 'Four kinds of cheese.', description_en: '', price: 4290, category: 'Pizzur', sort_order: 4 },
  { id: 'ho-5', restaurant_id: 'hornid', name_is: 'Pizza Americana', name_en: 'Americana', description_is: 'Cheese, ground beef, mushrooms.', description_en: '', price: 3390, category: 'Pizzur', sort_order: 5 },
  { id: 'ho-6', restaurant_id: 'hornid', name_is: 'Pizza Quattro Stagioni', name_en: 'Four Seasons', description_is: 'Cheese, mushrooms, ham, pepperoni, peppers.', description_en: '', price: 4290, category: 'Pizzur', sort_order: 6 },
  { id: 'ho-7', restaurant_id: 'hornid', name_is: 'Pizza Perez', name_en: 'Perez', description_is: 'Cheese, ground beef, pepperoni, olives, jalapeños.', description_en: '', price: 4290, category: 'Pizzur', sort_order: 7 },
  { id: 'ho-8', restaurant_id: 'hornid', name_is: 'Pizza con Parma e Rucola', name_en: 'Parma & Rucola', description_is: 'Cheese, Parma ham, rucola, parmesan.', description_en: '', price: 4290, category: 'Pizzur', sort_order: 8 },
  // ─── Reykjavik Pizzeria (Scraped 2026-03) ───
  { id: 'rp-1', restaurant_id: 'reykjavik-pizzeria', name_is: 'Margherita 12"', name_en: 'Margherita 12"', description_is: 'Sósa, ostur, oregano', description_en: '', price: 2590, category: 'Pizzur', sort_order: 1 },
  { id: 'rp-2', restaurant_id: 'reykjavik-pizzeria', name_is: 'Hawaii 12"', name_en: 'Hawaii 12"', description_is: 'Sósa, ostur, skinka, ananas', description_en: '', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'rp-3', restaurant_id: 'reykjavik-pizzeria', name_is: 'Viðar 12"', name_en: 'Viðar 12"', description_is: 'Sósa, ostur, pepperoni, laukur, ananas', description_en: '', price: 3490, category: 'Pizzur', sort_order: 3 },
  { id: 'rp-4', restaurant_id: 'reykjavik-pizzeria', name_is: 'Chili Banana 12"', name_en: 'Chili Banana 12"', description_is: 'Sósa, ostur, pepperoni, bananar, chili krydd', description_en: '', price: 3290, category: 'Pizzur', sort_order: 4 },
  { id: 'rp-5', restaurant_id: 'reykjavik-pizzeria', name_is: 'Pizza Flugvirkjans 12"', name_en: 'Flight Mechanic’s Pizza 12"', description_is: 'Sósa, ostur, pepperoni, hvítlaukur, sveppir, jalapeno, græn paprika, sólþurrkaðir tómatar, græn piparkorn, rjómaostur, svartur pipar, oregano, Salthnetur', description_en: '', price: 4090, category: 'Pizzur', sort_order: 5 },
  { id: 'rp-6', restaurant_id: 'reykjavik-pizzeria', name_is: 'Camembert 12"', name_en: 'Camembert 12"', description_is: 'Sósa, ostur, skinka, sveppir, camembert, grænn aspas', description_en: '', price: 3690, category: 'Pizzur', sort_order: 6 },
  { id: 'rp-7', restaurant_id: 'reykjavik-pizzeria', name_is: 'Reykjavík 12"', name_en: 'Reykjavík 12"', description_is: 'Sósa, ostur, hvítlaukur, skinka, sveppir, paprika', description_en: '', price: 3690, category: 'Pizzur', sort_order: 7 },
  { id: 'rp-8', restaurant_id: 'reykjavik-pizzeria', name_is: 'Parma 12"', name_en: 'Parma 12"', description_is: 'Sósa, ostur, ítölsk hráskinka, klettasalat, ferskur parmesan', description_en: '', price: 3990, category: 'Pizzur', sort_order: 8 },
  { id: 'rp-9', restaurant_id: 'reykjavik-pizzeria', name_is: 'Tex Mex 12"', name_en: 'Tex Mex 12"', description_is: 'Sósa, ostur, kjúklingur, jalapeño, laukur, maís baunir, rjómaostur', description_en: '', price: 3790, category: 'Pizzur', sort_order: 9 },
  { id: 'rp-10', restaurant_id: 'reykjavik-pizzeria', name_is: 'Kaninn 12"', name_en: 'Kaninn 12"', description_is: 'Sósa, ostur, nautahakk, laukur, beikon, sveppir, paprika, svartur pipar', description_en: '', price: 3890, category: 'Pizzur', sort_order: 10 },
  // ─── BakaBaka (Scraped 2026-03) ───
  { id: 'bb-1', restaurant_id: 'bakabaka', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Siccagno tómatsósa, Mozzarella, Basil', description_en: '', price: 3200, category: 'Pizzur', sort_order: 1 },
  { id: 'bb-2', restaurant_id: 'bakabaka', name_is: 'Pepperoni', name_en: 'Pepperoni', description_is: 'Siccagno tómatsósa, Mozzarella, Pepperoni, Chili flögur', description_en: '', price: 3600, category: 'Pizzur', sort_order: 2 },
  { id: 'bb-3', restaurant_id: 'bakabaka', name_is: 'Parma', name_en: 'Parma', description_is: 'Siccagno tómatsósa, Mozzarella, Parma skinka, Rúkkóla, Parmigiano', description_en: '', price: 3800, category: 'Pizzur', sort_order: 3 },
  { id: 'bb-4', restaurant_id: 'bakabaka', name_is: 'Mortadella', name_en: 'Mortadella', description_is: 'Siccagno tómatsósa, Mortadella pylsa, Burrata, Sítrónuolía, Pistasíur', description_en: '', price: 3800, category: 'Pizzur', sort_order: 4 },
  { id: 'bb-5', restaurant_id: 'bakabaka', name_is: 'Tonno e cipolle', name_en: 'Tonno e cipolle', description_is: 'Siccagno tómatsósa, Mozzarella, Rauðlaukur, Túnfiskur, Djúpsteiktar kapers, Pikklaður chili', description_en: '', price: 3600, category: 'Pizzur', sort_order: 5 },
  { id: 'bb-6', restaurant_id: 'bakabaka', name_is: 'Diavola', name_en: 'Diavola', description_is: 'Siccagno tómatsósa, Mozzarella, Sterk salami, Rauðlaukur, Ólífur, Chili flögur, Parmigiano', description_en: '', price: 3600, category: 'Pizzur', sort_order: 6 },
  { id: 'bb-7', restaurant_id: 'bakabaka', name_is: 'Bella Vegana', name_en: 'Bella Vegana', description_is: 'Siccagno tómatsósa, Grilluð paprika, Rauðlaukur, Ólífur, Pikklaður chili, Vegan rjómaostur', description_en: '', price: 3600, category: 'Pizzur', sort_order: 7 },
  { id: 'bb-8', restaurant_id: 'bakabaka', name_is: 'Scandinava', name_en: 'Scandinava', description_is: 'Mascarpone, Sterk salami, Rauðlaukur, Pikklaður chili, Garðakarsa', description_en: '', price: 3600, category: 'Pizzur', sort_order: 8 },
  { id: 'bb-9', restaurant_id: 'bakabaka', name_is: 'Stella di Nduja', name_en: 'Stella di Nduja', description_is: 'Mozzarella, Parmigiano, Nduja, Hægeldaður hvítlaukur, Ricotta', description_en: '', price: 3600, category: 'Pizzur', sort_order: 9 },
  { id: 'bb-10', restaurant_id: 'bakabaka', name_is: 'Bianca', name_en: 'Bianca', description_is: 'Mascarpone, Ostrusveppir, Hvítlauksolía, Villisveppa og truffluduft', description_en: '', price: 3600, category: 'Pizzur', sort_order: 10 },
  { id: 'bb-11', restaurant_id: 'bakabaka', name_is: 'Capra Rossa', name_en: 'Capra Rossa', description_is: 'Mozzarella, Geitaostur, Parmigiano, Hvítlauksolía, Rautt pestó, Prosciutto cotto', description_en: '', price: 3600, category: 'Pizzur', sort_order: 11 },
  { id: 'bb-12', restaurant_id: 'bakabaka', name_is: 'Patata', name_en: 'Patata', description_is: 'Mascarpone, Kartöflur, Gorgonzola, Rósmarín, Hunang', description_en: '', price: 3600, category: 'Pizzur', sort_order: 12 },
  // ─── Kaffi Laugalækur (Scraped 2026-03) ───
  { id: 'kl-1', restaurant_id: 'kaffi-laugalaekur', name_is: 'Litla Gula Hænan', name_en: 'Litla Gula Hænan', description_is: 'Kjúklingur, beikon, grænt pestó, ostur og tómatsósa. Toppað með salati, pikkluðum skalottlauk, konfekttómötum, hvítlauksdressingu og parmesan.', description_en: '', price: 3590, category: 'Pizzur', sort_order: 1 },
  { id: 'kl-2', restaurant_id: 'kaffi-laugalaekur', name_is: 'Pylsumeistarinn', name_en: 'Pylsumeistarinn', description_is: 'Beikon og kryddpylsur frá Pylsumeistaranum, sveppir, laukur, tómatsósa og ostur.', description_en: '', price: 3590, category: 'Pizzur', sort_order: 2 },
  { id: 'kl-3', restaurant_id: 'kaffi-laugalaekur', name_is: 'Geiteyjarströnd', name_en: 'Geiteyjarströnd', description_is: 'Reyktur silungur, pikklaður skalottlaukur, piparrótarsósa, soðið egg, grænt pestó, dill og ferskt salat.', description_en: '', price: 3590, category: 'Pizzur', sort_order: 3 },
  { id: 'kl-4', restaurant_id: 'kaffi-laugalaekur', name_is: 'Ostabaka', name_en: 'Cheese Pizza', description_is: 'Brí, gráðaostur, mozzarella, pikklaður laukur, salvía og heslihnetur.', description_en: '', price: 3490, category: 'Pizzur', sort_order: 4 },
  { id: 'kl-5', restaurant_id: 'kaffi-laugalaekur', name_is: 'Shawarmabaka', name_en: 'Shawarma Pizza', description_is: 'Rifið lambakjöt, shawarma sósa, ostur og laukur. Toppað með salati, rauðrófum, grænu pestóti, pikkluðu rauðkáli, pikkluðum chili, kóríander og hvítlauksdressingu.', description_en: '', price: 3590, category: 'Pizzur', sort_order: 5 },
  { id: 'kl-6', restaurant_id: 'kaffi-laugalaekur', name_is: 'Hnetukræsing', name_en: 'Hnetukræsing', description_is: 'Ostur, mozzarella, laukur, eggaldin, sveppir, tómatar, ólífur og Shawarma sósa. Toppaður með blöndu af hnetum og wasabibaunum.', description_en: '', price: 3195, category: 'Pizzur', sort_order: 6 },
  { id: 'kl-7', restaurant_id: 'kaffi-laugalaekur', name_is: 'Indversk baka (White chana)', name_en: 'Indian Pizza', description_is: 'Kjúklingabaunir með osti, rauðlauk, tómötum og fetaosti.', description_en: '', price: 3485, category: 'Pizzur', sort_order: 7 },
  { id: 'kl-8', restaurant_id: 'kaffi-laugalaekur', name_is: 'Hálfmáni', name_en: 'Calzone', description_is: 'Fylltur með osti, kryddpylsu og pikkluðum chili. Toppað með hvítlaukssmjöri, parmesan, grænu pestóti og salati til hliðar.', description_en: '', price: 3590, category: 'Pizzur', sort_order: 8 },
  { id: 'kl-9', restaurant_id: 'kaffi-laugalaekur', name_is: 'Dolce vita flatbaka', name_en: 'Dolce vita flatbaka', description_is: 'Sérréttur mánaðarins.', description_en: '', price: 2699, category: 'Pizzur', sort_order: 9 },
  { id: 'kl-10', restaurant_id: 'kaffi-laugalaekur', name_is: 'Barnabaka', name_en: 'Kids Pizza', description_is: 'Ostur og tómatsósa', description_en: '', price: 1480, category: 'Pizzur', sort_order: 10 },
  // ─── Rossopomodoro (Scraped 2026-03) ───
  { id: 'rs-1', restaurant_id: 'rossopomodoro', name_is: 'Calzone', name_en: 'Calzone', description_is: 'Tomato, mozzarella, mushrooms & ham', description_en: '', price: 4790, category: 'Pizzur', sort_order: 1 },
  { id: 'rs-2', restaurant_id: 'rossopomodoro', name_is: 'Capricciosa', name_en: 'Capricciosa', description_is: 'Tomato, mozzarella, ham, mushrooms, olives and artichokes', description_en: '', price: 4790, category: 'Pizzur', sort_order: 2 },
  { id: 'rs-3', restaurant_id: 'rossopomodoro', name_is: 'Corbarella', name_en: 'Corbarella', description_is: 'Mozzarella, cream, ham, mushrooms and black pepper', description_en: '', price: 4750, category: 'Pizzur', sort_order: 3 },
  { id: 'rs-4', restaurant_id: 'rossopomodoro', name_is: 'Formaggi', name_en: 'Formaggi', description_is: 'Mozzarella, ricotta, bufala, camembert and gorgonzola cheese', description_en: '', price: 4890, category: 'Pizzur', sort_order: 4 },
  { id: 'rs-5', restaurant_id: 'rossopomodoro', name_is: 'Hawaian', name_en: 'Hawaiian', description_is: 'Tomato, mozzarella, ham and pineapple', description_en: '', price: 4450, category: 'Pizzur', sort_order: 5 },
  { id: 'rs-6', restaurant_id: 'rossopomodoro', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tomato sauce, mozzarella and basil', description_en: '', price: 3890, category: 'Pizzur', sort_order: 6 },
  { id: 'rs-7', restaurant_id: 'rossopomodoro', name_is: 'Marinarella', name_en: 'Marinarella', description_is: 'Tomato, mozzarella, garlic, mussels, squid, prawns & scallops', description_en: '', price: 4990, category: 'Pizzur', sort_order: 7 },
  { id: 'rs-8', restaurant_id: 'rossopomodoro', name_is: 'Napoli', name_en: 'Napoli', description_is: 'Tomato sauce, cheese, oregano, anchovies, garlic and olives', description_en: '', price: 4890, category: 'Pizzur', sort_order: 8 },
  { id: 'rs-9', restaurant_id: 'rossopomodoro', name_is: 'Pizza del Piazzaiolo', name_en: 'Pizza del Piazzaiolo', description_is: 'The chef’s favorite, with fresh mozzarella, ham, pepperoni, pepper cheese and bacon', description_en: '', price: 4950, category: 'Pizzur', sort_order: 9 },
  { id: 'rs-10', restaurant_id: 'rossopomodoro', name_is: 'Pizzaiolo', name_en: 'Pizzaiolo', description_is: 'With pepperoni, jalapeño, minced meat and garlic', description_en: '', price: 4790, category: 'Pizzur', sort_order: 10 },
  { id: 'rs-11', restaurant_id: 'rossopomodoro', name_is: 'Rustica', name_en: 'Rustica', description_is: 'Tomato sauce, mozzarella, ham and mushrooms', description_en: '', price: 4550, category: 'Pizzur', sort_order: 11 },
  { id: 'rs-12', restaurant_id: 'rossopomodoro', name_is: 'Salmone', name_en: 'Salmone', description_is: 'Mozzarella, cream cheese, smoked salmon and rocket salad', description_en: '', price: 4950, category: 'Pizzur', sort_order: 12 },
  // ─── Napoli Pizza (Scraped 2026-03) ───
  { id: 'np-1', restaurant_id: 'napoli-pizza-rvk', name_is: 'Marinara', name_en: 'Marinara', description_is: 'Marinara sósa, ferskur hvítlaukur, fersk basilíka, oregano, svartur pipar, evo', description_en: '', price: 1890, category: 'Pizzur', sort_order: 1 },
  { id: 'np-2', restaurant_id: 'napoli-pizza-rvk', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano tómatsósa, ferskur mozzarella, fersk basilíka, evo', description_en: '', price: 2190, category: 'Pizzur', sort_order: 2 },
  { id: 'np-3', restaurant_id: 'napoli-pizza-rvk', name_is: 'Napoli', name_en: 'Napoli', description_is: 'San Marzano tómatsósa, fersk basilíka, ferskur mozzarella, pepperoni, svartur pipar, parmesan sneiðar, evo', description_en: '', price: 2590, category: 'Pizzur', sort_order: 3 },
  { id: 'np-4', restaurant_id: 'napoli-pizza-rvk', name_is: 'Salsiccia', name_en: 'Salsiccia', description_is: 'San Marzano tómatsósa, mozzarella, fersk basilíka, ítölsk pylsa, friarielli, chili olía', description_en: '', price: 2690, category: 'Pizzur', sort_order: 4 },
  { id: 'np-5', restaurant_id: 'napoli-pizza-rvk', name_is: 'Capricciosa', name_en: 'Capricciosa', description_is: 'San Marzano tómatsósa, ferskur mozzarella, fersk basilíka, skinka, sveppir, svartar ólífur, artisætur, oregano, evo', description_en: '', price: 2790, category: 'Pizzur', sort_order: 5 },
  { id: 'np-6', restaurant_id: 'napoli-pizza-rvk', name_is: 'Polpetta', name_en: 'Polpetta', description_is: 'San Marzano tómatsósa, ferskur mozzarella, fersk basilíka, ítalskar kjötbollur, oregano, parmesan sneiðar, evo', description_en: '', price: 2690, category: 'Pizzur', sort_order: 6 },
  { id: 'np-7', restaurant_id: 'napoli-pizza-rvk', name_is: 'Parma', name_en: 'Parma', description_is: 'San Marzano tómatsósa, ferskur mozzarella, fersk basilíka, klettasalat, parmaskinka, parmesan sneiðar, evo', description_en: '', price: 2890, category: 'Pizzur', sort_order: 7 },
  { id: 'np-8', restaurant_id: 'napoli-pizza-rvk', name_is: 'Ortolana/Vegan', name_en: 'Vegetarian', description_is: 'San Marzano tómatsósa, ferskur mozzarella, fersk basilíka, grilluð paprika, grillaður kúrbítur, svartar ólífur, artisætur, oregano', description_en: '', price: 2690, category: 'Pizzur', sort_order: 8 },
  { id: 'np-9', restaurant_id: 'napoli-pizza-rvk', name_is: 'Quattro Formagi', name_en: 'Four Cheese', description_is: 'Ricotta, ferskur mozzarella, fersk basilíka, bláostur, parmesan sneiðar, evo, rifsberjasulta til hliðar', description_en: '', price: 2690, category: 'Pizzur', sort_order: 9 },
  { id: 'np-10', restaurant_id: 'napoli-pizza-rvk', name_is: 'Aglio e Olio', name_en: 'Garlic Pizza', description_is: 'Ferskur mozzarella, fersk basilíka, ferskur hvítlaukur, hvítlauksolía', description_en: '', price: 2090, category: 'Pizzur', sort_order: 10 },
  { id: 'np-11', restaurant_id: 'napoli-pizza-rvk', name_is: 'Calzone', name_en: 'Calzone', description_is: 'San Marzano tómatsósa, ricotta, fersk basilíka, ferskur mozzarella, skinka, pepperoni, evo', description_en: '', price: 2490, category: 'Pizzur', sort_order: 11 },
  // ─── Glósteinn (Scraped 2026-03) ───
  { id: 'gs-1', restaurant_id: 'glosteinnn', name_is: 'Melbær', name_en: 'Melbær', description_is: 'Glósteinssósa, Ostur', description_en: '', price: 2490, category: 'Pizzur', sort_order: 1 },
  { id: 'gs-2', restaurant_id: 'glosteinnn', name_is: 'Mýrarás', name_en: 'Mýrarás', description_is: 'Glósteinssósa, Ferskur Mozzarella, Basil, Ólífuolía', description_en: '', price: 2890, category: 'Pizzur', sort_order: 2 },
  { id: 'gs-3', restaurant_id: 'glosteinnn', name_is: 'Hraunbær', name_en: 'Hraunbær', description_is: 'Auka Ostur, Hvítlauksolía, Sjávarsalt', description_en: '', price: 2690, category: 'Pizzur', sort_order: 3 },
  { id: 'gs-4', restaurant_id: 'glosteinnn', name_is: 'Fylkisvegur', name_en: 'Fylkisvegur', description_is: 'Glósteinssósa, Ostur, Pepperoni', description_en: '', price: 2950, category: 'Pizzur', sort_order: 4 },
  { id: 'gs-5', restaurant_id: 'glosteinnn', name_is: 'Heiðarás', name_en: 'Heiðarás', description_is: 'Glósteinssósa, Ostur, Skinka, Ananas', description_en: '', price: 3290, category: 'Pizzur', sort_order: 5 },
  { id: 'gs-6', restaurant_id: 'glosteinnn', name_is: 'Seiðakvísl', name_en: 'Seiðakvísl', description_is: 'Glósteinssósa, Ostur, Pepperoni, Sveppir', description_en: '', price: 3290, category: 'Pizzur', sort_order: 6 },
  { id: 'gs-7', restaurant_id: 'glosteinnn', name_is: 'Þingvað', name_en: 'Þingvað', description_is: 'Glósteinssósa, Ostur, Pepperoni, Nautahakk, Rjómaostur', description_en: '', price: 3590, category: 'Pizzur', sort_order: 7 },
  { id: 'gs-8', restaurant_id: 'glosteinnn', name_is: 'Bröndukvísl', name_en: 'Bröndukvísl', description_is: 'Glósteinssósa, Ostur, Pepperoni, Kjúklingur, Rjómaostur, Rauðlaukur, Döðlur, Mulið Tortilla Snakk', description_en: '', price: 3690, category: 'Pizzur', sort_order: 8 },
  { id: 'gs-9', restaurant_id: 'glosteinnn', name_is: 'Glæsibær', name_en: 'Glæsibær', description_is: 'Glósteinssósa, Ostur, Hvítlauksmarineraðar Tígrisrækjur, Klettasalat, Parmesan, Pistasíur, Hvítlauksolía, Sjávarsalt', description_en: '', price: 3790, category: 'Pizzur', sort_order: 9 },
  { id: 'gs-10', restaurant_id: 'glosteinnn', name_is: 'Reykás', name_en: 'Reykás', description_is: 'Glósteinssósa, Ostur, Hráskinka, Klettasalat, Parmesan', description_en: '', price: 3790, category: 'Pizzur', sort_order: 10 },
  // ─── Pizza Popolare (Scraped 2026-03) ───
  { id: 'pp-1', restaurant_id: 'pizza-popolare', name_is: 'Popolare Piccante', name_en: 'Popolare Piccante', description_is: 'San Marzano, Mozzarella, Salami Piccante, Nduja, Olives, Chili flakes', description_en: '', price: 3990, category: 'Pizzur', sort_order: 1 },
  { id: 'pp-2', restaurant_id: 'pizza-popolare', name_is: 'Diavola', name_en: 'Diavola', description_is: 'San Marzano Tomato, Mozzarella, Spicy Salami, Chili', description_en: '', price: 3890, category: 'Pizzur', sort_order: 2 },
  { id: 'pp-3', restaurant_id: 'pizza-popolare', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano Tomato, Mozzarella, Basil', description_en: '', price: 3190, category: 'Pizzur', sort_order: 3 },
  { id: 'pp-4', restaurant_id: 'pizza-popolare', name_is: 'Vegetarian', name_en: 'Vegetarian', description_is: 'San Marzano tómatar, Mozzarella, Basil, Hvítlaukur, Ristaðar Ratte kartöflur, Ætiþistlar, Grillaðar paprikur, Kirsuberjatómatar', description_en: '', price: 3690, category: 'Pizzur', sort_order: 4 },
  { id: 'pp-5', restaurant_id: 'pizza-popolare', name_is: 'Calzone', name_en: 'Calzone', description_is: 'San Marzano Tomato, Mozzarella, Cooked Ham, Mushroom', description_en: '', price: 3890, category: 'Pizzur', sort_order: 5 },
  { id: 'pp-6', restaurant_id: 'pizza-popolare', name_is: 'Napoli Popolare', name_en: 'Napoli Popolare', description_is: 'San Marzano Tomato, Cherry Tomato, Garlic, Anchovies, Capers, Basil, Oregano', description_en: '', price: 3690, category: 'Pizzur', sort_order: 6 },
  { id: 'pp-7', restaurant_id: 'pizza-popolare', name_is: 'Marinara', name_en: 'Marinara', description_is: 'San Marzano Tomato, Garlic, Oregano, Basil', description_en: '', price: 3090, category: 'Pizzur', sort_order: 7 },
  { id: 'pp-8', restaurant_id: 'pizza-popolare', name_is: 'Regina', name_en: 'Regina', description_is: 'San Marzano Tomato, Mozzarella, Cooked Ham, Mushroom', description_en: '', price: 3790, category: 'Pizzur', sort_order: 8 },
  { id: 'pp-9', restaurant_id: 'pizza-popolare', name_is: 'Crispy Guanciale', name_en: 'Crispy Guanciale', description_is: 'San Marzano Tomato, Mozzarella, Crispy Guanciale, Chili Flakes', description_en: '', price: 4090, category: 'Pizzur', sort_order: 9 },
  { id: 'pp-10', restaurant_id: 'pizza-popolare', name_is: 'Parmigiana', name_en: 'Parmigiana', description_is: 'Eggplant Parmigiano Ragù, Basil, Ristaðir kirsuberjatómatar, Mozzarella', description_en: '', price: 3890, category: 'Pizzur', sort_order: 10 },

  // ─── Antons Mamma Mia (Scraped 2026-03) ───
  { id: 'am-1', restaurant_id: 'antons-mamma-mia', name_is: 'Pizza Grande', name_en: 'Pizza Grande', description_is: 'Nautahakk, skinka, pepperoni, beikonkurl', description_en: 'Ground beef, ham, pepperoni, bacon bits', price: 3190, category: 'Pizzur', sort_order: 1 },
  { id: 'am-2', restaurant_id: 'antons-mamma-mia', name_is: 'Pizza Falk', name_en: 'Pizza Falk', description_is: 'Nautahakk, pepperoni, ananas, jalapeno, beikonkurl, svartur pipar', description_en: 'Ground beef, pepperoni, pineapple, jalapeno, bacon bits, black pepper', price: 3490, category: 'Pizzur', sort_order: 2 },
  { id: 'am-3', restaurant_id: 'antons-mamma-mia', name_is: 'Pizza Volcano (Sterk)', name_en: 'Pizza Volcano (Spicy)', description_is: 'Laukur, paprika, pepperoni, nautahakk, jalapeno, cayennepipar, svartar ólífur, chilibitaflögur. Srirachasósa fylgir með.', description_en: 'Onion, bell pepper, pepperoni, ground beef, jalapeno, cayenne pepper, black olives, chili flakes. Served with Sriracha sauce.', price: 3490, category: 'Pizzur', sort_order: 3 },
  { id: 'am-4', restaurant_id: 'antons-mamma-mia', name_is: 'Pizza Ala Humar (Premium)', name_en: 'Lobster Pizza (Premium)', description_is: 'Hvítlaukssmjör, rjómaostur, hvítlaukur, tómatar, humar. Toppað með klettasalati og ferskum parmesan.', description_en: 'Garlic butter, cream cheese, garlic, tomatoes, langoustine. Topped with arugula and fresh parmesan.', price: 3890, category: 'Pizzur', sort_order: 4 },

  // ─── Fernando's Keflavík (Scraped 2026-03) ───
  { id: 'fe-1', restaurant_id: 'fernandos-keflavik', name_is: 'Lava Pizza', name_en: 'Lava Pizza', description_is: 'Tómatsósa, ostur, pepperoni, jalapeno, chilikrydd (Sterk)', description_en: 'Tomato sauce, cheese, pepperoni, jalapeno, chili spice (Spicy)', price: 3390, category: 'Pizzur', sort_order: 1 },
  { id: 'fe-2', restaurant_id: 'fernandos-keflavik', name_is: 'Humarpizza', name_en: 'Langoustine Pizza', description_is: 'Tómatsósa, ostur, íslenskur humar, hvítlaukur, rjómaostur', description_en: 'Tomato sauce, cheese, Icelandic langoustine, garlic, cream cheese', price: 3990, category: 'Pizzur', sort_order: 2 },
  { id: 'fe-3', restaurant_id: 'fernandos-keflavik', name_is: 'Calzone Fernando', name_en: 'Fernando Calzone', description_is: 'Innbökuð pizza með skinku, sveppum og rjómaosti', description_en: 'Folded pizza with ham, mushrooms and cream cheese', price: 3490, category: 'Pizzur', sort_order: 3 },

  // ─── Pizza Bræður Mosfellsbær (Scraped 2026-03) ───
  { id: 'pb-1', restaurant_id: 'pizza-braedur-mosfellsbaer', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, ostur', description_en: 'Tomato sauce, cheese', price: 2790, category: 'Pizzur', sort_order: 1 },
  { id: 'pb-2', restaurant_id: 'pizza-braedur-mosfellsbaer', name_is: 'Pepperoni', name_en: 'Pepperoni', description_is: 'Tómatsósa, ostur, vel af pepperóní', description_en: 'Tomato sauce, cheese, plenty of pepperoni', price: 2990, category: 'Pizzur', sort_order: 2 },
  { id: 'pb-3', restaurant_id: 'pizza-braedur-mosfellsbaer', name_is: 'Bræðrapizza', name_en: 'Brothers Special', description_is: 'Tómatsósa, ostur, pepperóní, beikon, rjómaostur', description_en: 'Tomato sauce, cheese, pepperoni, bacon, cream cheese', price: 3490, category: 'Pizzur', sort_order: 3 },

  // ─── Italiano Pizzeria (Scraped 2026-03) ───
  { id: 'ik-1', restaurant_id: 'italiano-kopavogur', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, fersk basilíka', description_en: 'Tomato sauce, mozzarella, fresh basil', price: 2890, category: 'Pizzur', sort_order: 1 },
  { id: 'ik-2', restaurant_id: 'italiano-kopavogur', name_is: 'Vegan Buffalo', name_en: 'Vegan Buffalo', description_is: 'Vegan ostur, vegan buffalo kjúklingur, rauðlaukur, ferskt kóríander, ranch sósa', description_en: 'Vegan cheese, vegan buffalo chicken, red onion, fresh cilantro, ranch sauce', price: 3590, category: 'Pizzur', sort_order: 2 },
  { id: 'ik-3', restaurant_id: 'italiano-kopavogur', name_is: 'Quattro Formaggi', name_en: 'Four Cheese', description_is: 'Tómatsósa, mozzarella, gorgonzola, parmesan, fetaostur', description_en: 'Tomato sauce, mozzarella, gorgonzola, parmesan, feta cheese', price: 3490, category: 'Pizzur', sort_order: 3 },

  // ─── Pizzafjörður (Scraped 2026-07, verð = 12") ───
  { id: 'pf-1', restaurant_id: 'pizzafjordur', name_is: 'Pizza Margarita', name_en: 'Pizza Margarita', description_is: 'Pizzusósa, ostur, óreganó', description_en: 'Pizza sauce, cheese, oregano', price: 1750, price_large: 2000, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 1 },
  { id: 'pf-2', restaurant_id: 'pizzafjordur', name_is: 'Pepperoni Special', name_en: 'Pepperoni Special', description_is: 'Pepperóní, ananas, laukur', description_en: 'Pepperoni, pineapple, onions', price: 2550, price_large: 3300, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 2 },
  { id: 'pf-3', restaurant_id: 'pizzafjordur', name_is: 'Ostapizza Prinsessunar', name_en: 'Princess Cheese Pizza', description_is: 'Ostur, rjómaostur, parmesan, camembert, mexíkóostur', description_en: 'Cheese, cream cheese, parmesan, camembert, mexican cheese', price: 3200, price_large: 3700, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 3 },
  { id: 'pf-4', restaurant_id: 'pizzafjordur', name_is: 'Pizza Combat', name_en: 'Pizza Combat', description_is: 'Skinka, ananas, laukur, sveppir, paprika, beikon', description_en: 'Ham, pineapple, onions, mushroom, bell pepper, bacon', price: 3500, price_large: 4300, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 4 },
  { id: 'pf-5', restaurant_id: 'pizzafjordur', name_is: 'Pizza Napoli', name_en: 'Pizza Napoli', description_is: 'Skinka, sveppir, paprika, hvítlaukur', description_en: 'Ham, mushroom, bell pepper, garlic', price: 2950, price_large: 3500, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 5 },
  { id: 'pf-6', restaurant_id: 'pizzafjordur', name_is: 'Veislan', name_en: 'The Feast', description_is: 'Skinka, pepperóní, sveppir, svartar ólífur, hvítlaukur, grænn pipar, parmesan', description_en: 'Ham, pepperoni, mushroom, black olives, garlic, green peppercorn, parmesan', price: 3450, price_large: 4350, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 6 },
  { id: 'pf-7', restaurant_id: 'pizzafjordur', name_is: 'Víkin', name_en: 'Víkin', description_is: 'Skinka, ananas, sveppir', description_en: 'Ham, pineapple, mushroom', price: 2750, price_large: 3400, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 7 },
  { id: 'pf-8', restaurant_id: 'pizzafjordur', name_is: 'Skarðið', name_en: 'Skarðið', description_is: 'Mest selda pizzan — pepperóní, sveppir, beikon, rjómaostur', description_en: 'Best seller — pepperoni, mushroom, bacon, cream cheese', price: 3100, price_large: 3850, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 8 },
  { id: 'pf-9', restaurant_id: 'pizzafjordur', name_is: 'Pizza hafsins', name_en: 'Pizza of the Sea', description_is: 'Túnfiskur, rækjur, hvítlaukur, óreganó, parmesan', description_en: 'Tuna, shrimp, garlic, oregano, parmesan', price: 2950, price_large: 3550, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 9 },
  { id: 'pf-10', restaurant_id: 'pizzafjordur', name_is: 'Sveitin', name_en: 'The Countryside', description_is: 'Nautahakk, kjúklingur, beikon', description_en: 'Beef, chicken, bacon', price: 2800, price_large: 3600, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 10 },
  { id: 'pf-11', restaurant_id: 'pizzafjordur', name_is: 'Basic', name_en: 'Basic', description_is: 'Skinka, pepperóní, rjómaostur', description_en: 'Ham, pepperoni, cream cheese', price: 2750, price_large: 3400, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 11 },
  { id: 'pf-12', restaurant_id: 'pizzafjordur', name_is: 'BBQ Pizza', name_en: 'BBQ Pizza', description_is: 'BBQ sósa, ostur, nautahakk, beikon, laukur', description_en: 'BBQ sauce, cheese, beef, bacon, onion', price: 2750, price_large: 3400, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 12 },
  { id: 'pf-13', restaurant_id: 'pizzafjordur', name_is: 'Nýpan Special', name_en: 'Nýpan Special', description_is: 'Pepperóní, jalapeno, rjómaostur, ananas, svartar ólífur, hvítlaukur, óreganó, sveppir', description_en: 'Pepperoni, jalapeno, cream cheese, pineapple, black olives, garlic, oregano, mushroom', price: 3500, price_large: 4750, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 13 },
  { id: 'pf-14', restaurant_id: 'pizzafjordur', name_is: 'Nýpan Classic', name_en: 'Nýpan Classic', description_is: 'Skinka, pepperóní, beikon, paprika, laukur, sveppir, rjómaostur, gráðostur', description_en: 'Ham, pepperoni, bacon, bell pepper, onions, mushroom, cream cheese, blue cheese', price: 3750, price_large: 4800, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 14 },
  { id: 'pf-15', restaurant_id: 'pizzafjordur', name_is: 'Pollo', name_en: 'Pollo', description_is: 'Kjúklingur, tómatar, rauðlaukur', description_en: 'Chicken, tomato, red onion', price: 2550, price_large: 3300, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 15 },
  { id: 'pf-16', restaurant_id: 'pizzafjordur', name_is: 'Meistarinn', name_en: 'The Master', description_is: 'Pepperóní, skinka, beikon, ananas, jalapeno, hvítlaukur, svartur pipar, laukur, sveppir', description_en: 'Pepperoni, ham, bacon, pineapple, jalapeno, garlic, black pepper, onion, mushroom', price: 3750, price_large: 4800, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 16 },
  { id: 'pf-17', restaurant_id: 'pizzafjordur', name_is: 'Kjúklinga loco', name_en: 'Chicken Loco', description_is: 'Kjúklingur, salthnetur, sveppir', description_en: 'Chicken, salted nuts, mushroom', price: 2650, price_large: 3250, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 17 },
  { id: 'pf-18', restaurant_id: 'pizzafjordur', name_is: 'Fernan', name_en: 'Fernan', description_is: 'Skinka, paprika, sveppir, ananas', description_en: 'Ham, bell pepper, mushroom, pineapple', price: 2950, price_large: 3750, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 18 },
  { id: 'pf-19', restaurant_id: 'pizzafjordur', name_is: 'Húsdýragarðurinn', name_en: 'The Petting Zoo', description_is: 'Nautahakk, beikon, egg, svartur pipar', description_en: 'Ground beef, bacon, egg, black pepper', price: 2650, price_large: 3350, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 19 },
  { id: 'pf-20', restaurant_id: 'pizzafjordur', name_is: 'Daredevil', name_en: 'Daredevil', description_is: 'Pepperóní, chili, jalapeno, svartur pipar', description_en: 'Pepperoni, chili, jalapeno, black pepper', price: 2500, price_large: 3050, size_small_label: '12"', size_large_label: '16"', category: 'Pizzur', sort_order: 20 },
  { id: 'pf-b1', restaurant_id: 'pizzafjordur', name_is: 'Mexíkó Brauð', name_en: 'Mexico Bread', description_is: 'Ostur, hvítlaukur, rjómaostur, mulið doritos', description_en: 'Cheese, garlic, cream cheese, crushed doritos', price: 2350, price_large: 2850, size_small_label: '12"', size_large_label: '16"', category: 'Brauð', sort_order: 21 },
  { id: 'pf-b2', restaurant_id: 'pizzafjordur', name_is: 'Hvítlauksbrauð', name_en: 'Garlic Bread', description_is: '', description_en: '', price: 1750, price_large: 2000, size_small_label: '12"', size_large_label: '16"', category: 'Brauð', sort_order: 22 },
  { id: 'pf-b3', restaurant_id: 'pizzafjordur', name_is: 'Brauðstangir', name_en: 'Breadsticks', description_is: '', description_en: '', price: 750, price_large: 1150, size_small_label: '12"', size_large_label: '16"', category: 'Brauð', sort_order: 23 },

  // ─── Pizza Kofinn Húsavík (Scraped 2026-03) ───
  { id: 'pk-1', restaurant_id: 'pizza-kofinn', name_is: 'Kofapizzan', name_en: 'Cabin Pizza', description_is: 'Tómatsósa, mozzarella, nautahakk, skinka, pepperóní', description_en: 'Tomato sauce, mozzarella, ground beef, ham, pepperoni', price: 3690, category: 'Pizzur', sort_order: 1 },
  { id: 'pk-2', restaurant_id: 'pizza-kofinn', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 3390, category: 'Pizzur', sort_order: 2 },
  { id: 'pk-3', restaurant_id: 'pizza-kofinn', name_is: 'Grænmetis', name_en: 'Vegetarian', description_is: 'Tómatsósa, mozzarella, sveppir, laukur, paprika, ólífur', description_en: 'Tomato sauce, mozzarella, mushrooms, onion, bell pepper, olives', price: 3490, category: 'Pizzur', sort_order: 3 },

  // ─── Askur Pizzeria Egilsstaðir (Scraped 2026-03) ───
  { id: 'ap-1', restaurant_id: 'askur-pizzeria', name_is: 'Mér er drull', name_en: 'Mér er drull', description_is: 'Sósa, ostur, tómatar, hvítlaukur, basilíkukrydd, ferskur mozzarella og fersk basilíka', description_en: 'Sauce, cheese, tomatoes, garlic, basil seasoning, fresh mozzarella and fresh basil', price: 3750, category: 'Pizzur', sort_order: 1 },
  { id: 'ap-2', restaurant_id: 'askur-pizzeria', name_is: 'Fæ Aldrei Nóg Af Þér', name_en: 'Fæ Aldrei Nóg Af Þér', description_is: 'Sósa, veganostur, hvítlaukur, rauðlaukur, ananas, sveppir, vegan hakk og grænn pipar (Vegan)', description_en: 'Sauce, vegan cheese, garlic, red onion, pineapple, mushrooms, vegan mince and green pepper (Vegan)', price: 3750, category: 'Pizzur', sort_order: 2 },
  { id: 'ap-3', restaurant_id: 'askur-pizzeria', name_is: 'Vertu þú sjálfur', name_en: 'Vertu þú sjálfur', description_is: 'Sósa, veganostur, sveppir, döðlur, salthnetur, klettasalat og Bera hot sauce (Vegan)', description_en: 'Sauce, vegan cheese, mushrooms, dates, salted peanuts, arugula and Bera hot sauce (Vegan)', price: 3750, category: 'Pizzur', sort_order: 3 },
  { id: 'ap-4', restaurant_id: 'askur-pizzeria', name_is: 'Með allt á hreinu', name_en: 'The Works', description_is: 'Sósa, ostur, hreindýrahakk, sultaður rauðlaukur, Gellir ferskostur og furuhnetur', description_en: 'Sauce, cheese, minced reindeer, pickled red onion, Gellir cream cheese and pine nuts', price: 5550, category: 'Pizzur', sort_order: 4 },
  { id: 'ap-5', restaurant_id: 'askur-pizzeria', name_is: 'Orginal', name_en: 'Original', description_is: 'Sósa, ostur, beikon, döðlur og piparrjómaostur', description_en: 'Sauce, cheese, bacon, dates and pepper cream cheese', price: 3550, category: 'Pizzur', sort_order: 5 },
  { id: 'ap-6', restaurant_id: 'askur-pizzeria', name_is: 'Fallegi smiðurinn', name_en: 'Handsome Carpenter', description_is: 'Sósa, ostur, pepperoni, piparostur, rauðlaukur og sveppir', description_en: 'Sauce, cheese, pepperoni, pepper cheese, red onion and mushrooms', price: 3650, category: 'Pizzur', sort_order: 6 },
  { id: 'ap-7', restaurant_id: 'askur-pizzeria', name_is: 'Fimm á richter', name_en: 'Fimm á richter', description_is: 'Sósa, ostur, vínber, beikon, camembert ostur, valhnetur og chili hunang', description_en: 'Sauce, cheese, grapes, bacon, camembert, walnuts and chili honey', price: 3750, category: 'Pizzur', sort_order: 7 },
  { id: 'ap-8', restaurant_id: 'askur-pizzeria', name_is: 'Vor í Vaglaskógi', name_en: 'Vor í Vaglaskógi', description_is: 'Sósa, ostur, sveppir, rauðlaukur, paprika, svartar ólífur og óreganó', description_en: 'Sauce, cheese, mushrooms, red onion, bell pepper, black olives and oregano', price: 3750, category: 'Pizzur', sort_order: 8 },
  { id: 'ap-9', restaurant_id: 'askur-pizzeria', name_is: 'Stella í Orlofi', name_en: 'Stella í Orlofi', description_is: 'BBQ sósa, ostur, hakk, beikon, rauðlaukur og kjúklingur', description_en: 'BBQ sauce, cheese, ground beef, bacon, red onion and chicken', price: 4000, category: 'Pizzur', sort_order: 9 },
  { id: 'ap-10', restaurant_id: 'askur-pizzeria', name_is: 'Í átt að tunglinu', name_en: 'To the Moon', description_is: 'Calzone: sósa, ostur, skinka, sveppir og svartur pipar', description_en: 'Calzone: sauce, cheese, ham, mushrooms and black pepper', price: 3550, category: 'Pizzur', sort_order: 10 },
  { id: 'ap-11', restaurant_id: 'askur-pizzeria', name_is: 'Í Bláum Skugga', name_en: 'Í Bláum Skugga', description_is: 'Sósa, ostur, gráðostur, cheddar ostur, piparostur og parmesan', description_en: 'Sauce, cheese, blue cheese, cheddar, pepper cheese and parmesan', price: 3750, category: 'Pizzur', sort_order: 11 },
  { id: 'ap-12', restaurant_id: 'askur-pizzeria', name_is: 'Esjan', name_en: 'Esjan', description_is: 'Sósa, ostur, skinka og ananas', description_en: 'Sauce, cheese, ham and pineapple', price: 3300, category: 'Pizzur', sort_order: 12 },
  { id: 'ap-13', restaurant_id: 'askur-pizzeria', name_is: 'Vöðvastæltur', name_en: 'Muscle Man', description_is: 'Sósa, ostur, pepperoni, skinka, beikon og rjómaostur', description_en: 'Sauce, cheese, pepperoni, ham, bacon and cream cheese', price: 3900, category: 'Pizzur', sort_order: 13 },
  { id: 'ap-14', restaurant_id: 'askur-pizzeria', name_is: 'B.O.B.A', name_en: 'B.O.B.A', description_is: 'Ostur, pepperoni, sveppir, ólífur, mozzarella, habanero, græn piparkorn og döðlur', description_en: 'Cheese, pepperoni, mushrooms, olives, mozzarella, habanero, green peppercorns and dates', price: 4100, category: 'Pizzur', sort_order: 14 },
  { id: 'ap-15', restaurant_id: 'askur-pizzeria', name_is: 'Járnkallinn', name_en: 'Járnkallinn', description_is: 'Sósa, ostur, nautahakk, pepperoni, sveppir, Gellir ferskostur, hvítlaukur og rauðlaukur', description_en: 'Sauce, cheese, ground beef, pepperoni, mushrooms, Gellir cream cheese, garlic and red onion', price: 4100, category: 'Pizzur', sort_order: 15 },
  { id: 'ap-16', restaurant_id: 'askur-pizzeria', name_is: 'Hjálpaðu mér upp', name_en: 'Hjálpaðu mér upp', description_is: 'Sósa, ostur, pepperóní, piparostur, jalapeno og chiliflögur (Sterk)', description_en: 'Sauce, cheese, pepperoni, pepper cheese, jalapeno and chili flakes (Spicy)', price: 3750, category: 'Pizzur', sort_order: 16 },
  { id: 'ap-17', restaurant_id: 'askur-pizzeria', name_is: 'Enginn mórall', name_en: 'Enginn mórall', description_is: 'Hvítlauksmauk, rjómaostur, ostur, sveppir, rauðlaukur, piparostur og svartur pipar', description_en: 'Garlic paste, cream cheese, cheese, mushrooms, red onion, pepper cheese and black pepper', price: 3750, category: 'Pizzur', sort_order: 17 },
  { id: 'ap-18', restaurant_id: 'askur-pizzeria', name_is: 'Pamela', name_en: 'Pamela', description_is: 'Hvítlauksmauk, ostur, parmaskinka, klettasalat og parmesan', description_en: 'Garlic paste, cheese, parma ham, arugula and parmesan', price: 3950, category: 'Pizzur', sort_order: 18 },
  { id: 'ap-19', restaurant_id: 'askur-pizzeria', name_is: 'Margaríta', name_en: 'Margherita', description_is: 'Sósa, ostur, mozzarella og fersk basilíka', description_en: 'Tomato sauce, cheese, mozzarella and fresh basil', price: 2750, category: 'Pizzur', sort_order: 19 },

  // ─── Stykkið Pizzeria Stykkishólmur (Scraped 2026-03) ───
  { id: 'sp-1', restaurant_id: 'stykkid-pizzeria', name_is: 'Snæfellspizza', name_en: 'Snæfellsnes Special', description_is: 'Tómatsósa, mozzarella, reyktur lax, rjómaostur, klettasalat, dill', description_en: 'Tomato sauce, mozzarella, smoked salmon, cream cheese, arugula, dill', price: 3890, category: 'Pizzur', sort_order: 1 },
  { id: 'sp-2', restaurant_id: 'stykkid-pizzeria', name_is: 'Aðalgatan', name_en: 'Main Street', description_is: 'Tómatsósa, mozzarella, pepperóní, sveppir, paprika', description_en: 'Tomato sauce, mozzarella, pepperoni, mushrooms, bell pepper', price: 3590, category: 'Pizzur', sort_order: 2 },
  { id: 'sp-3', restaurant_id: 'stykkid-pizzeria', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2990, category: 'Pizzur', sort_order: 3 },

  // ─── Íshúsið Pizzeria Höfn (Scraped 2026-03) ───
  { id: 'ip-1', restaurant_id: 'ishusid-pizzeria-hofn', name_is: 'Lobster Classic', name_en: 'Lobster Classic', description_is: 'Sósa, ostur, staðbundinn humar, paprika, hvítlaukur, klettasalat, parmesan', description_en: 'Sauce, cheese, local langoustine, bell peppers, garlic, arugula, parmesan', price: 4290, category: 'Pizzur', sort_order: 1 },
  { id: 'ip-2', restaurant_id: 'ishusid-pizzeria-hofn', name_is: 'Atli Special', name_en: 'Atli Special', description_is: 'Hvít sósa, ostur, kjúklingur, sveppir, beikon, sterk majónessósa', description_en: 'White sauce, cheese, chicken, mushrooms, bacon, spicy mayo', price: 3690, category: 'Pizzur', sort_order: 2 },
  { id: 'ip-3', restaurant_id: 'ishusid-pizzeria-hofn', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, ostur, óreganó', description_en: 'Tomato sauce, cheese, oregano', price: 2890, category: 'Pizzur', sort_order: 3 },

  // ─── Flatey Pizza Selfoss (Scraped 2026-03) ───
  { id: 'fs-1', restaurant_id: 'flatey-pizza-selfoss', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano, fior di latte, basilíka, ólífuolía', description_en: 'San Marzano, fior di latte, basil, olive oil', price: 3190, category: 'Pizzur', sort_order: 1 },
  { id: 'fs-2', restaurant_id: 'flatey-pizza-selfoss', name_is: 'Padrino', name_en: 'Padrino', description_is: 'San Marzano, mozzarella, pepperóní, súr chili, hunang', description_en: 'San Marzano, mozzarella, pepperoni, pickled chili, honey', price: 3790, category: 'Pizzur', sort_order: 2 },
  { id: 'fs-3', restaurant_id: 'flatey-pizza-selfoss', name_is: 'Tartufo', name_en: 'Tartufo', description_is: 'Mozzarella, sveppir, ricotta, kartöflur, trufflolía', description_en: 'Mozzarella, mushrooms, ricotta, potatoes, truffle oil', price: 4090, category: 'Pizzur', sort_order: 3 },

  // ─── Kaffi Krús Selfoss (Scraped 2026-03) ───
  { id: 'kk-1', restaurant_id: 'kaffi-krus', name_is: 'Verona', name_en: 'Verona', description_is: 'Sósa, ostur, pepperoni, beikon, sveppir, rjómaostur og oregano', description_en: 'Sauce, cheese, pepperoni, bacon, mushrooms, cream cheese and oregano', price: 3690, category: 'Pizzur', sort_order: 1 },
  { id: 'kk-2', restaurant_id: 'kaffi-krus', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Sósa, ostur og oregano', description_en: 'Sauce, cheese and oregano', price: 2890, category: 'Pizzur', sort_order: 2 },
  { id: 'kk-3', restaurant_id: 'kaffi-krus', name_is: 'Sérréttapizza', name_en: 'House Special', description_is: 'Sósa, ostur, skinka, nautahakk, laukur, fersk paprika', description_en: 'Sauce, cheese, ham, ground beef, onion, fresh bell pepper', price: 3590, category: 'Pizzur', sort_order: 3 },

  // ─── Pítsugerðin Vestmannaeyjar (Scraped 2026-03) ───
  { id: 'pg-1', restaurant_id: 'pitsugerdin', name_is: 'Súrdeigs Margherita', name_en: 'Sourdough Margherita', description_is: 'San Marzano, ferskur mozzarella, basilíka', description_en: 'San Marzano, fresh mozzarella, basil', price: 3190, category: 'Pizzur', sort_order: 1 },
  { id: 'pg-2', restaurant_id: 'pitsugerdin', name_is: 'Gorgonzola Special', name_en: 'Gorgonzola Special', description_is: 'Viðarelduð, mozzarella, gorgonzola, hráskinka, fíkjur', description_en: 'Wood-fired, mozzarella, gorgonzola, prosciutto, figs', price: 3890, category: 'Pizzur', sort_order: 2 },
  { id: 'pg-3', restaurant_id: 'pitsugerdin', name_is: 'Piccante', name_en: 'Spicy Sourdough', description_is: 'San Marzano, mozzarella, sterk salsiccia, chili', description_en: 'San Marzano, mozzarella, spicy salsiccia, chili', price: 3590, category: 'Pizzur', sort_order: 3 },

  // ─── Pizza 67 Vestmannaeyjar (Scraped 2026-03) ───
  { id: 'p7-1', restaurant_id: 'pizza-67-vestmannaeyjar', name_is: 'Sjóarinn', name_en: 'The Sailor', description_is: 'Tómatsósa, ostur, rækjur, túnfiskur, laukur', description_en: 'Tomato sauce, cheese, shrimp, tuna, onion', price: 3490, category: 'Pizzur', sort_order: 1 },
  { id: 'p7-2', restaurant_id: 'pizza-67-vestmannaeyjar', name_is: 'Eyjasérréttur', name_en: 'Islands Special', description_is: 'Tómatsósa, ostur, pepperóní, sveppir, paprika', description_en: 'Tomato sauce, cheese, pepperoni, mushrooms, bell pepper', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'p7-3', restaurant_id: 'pizza-67-vestmannaeyjar', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, ostur, oreganó', description_en: 'Tomato sauce, cheese, oregano', price: 2790, category: 'Pizzur', sort_order: 3 },

  // ─── Hamraborg Ísafjörður (Scraped 2026-03) ───
  { id: 'hb-1', restaurant_id: 'hamraborg-isafjordur', name_is: 'Hamraborgar Special', name_en: 'Hamraborg Special', description_is: 'Sósa, ostur, hakk, laukur, gráðostur, bernaisesósa', description_en: 'Sauce, cheese, ground beef, onion, blue cheese, bernaise sauce', price: 3890, category: 'Pizzur', sort_order: 1 },
  { id: 'hb-2', restaurant_id: 'hamraborg-isafjordur', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Sósa, ostur, pepperóní', description_en: 'Sauce, cheese, pepperoni', price: 3190, category: 'Pizzur', sort_order: 2 },
  { id: 'hb-3', restaurant_id: 'hamraborg-isafjordur', name_is: 'Margarita', name_en: 'Margarita', description_is: 'Sósa, ostur og oreganó', description_en: 'Sauce, cheese and oregano', price: 2890, category: 'Pizzur', sort_order: 3 },

  // ─── Pizzan Hafnarfjörður (Scraped 2026-03) ───
  { id: 'ph-1', restaurant_id: 'pizzan-hafnarfjordur', name_is: 'Pizzan Deluxe', name_en: 'Pizzan Deluxe', description_is: 'Pepperóní, rjómaostur, piparostur, beikon og svartur pipar', description_en: 'Pepperoni, cream cheese, pepper cheese, bacon and black pepper', price: 3890, category: 'Pizzur', sort_order: 1 },
  { id: 'ph-2', restaurant_id: 'pizzan-hafnarfjordur', name_is: 'Sweet Bacon', name_en: 'Sweet Bacon', description_is: 'Bacon sulta, pepperóní, jalapeno, hvítlauks aioli og nachos', description_en: 'Bacon jam, pepperoni, jalapeno, garlic aioli and nachos', price: 3990, category: 'Pizzur', sort_order: 2 },
  { id: 'ph-3', restaurant_id: 'pizzan-hafnarfjordur', name_is: '5 Cheese', name_en: '5 Cheese', description_is: 'Stracciatella, ostur, fior de latte, piparostur og parmesan', description_en: 'Stracciatella, cheese, fior de latte, pepper cheese and parmesan', price: 4190, category: 'Pizzur', sort_order: 3 },
  { id: 'ph-4', restaurant_id: 'pizzan-hafnarfjordur', name_is: 'Pretty Pesto', name_en: 'Pretty Pesto', description_is: 'Kjúklingur, stracciatella, döðlur, pestó og chilli flögur', description_en: 'Chicken, stracciatella, dates, pesto and chilli flakes', price: 4090, category: 'Pizzur', sort_order: 4 },

  // ─── Flatey Pizza Garðabær (Scraped 2026-03) ───
  { id: 'fg-1', restaurant_id: 'flatey-pizza-gardabaer', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano, fior di latte, basilíka, ólífuolía', description_en: 'San Marzano, fior di latte, basil, olive oil', price: 3190, category: 'Pizzur', sort_order: 1 },
  { id: 'fg-2', restaurant_id: 'flatey-pizza-gardabaer', name_is: 'Umberto', name_en: 'Umberto', description_is: 'San Marzano, mozzarella, pepperóní, döðlur, mascarpone', description_en: 'San Marzano, mozzarella, pepperoni, dates, mascarpone', price: 3890, category: 'Pizzur', sort_order: 2 },
  { id: 'fg-3', restaurant_id: 'flatey-pizza-gardabaer', name_is: 'Stracciatella', name_en: 'Stracciatella', description_is: 'Gráðaður skinka, mozzarella, stracciatella, basilíkuolía', description_en: 'Cured ham, mozzarella, stracciatella, basil oil', price: 4190, category: 'Pizzur', sort_order: 3 },
  // ─── Pizzasmiðjan Akureyri (Scraped 2026-03) ───
  { id: 'psa-1', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano tómatsósa, ferskur mozzarella, basilíka, ólífuolía', description_en: 'San Marzano tomato sauce, fresh mozzarella, basil, olive oil', price: 2990, category: 'Pizzur', sort_order: 1 },
  { id: 'psa-2', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Pepperoni', name_en: 'Pepperoni', description_is: 'Tómatsósa, ferskur mozzarella, hágæða pepperoni', description_en: 'Tomato sauce, fresh mozzarella, high quality pepperoni', price: 3490, category: 'Pizzur', sort_order: 2 },
  { id: 'psa-3', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Nduja og Hunang', name_en: 'Nduja & Honey', description_is: 'Tómatsósa, mozzarella, nduja, rjómaostur, chili hunang', description_en: 'Tomato sauce, mozzarella, nduja, cream cheese, hot honey', price: 3890, category: 'Pizzur', sort_order: 3 },
  { id: 'psa-4', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Sveppapizza', name_en: 'Mushroom Pizza', description_is: 'Hvítlauksolía, mozzarella, blandaðir trufflusveppir', description_en: 'Garlic oil, mozzarella, mixed truffle mushrooms', price: 3890, category: 'Pizzur', sort_order: 4 },
  { id: 'psa-5', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Hráskinku', name_en: 'Prosciutto', description_is: 'Tómatsósa, mozzarella, hráskinka, klettasalat, parmesan', description_en: 'Tomato sauce, mozzarella, prosciutto, arugula, parmesan', price: 3990, category: 'Pizzur', sort_order: 5 },

  // ─── Íslenska Flatbakan (Scraped 2026-03) ───
  { id: 'ifb-1', restaurant_id: 'islenska-flatbakan', name_is: 'Sú Boltaða', name_en: 'Sú Boltaða', description_is: 'Mozzarellaosta blanda, flatböku sósa, pepperoni, skinka, sveppir, hvítlaukur, ananas, rjómaostur og svartur pipar', description_en: 'Mozzarella blend, flatbread sauce, pepperoni, ham, mushrooms, garlic, pineapple, cream cheese, black pepper', price: 3690, category: 'Pizzur', sort_order: 1 },
  { id: 'ifb-2', restaurant_id: 'islenska-flatbakan', name_is: 'Sú Döðlaða', name_en: 'Sú Döðlaða', description_is: 'Mozzarellaosta blanda, flatböku sósa, pepperoni, döðlur, rauðlaukur, beikon, rjómaostur og svartur pipar', description_en: 'Mozzarella blend, flatbread sauce, pepperoni, dates, red onion, bacon, cream cheese, black pepper', price: 3490, category: 'Pizzur', sort_order: 2 },
  { id: 'ifb-3', restaurant_id: 'islenska-flatbakan', name_is: 'Sú sterka', name_en: 'Sú sterka', description_is: 'Pepperóní, laukur, ferskur chilli, jalapeno, blandaðar ólífur, piparostur og chillikrydd', description_en: 'Pepperoni, onion, fresh chili, jalapeno, mixed olives, pepper cheese, chili spice', price: 3590, category: 'Pizzur', sort_order: 3 },
  { id: 'ifb-4', restaurant_id: 'islenska-flatbakan', name_is: 'Sú Peppaða', name_en: 'Sú Peppaða', description_is: 'Mozzarellaosta blanda, flatböku sósa, pepperoni, rjómaostur', description_en: 'Mozzarella blend, flatbread sauce, pepperoni, cream cheese', price: 3090, category: 'Pizzur', sort_order: 4 },

  // ─── Greifinn Akureyri (Scraped 2026-03) ───
  { id: 'greif-1', restaurant_id: 'greifinn-akureyri', name_is: 'Greifinn', name_en: 'Greifinn', description_is: 'Tómatsósa, ostur, skinka, pepperoni, sveppir, laukur, paprika, rjómaostur', description_en: 'Tomato sauce, cheese, ham, pepperoni, mushrooms, onion, peppers, cream cheese', price: 4290, category: 'Pizzur', sort_order: 1 },
  { id: 'greif-2', restaurant_id: 'greifinn-akureyri', name_is: 'Eldkeilir', name_en: 'Eldkeilir', description_is: 'Tómatsósa, ostur, pepperoni, beikon, grænn pipar, jalapeño, laukur, ferskur chili', description_en: 'Tomato sauce, cheese, pepperoni, bacon, green pepper, jalapeño, onion, fresh chili', price: 4290, category: 'Pizzur', sort_order: 2 },
  { id: 'greif-3', restaurant_id: 'greifinn-akureyri', name_is: 'Skarðshlíð', name_en: 'Skarðshlíð', description_is: 'Tómatsósa, ostur, nautahakk, skinka, beikon, pepparoni, auka ostur', description_en: 'Tomato sauce, cheese, minced beef, ham, bacon, pepperoni, extra cheese', price: 4390, category: 'Pizzur', sort_order: 3 },
  { id: 'greif-4', restaurant_id: 'greifinn-akureyri', name_is: 'Hawaii', name_en: 'Hawaii', description_is: 'Tómatsósa, ostur, skinka, ananas', description_en: 'Tomato sauce, cheese, ham, pineapple', price: 3290, category: 'Pizzur', sort_order: 4 },
  { id: 'greif-5', restaurant_id: 'greifinn-akureyri', name_is: 'Margarita', name_en: 'Margarita', description_is: 'Tómatsósa, mikill ostur', description_en: 'Tomato sauce, lots of cheese', price: 2990, category: 'Pizzur', sort_order: 5 },

  // ─── Castello Pizzeria (Scraped 2026-03) ───
  { id: 'cast-1', restaurant_id: 'castello-hafnarfjordur', name_is: 'Castello Special', name_en: 'Castello Special', description_is: 'Tómatsósa, ostur, pepperoni, sveppir, rjómaostur, auka pepperoni', description_en: 'Tomato sauce, cheese, pepperoni, mushrooms, cream cheese, extra pepperoni', price: 3950, category: 'Pizzur', sort_order: 1 },
  { id: 'cast-2', restaurant_id: 'castello-hafnarfjordur', name_is: 'Riddarinn', name_en: 'The Knight', description_is: 'Tómatsósa, ostur, skinka, nautahakk, laukur, gráðaostur', description_en: 'Tomato sauce, cheese, ham, minced beef, onion, blue cheese', price: 3950, category: 'Pizzur', sort_order: 2 },
  { id: 'cast-3', restaurant_id: 'castello-hafnarfjordur', name_is: 'Kóngurinn', name_en: 'The King', description_is: 'Tómatsósa, ostur, pepperoni, skinka, beikon', description_en: 'Tomato sauce, cheese, pepperoni, ham, bacon', price: 4150, category: 'Pizzur', sort_order: 3 },
  { id: 'cast-4', restaurant_id: 'castello-hafnarfjordur', name_is: 'Drottningin', name_en: 'The Queen', description_is: 'Tómatsósa, ostur, kjúklingur, paprika, laukur, hvítlaukssósa', description_en: 'Tomato sauce, cheese, chicken, peppers, onion, garlic sauce', price: 4150, category: 'Pizzur', sort_order: 4 },
  { id: 'cast-5', restaurant_id: 'castello-hafnarfjordur', name_is: 'Margarita', name_en: 'Margarita', description_is: 'Tómatsósa, hefðbundin eða þunn', description_en: 'Tomato sauce, traditional or thin crust', price: 2850, category: 'Pizzur', sort_order: 5 },
];

export { allRecipes as mockRecipes } from './recipeData';

