/* eslint-disable @typescript-eslint/no-explicit-any */
import { Ad } from '@/types/ad';
import { Restaurant, MenuItem } from '@/types/restaurant';
import { Recipe } from '@/types/recipe';

export const mockAds: Ad[] = [
  {
    id: 'ad-home-hero',
    name: 'Pizzavika 2026',
    client: 'Pizzan ehf.',
    format: '1018x360',
    creatives: {
      '1018x360': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1018&h=360&fit=crop'
    },
    image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1018&h=360&fit=crop',
    target_url: '#',
    status: 'active',
    placements: ['home_hero'],
    start_date: null as any,
    end_date: null as any,
  },
  {
    id: 'ad-home-featured',
    name: 'Súkkulaði Mousse',
    client: 'Sælgætisgerðin',
    format: '310x400',
    creatives: {
      '310x400': 'https://images.unsplash.com/photo-1555992336-03a23c7b20ee?q=80&w=310&h=400&fit=crop'
    },
    image_url: 'https://images.unsplash.com/photo-1555992336-03a23c7b20ee?q=80&w=310&h=400&fit=crop',
    target_url: '#',
    status: 'active',
    placements: ['home_featured'],
    start_date: null as any,
    end_date: null as any,
  }
];

export const mockRestaurants: Restaurant[] = [
  // ─── REYKJAVÍK ───
  {
    id: 'flatey-pizza',
    name: 'Flatey Pizza',
    slug: 'flatey-pizza',
    description_is: 'Ekta napólísk súrdeigspizza, bökuð í 500 gráða viðarofni á 90 sekúndum. Beint úr sveitinni.',
    description_en: 'Authentic Neapolitan sourdough pizza baked in a 500°C wood fire oven in 90 seconds. Farm fresh.',
    address: 'Grandagarður 11',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1539, longitude: -21.9392 } as any,
    phone: '588 5555',
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '11-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Súrdeig'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    google_place_id: 'ChIJ_flatey_rvk', tripadvisor_url: 'https://tripadvisor.com/flatey-pizza',
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Súrdeig', 'Viðarofn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'olifa-la-madre',
    name: 'Olifa La Madre',
    slug: 'olifa-la-madre',
    description_is: 'Fyrsti Pala pizzustaðurinn á Íslandi. Rómversk pizza með lífrænum hráefnum og stökkum súrdeigsbotni.',
    description_en: 'Iceland\'s first Pala pizza restaurant. Roman-style with organic ingredients and crispy sourdough crust.',
    address: 'Laugavegur 2b',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1466, longitude: -21.9331 } as any,
    phone: '551 0100',
    website: 'https://olifa.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '11:30-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Lífrænt'],
    image_urls: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Rómversk', 'Pala', 'Lífræn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'daddis-pizza',
    name: 'Daddi\'s Pizza',
    slug: 'daddis-pizza',
    description_is: 'Fjölskyldurekin pizzería í hjarta Reykjavíkur. Handflet deig og yfir 30 tegundir af áleggi. Klassískt andrúmsloft.',
    description_en: 'Family-owned pizzeria in the heart of Reykjavik. Hand-tossed dough with 30+ topping choices.',
    address: 'Hafnarstræti 8',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1482, longitude: -21.9382 } as any,
    phone: '561 2345',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Fjölskyldu-vænlegt'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Klassísk', 'Fjölskylda', 'Handýtt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'eldofninn',
    name: 'Eldofninn',
    slug: 'eldofninn',
    description_is: 'Vinsælt takeaway. Steinofn fluttur frá Ítalíu. Þunnar og stökkar pizzur gerðar frá grunni.',
    description_en: 'Popular takeaway spot. Stone oven imported from Italy. Thin and crispy scratch-made pizzas.',
    address: 'Bragagata 38a',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1459, longitude: -21.9385 } as any,
    phone: '562 3838',
    website: 'https://eldofninn.is',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Takeaway', 'Delivery', 'Steinofn'],
    image_urls: ['https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Takeaway', 'Steinofn', 'Þunn skorpa'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'hornid',
    name: 'Hornið',
    slug: 'hornid',
    description_is: 'Elsta ítalska veitingahúsið í Reykjavík, stofnað 1979. Hafnarglæsileiki, vænir skammtar og klassískar pizzur.',
    description_en: 'Reykjavik\'s oldest Italian restaurant, established 1979. Harbor-side charm, generous portions, classic pizzas.',
    address: 'Hafnarstræti 15',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1489, longitude: -21.9369 } as any,
    phone: '551 3340',
    website: 'https://hornid.is',
    opening_hours: { mán: '11:30-23', þri: '11:30-23', mið: '11:30-23', fim: '11:30-23', fös: '11:30-01', lau: '12-01', sun: '12-23' },
    price_level: 3,
    features: ['Dine-in', 'Bar', 'Sögulegt'],
    image_urls: ['https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Sögulegt', 'Klassískt', 'Höfn'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'reykjavik-pizzeria',
    name: 'Reykjavik Pizzeria',
    slug: 'reykjavik-pizzeria',
    description_is: 'Eldbakaðar pizzur á hagstæðu verði. Stórt úrval af hefðbundnum og nýstárlegum pizzum.',
    description_en: 'Fire-baked pizzas at affordable prices. Wide selection of traditional and unique pies.',
    address: 'Háteigsvegur 9',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1412, longitude: -21.9120 } as any,
    phone: '562 4444',
    website: 'https://reykjavikpizzeria.is',
    opening_hours: { mán: '11:30-21:30', þri: '11:30-21:30', mið: '11:30-21:30', fim: '11:30-21:30', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Vegan', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Eldbakað', 'Hagstætt', 'Vegan'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'bakabaka',
    name: 'BakaBaka',
    slug: 'bakabaka',
    description_is: 'Bakarí að degi, pizzería að kvöldi. Langur hefunartími gefur djúpt og flókið bragð.',
    description_en: 'Bakery by day, pizzeria by evening. Long fermentation creates deep, complex flavors.',
    address: 'Skólavörðustígur 36',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1440, longitude: -21.9274 } as any,
    opening_hours: { mán: '17-21', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '17-22', sun: 'Lokað' },
    price_level: 3,
    features: ['Dine-in', 'Bakarí', 'Súrdeig'],
    image_urls: ['https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.7, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Súrdeig', 'Bakarí', 'Hefun'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'blackbox-pizzeria',
    name: 'Blackbox Pizzeria',
    slug: 'blackbox-pizzeria',
    description_is: 'Klassísk pizzería. Deigið hvílir í sólarhring og er bakað á undir 2 mínútum.',
    description_en: 'Classic-style pizzeria. Dough proves for a full day and bakes in under 2 minutes.',
    address: 'Borgartún 26',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1437, longitude: -21.9098 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Fljótt'],
    image_urls: ['https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Klassísk', 'Fljótt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'coocoos-nest',
    name: 'The Coocoo\'s Nest',
    slug: 'coocoos-nest',
    description_is: 'Huggulegt brúnsjstaður og pizza bar. Þunnur botn, stökkir og brenndir kantar. Frábærir kokteilar.',
    description_en: 'Cozy brunch spot and pizza bar. Thin, crispy, and charred crust. Excellent cocktails.',
    address: 'Grandagarður 23',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1545, longitude: -21.9410 } as any,
    website: 'https://coocoosnest.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '10-23', sun: '10-22' },
    price_level: 3,
    features: ['Dine-in', 'Bar', 'Brúnsj', 'Kokteill'],
    image_urls: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Brúnsj', 'Kokteill', 'Grandi'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'kaffi-laugalaekur',
    name: 'Kaffi Laugalækur',
    slug: 'kaffi-laugalaekur',
    description_is: 'Hverfis-gastrobar með verðlaunuðum súrdeigspizzum. Huggulegt og staðbundið.',
    description_en: 'Neighborhood gastro bar with award-winning sourdough pizzas. Cozy and local.',
    address: 'Laugalækur 6',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1404, longitude: -21.8985 } as any,
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Bar', 'Súrdeig', 'Verðlaunað'],
    image_urls: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Gastro bar', 'Súrdeig', 'Verðlaunað'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'rossopomodoro',
    name: 'Rossopomodoro',
    slug: 'rossopomodoro',
    description_is: 'Napólískur veitingastaður á Laugavegi. Ekta ítölsk pizza, pasta og vín.',
    description_en: 'Neapolitan chain restaurant on Laugavegur. Authentic Italian pizza, pasta, and wine.',
    address: 'Laugavegur 40',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1448, longitude: -21.9256 } as any,
    website: 'https://rossopomodoro.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 3,
    features: ['Dine-in', 'Vín', 'Napólí'],
    image_urls: ['https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Keðja', 'Vín'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-with-no-name',
    name: 'Pizza With No Name',
    slug: 'pizza-with-no-name',
    description_is: 'Leyndarmálið á Hlemmi. Frábærar pizzur, gott andrúmsloft í nýja mathöllinni.',
    description_en: 'The secret at Hlemmur. Great pizzas, good atmosphere in the new food hall.',
    address: 'Hlemmur Mathöll',
    city: 'Reykjavík',
    postal_code: '105',
    location: { latitude: 64.1432, longitude: -21.9145 } as any,
    opening_hours: { daglega: '11:30-22:00' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Mathöll'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Hlemmur', 'Mathöll', 'Casual'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'napoli-pizza-rvk',
    name: 'Napoli Pizza',
    slug: 'napoli-pizza-rvk',
    description_is: 'Hefðbundin napólísk pizza á besta matarsvæði Reykjavíkur. Ferskt deig daglega.',
    description_en: 'Traditional Neapolitan pizza in Reykjavik\'s best food district. Fresh dough daily.',
    address: 'Tryggvagata 14',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1495, longitude: -21.9392 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Napólí', 'Hefðbundin'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'glosteinnn',
    name: 'Glósteinn',
    slug: 'glosteinn',
    description_is: 'Steinbökuð pizza á hagstæðu verði. Stórt úrval og góðir hádegisréttir.',
    description_en: 'Stone-baked pizza at affordable prices. Wide selection and great lunch deals.',
    address: 'Hringbraut 119',
    city: 'Reykjavík',
    postal_code: '107',
    location: { latitude: 64.1390, longitude: -21.9280 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 1,
    features: ['Takeaway', 'Delivery', 'Hagstætt'],
    image_urls: ['https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Hagstætt', 'Steinbakað', 'Delivery'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-popolare',
    name: 'Pizza Popolare Pósthús',
    slug: 'pizza-popolare',
    description_is: 'Í gamla pósthúsinu í Austurstræti. Viðarofnsbakaðar pizzur og ítalskt andrúmsloft.',
    description_en: 'In the old post office on Austurstræti. Wood-fired and Italian atmosphere.',
    address: 'Austurstræti 13',
    city: 'Reykjavík',
    postal_code: '101',
    location: { latitude: 64.1477, longitude: -21.9351 } as any,
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 3,
    features: ['Dine-in', 'Viðarofn', 'Sögulegt hús'],
    image_urls: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Miðborg', 'Sögulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── AKUREYRI ───
  {
    id: 'pizzasmidjan-akureyri',
    name: 'Pizzasmiðjan',
    slug: 'pizzasmidjan-akureyri',
    description_is: 'Viðarofnspizza í hjarta Akureyrar. Rólegt og huggulegt andrúmsloft.',
    description_en: 'Wood-fired pizza in the heart of Akureyri. Relaxed and cozy atmosphere.',
    address: 'Kaupvangsstræti 6',
    city: 'Akureyri',
    postal_code: '600',
    location: { latitude: 65.6835, longitude: -18.0878 } as any,
    website: 'https://pizzasmidjan.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1585238342024-78d387f4a707?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Viðarofn', 'Akureyri', 'Norðurland'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'greifinn-akureyri',
    name: 'Greifinn',
    slug: 'greifinn-akureyri',
    description_is: 'Vinsæll staður á Akureyri þar sem hægt er að borða pizzur, borgara og íslenska rétti. Fjölskylduvænlegt.',
    description_en: 'Popular Akureyri spot serving pizzas, burgers, and Icelandic dishes. Family-friendly.',
    address: 'Glerárgata 20',
    city: 'Akureyri',
    postal_code: '600',
    location: { latitude: 65.6810, longitude: -18.0930 } as any,
    phone: '460 1600',
    opening_hours: { mán: '11:30-22', þri: '11:30-22', mið: '11:30-22', fim: '11:30-22', fös: '11:30-23', lau: '12-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Fjölskylduvænlegt', 'Bar'],
    image_urls: ['https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Fjölskylda', 'Akureyri'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── KEFLAVÍK ───
  {
    id: 'antons-mamma-mia',
    name: 'Antons Mamma Mia',
    slug: 'antons-mamma-mia',
    description_is: 'Steinofnspizzur í Keflavík. Huggulegt og rólegt andrúmsloft með ítölskum matseðli.',
    description_en: 'Stone-oven pizzas in Keflavik. Cozy atmosphere with a full Italian menu.',
    address: 'Hafnargata 32',
    city: 'Keflavík',
    postal_code: '230',
    location: { latitude: 64.0048, longitude: -22.5631 } as any,
    phone: '421 5533',
    website: 'https://antons.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Steinofn', 'Pasta'],
    image_urls: ['https://images.unsplash.com/photo-1485182708500-e8f1f318ba72?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Steinofn', 'Keflavík', 'Ítalía'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'fernandos-keflavik',
    name: 'Fernando\'s',
    slug: 'fernandos-keflavik',
    description_is: 'Vinsæll ítalskur veitingastaður í Keflavík. Ferskar pizzur og pasta með íslensku ívafi.',
    description_en: 'Popular Italian restaurant in Keflavik. Fresh pizzas and pasta with an Icelandic twist.',
    address: 'Hafnargata 5',
    city: 'Keflavík',
    postal_code: '230',
    location: { latitude: 64.0052, longitude: -22.5580 } as any,
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0, rating_tripadvisor: 3.5,
    likes_count: 0, is_verified: false, tags: ['Keflavík', 'Ítalía'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── AUSTFIRÐIR ───
  {
    id: 'pizzafjordur',
    name: 'Pizzafjörður',
    slug: 'pizzafjordur',
    description_is: 'Lítil pizzería á Eskifirði með frábærar pizzur og vinalegt fólk. Ferskt deig, mikið áleggsúrval og rólegt andrúmsloft á Austfjörðum.',
    description_en: 'Small pizzeria in Eskifjörður with amazing pizza and friendly staff. Fresh dough, lots of toppings, and calm East Iceland vibes.',
    address: 'Strandgata 25',
    city: 'Eskifjörður',
    postal_code: '735',
    location: { latitude: 65.0712, longitude: -14.0131 } as any,
    opening_hours: { sun: '17-21', mán: '17-21', þri: '17-21', mið: '17-21', fim: 'Lokað', fös: 'Lokað', lau: 'Lokað' },
    price_level: 2,
    features: ['Takeaway', 'Glutenlaust val'],
    image_urls: ['https://images.unsplash.com/photo-1600628421055-4d30de868b8f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.7, rating_tripadvisor: 5.0,
    likes_count: 0, is_verified: false, tags: ['Austfirðir', 'Eskifjörður', 'Huggulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── SELFOSS ───
  {
    id: 'flatey-pizza-selfoss',
    name: 'Flatey Pizza Selfoss',
    slug: 'flatey-pizza-selfoss',
    description_is: 'Útibú Flatey Pizza á Selfossi. Sömu einkennandi napólísku pizzurnar úr viðarofni.',
    description_en: 'Flatey Pizza branch in Selfoss. Same signature Neapolitan wood-fired pizzas.',
    address: 'Austurvegur 1',
    city: 'Selfoss',
    postal_code: '800',
    location: { latitude: 63.9355, longitude: -21.0035 } as any,
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Viðarofn', 'Selfoss'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'kaffi-krus',
    name: 'Kaffi Krús',
    slug: 'kaffi-krus',
    description_is: 'Huggulegt kaffihús á Selfossi. Stökkar pizzur og borgarar ásamt steinbökuðu brauði.',
    description_en: 'Cozy café in Selfoss. Crispy pizzas, burgers, and artisan bread.',
    address: 'Austurvegur 7',
    city: 'Selfoss',
    postal_code: '800',
    location: { latitude: 63.9353, longitude: -21.0020 } as any,
    website: 'https://kaffikrus.is',
    opening_hours: { mán: '08-22', þri: '08-22', mið: '08-22', fim: '08-22', fös: '08-23', lau: '09-23', sun: '09-22' },
    price_level: 2,
    features: ['Dine-in', 'Kaffi', 'Brauð'],
    image_urls: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Kaffi', 'Selfoss', 'Huggulegt'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── HÚSAVÍK ───
  {
    id: 'pizza-kofinn',
    name: 'Pizza Kofinn',
    slug: 'pizza-kofinn',
    description_is: 'Viðarofnspizza í bæjarkjarna Húsavíkur. Staðbundið, vinalegt og gott. Margherita, pepperóní og Parma.',
    description_en: 'Wood-fired pizza in the heart of Húsavík. Local, friendly, and delicious. Margherita, pepperoni, and Parma.',
    address: 'Hafnarstétt 9',
    city: 'Húsavík',
    postal_code: '640',
    location: { latitude: 66.0449, longitude: -17.3389 } as any,
    website: 'https://pizzakofinn.is',
    opening_hours: { mán: '12-21', þri: '12-21', mið: '12-21', fim: '12-21', fös: '12-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Húsavík', 'Norðurland'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── VESTMANNAEYJAR ───
  {
    id: 'pitsugerdin',
    name: 'Pítsugerðin',
    slug: 'pitsugerdin',
    description_is: 'Ekta viðarofnspizza í Vestmannaeyjum. San Marzano tómatar, súrdeig og staðbundinn bjór á krana.',
    description_en: 'Authentic wood-fired pizza in the Westman Islands. San Marzano tomatoes, sourdough, and local craft beer.',
    address: 'Vestmannabraut 28',
    city: 'Vestmannaeyjar',
    postal_code: '900',
    location: { latitude: 63.4427, longitude: -20.2690 } as any,
    opening_hours: { mán: 'Lokað', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Viðarofn', 'Bjór'],
    image_urls: ['https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.5, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: false, tags: ['Viðarofn', 'Vestmannaeyjar', 'Súrdeig'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-67-vestmannaeyjar',
    name: 'Pizza 67',
    slug: 'pizza-67-vestmannaeyjar',
    description_is: 'Ítölsk pizza í Eyjum. Stórt úrval á hagstæðu verði.',
    description_en: 'Italian pizza in the Westman Islands. Wide selection at affordable prices.',
    address: 'Bárustígur 11',
    city: 'Vestmannaeyjar',
    postal_code: '900',
    location: { latitude: 63.4420, longitude: -20.2680 } as any,
    opening_hours: { mán: '17-21', þri: '17-21', mið: '17-21', fim: '17-21', fös: '17-22', lau: '12-22', sun: '12-21' },
    price_level: 1,
    features: ['Takeaway', 'Delivery', 'Hagstætt'],
    image_urls: ['https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2,
    likes_count: 0, is_verified: false, tags: ['Hagstætt', 'Vestmannaeyjar'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── ÍSAFJÖRÐUR ───
  {
    id: 'hamraborg-isafjordur',
    name: 'Hamraborg',
    slug: 'hamraborg-isafjordur',
    description_is: 'Pizzería á Ísafirði. 12 tommu pizzur með þremur áleggsvalkostum. Einfalt og gott.',
    description_en: '12-inch pizzas with three toppings in Ísafjörður. Simple and delicious.',
    address: 'Hafnarstræti 7',
    city: 'Ísafjörður',
    postal_code: '400',
    location: { latitude: 66.0742, longitude: -23.1350 } as any,
    website: 'https://hamraborg.com',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3,
    likes_count: 0, is_verified: false, tags: ['Ísafjörður', 'Vestfirðir'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── EGILSSTAÐIR ───
  {
    id: 'askur-pizzeria',
    name: 'Askur Pizzeria',
    slug: 'askur-pizzeria',
    description_is: 'Staðbundin brugghús-pizzería á Egilsstöðum. Búðu til þína eigin pizzu eða veldu af matseðli.',
    description_en: 'Local brewery pizzeria in Egilsstaðir. Build your own pizza or choose from the menu.',
    address: 'Fagradalsbraut 1',
    city: 'Egilsstaðir',
    postal_code: '700',
    location: { latitude: 65.2535, longitude: -14.3948 } as any,
    website: 'https://askurpizzeria.is',
    opening_hours: { mán: '11:30-21', þri: '11:30-21', mið: '11:30-21', fim: '11:30-21', fös: '11:30-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Brugghús', 'Sérsniðið'],
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.4, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Brugghús', 'Egilsstaðir', 'Austfirðir'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── STYKKISHÓLMUR ───
  {
    id: 'stykkid-pizzeria',
    name: 'Stykkið Pizzeria',
    slug: 'stykkid-pizzeria',
    description_is: 'Pizzería í fallegasta bæ Vesturlands. Ferskt deig og staðbundin hráefni.',
    description_en: 'Pizzeria in western Iceland\'s most beautiful town. Fresh dough and local ingredients.',
    address: 'Aðalgata 3',
    city: 'Stykkishólmur',
    postal_code: '340',
    location: { latitude: 65.0758, longitude: -22.7300 } as any,
    opening_hours: { mán: '12-21', þri: '12-21', mið: '12-21', fim: '12-21', fös: '12-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway'],
    image_urls: ['https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3, rating_tripadvisor: 4.0,
    likes_count: 0, is_verified: false, tags: ['Stykkishólmur', 'Snæfellsnes'],
    created_at: null as any, updated_at: null as any,
  },

  // ─── HÖFUÐBORGARSVÆÐIÐ ───
  {
    id: 'pizzan-hafnarfjordur',
    name: 'Pizzan Hafnarfjörður',
    slug: 'pizzan-hafnarfjordur',
    description_is: 'Útibú Pizzunnar á Fjarðargötu. Vinsælar pizzur og meðlæti.',
    description_en: 'Pizzan branch on Fjarðargata. Popular pizzas and sides.',
    address: 'Fjarðargata 13-15',
    city: 'Hafnarfjörður',
    postal_code: '220',
    location: { latitude: 64.0671, longitude: -21.9549 } as any,
    website: 'https://pizzan.is',
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1,
    likes_count: 0, is_verified: false, tags: ['Hafnarfjörður', 'Keðja'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'flatey-pizza-gardabaer',
    name: 'Flatey Pizza Garðatorg',
    slug: 'flatey-pizza-gardabaer',
    description_is: 'Flatey Pizza útibú á Garðatorgi í Garðabæ. Sömu napólísku pizzurnar úr viðarofni.',
    description_en: 'Flatey Pizza branch at Garðatorg in Garðabær. Same Neapolitan wood-fired pizzas.',
    address: 'Garðatorg 7',
    city: 'Garðabær',
    postal_code: '210',
    location: { latitude: 64.0897, longitude: -21.9230 } as any,
    website: 'https://flateypizza.is',
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '11-22', sun: '12-21' },
    price_level: 3,
    features: ['Dine-in', 'Takeaway', 'Viðarofn'],
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.6, rating_tripadvisor: 4.5,
    likes_count: 0, is_verified: true, tags: ['Napólí', 'Viðarofn', 'Garðabær'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'italiano-kopavogur',
    name: 'Italiano Pizzeria',
    slug: 'italiano-kopavogur',
    description_is: 'Ítölsk pizzería í Kópavogi. Vænir skammtar og klassískar pizzur.',
    description_en: 'Italian pizzeria in Kópavogur. Generous portions and classic pizzas.',
    address: 'Smáratorg',
    city: 'Kópavogur',
    postal_code: '201',
    location: { latitude: 64.1069, longitude: -21.8822 } as any,
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.2,
    likes_count: 0, is_verified: false, tags: ['Kópavogur', 'Klassísk'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'islenska-flatbakan',
    name: 'Íslenska Flatbakan',
    slug: 'islenska-flatbakan',
    description_is: 'Íslensku flatbökurnar — pizzur með íslensku ívafi. Stórt úrval og fjölskylduvænlegt.',
    description_en: 'The Icelandic Flatbread — pizzas with an Icelandic twist. Wide selection and family-friendly.',
    address: 'Dalshraun 1',
    city: 'Kópavogur',
    postal_code: '201',
    location: { latitude: 64.1049, longitude: -21.8900 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Takeaway', 'Delivery', 'Fjölskylduvænlegt'],
    image_urls: ['https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.0,
    likes_count: 0, is_verified: false, tags: ['Kópavogur', 'Íslensku'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'pizza-braedur-mosfellsbaer',
    name: 'Pizza Bræður',
    slug: 'pizza-braedur-mosfellsbaer',
    description_is: 'Nýtt pizzahús í Mosfellsbæ. Bræðurnir baka ferskar pizzur daglega.',
    description_en: 'New pizza spot in Mosfellsbær. The brothers bake fresh pizzas daily.',
    address: 'Háholt 13',
    city: 'Mosfellsbær',
    postal_code: '270',
    location: { latitude: 64.1666, longitude: -21.6966 } as any,
    opening_hours: { mán: '11-21', þri: '11-21', mið: '11-21', fim: '11-21', fös: '11-22', lau: '12-22', sun: '12-21' },
    price_level: 2,
    features: ['Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.3,
    likes_count: 0, is_verified: false, tags: ['Mosfellsbær', 'Nýtt'],
    created_at: null as any, updated_at: null as any,
  },
  {
    id: 'castello-hafnarfjordur',
    name: 'Castello Pizzeria',
    slug: 'castello-hafnarfjordur',
    description_is: 'Klassísk pizzería í Hafnarfirði. Þykk og þunn skorpa, stórt áleggsval.',
    description_en: 'Classic pizzeria in Hafnarfjörður. Thick and thin crust options, wide topping selection.',
    address: 'Strandgata 55',
    city: 'Hafnarfjörður',
    postal_code: '220',
    location: { latitude: 64.0650, longitude: -21.9580 } as any,
    opening_hours: { mán: '11-22', þri: '11-22', mið: '11-22', fim: '11-22', fös: '11-23', lau: '11-23', sun: '12-22' },
    price_level: 2,
    features: ['Dine-in', 'Takeaway', 'Delivery'],
    image_urls: ['https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?q=80&w=1200'],
    rating_avg: 0, rating_count: 0, rating_google: 4.1,
    likes_count: 0, is_verified: false, tags: ['Hafnarfjörður', 'Klassísk'],
    created_at: null as any, updated_at: null as any,
  },
];

export const mockMenuItems: MenuItem[] = [
  // ─── Flatey Pizza ───
  { id: 'fp-1', restaurant_id: 'flatey-pizza', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano tómatar, fior di latte, basilíka, ólífuolía', description_en: 'San Marzano tomatoes, fior di latte, basil, olive oil', price: 2590, category: 'Pizzur', sort_order: 1 },
  { id: 'fp-2', restaurant_id: 'flatey-pizza', name_is: 'Padrino', name_en: 'Padrino', description_is: 'San Marzano, mozzarella, pepperóní, súr chili, hunang, basilíka', description_en: 'San Marzano, mozzarella, pepperoni, pickled chili, honey, basil', price: 3190, category: 'Pizzur', sort_order: 2 },
  { id: 'fp-3', restaurant_id: 'flatey-pizza', name_is: 'Umberto', name_en: 'Umberto', description_is: 'San Marzano, mozzarella, pepperóní, döðlur, mascarpone, basilíka', description_en: 'San Marzano, mozzarella, pepperoni, dates, mascarpone, basil', price: 3290, category: 'Pizzur', sort_order: 3 },
  { id: 'fp-4', restaurant_id: 'flatey-pizza', name_is: 'Tartufo', name_en: 'Tartufo', description_is: 'Mozzarella, sveppir, ricotta, kartöflur, trufflolía, sjávarsalt', description_en: 'Mozzarella, mushrooms, ricotta, potatoes, truffle oil, sea salt', price: 3490, category: 'Pizzur', sort_order: 4 },
  { id: 'fp-5', restaurant_id: 'flatey-pizza', name_is: 'Stracciatella', name_en: 'Stracciatella', description_is: 'Gráðaður skinka, mozzarella, stracciatella, basilíkuolía, parmesan', description_en: 'Cured ham, mozzarella, stracciatella, basil oil, parmesan', price: 3590, category: 'Pizzur', sort_order: 5 },
  // ─── Olifa La Madre ───
  { id: 'ol-1', restaurant_id: 'olifa-la-madre', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Pelati tómatsósa, mozzarella, fersk basilíka', description_en: 'Pelati tomato sauce, mozzarella, fresh basil', price: 2999, category: 'Pizzur', sort_order: 1 },
  { id: 'ol-2', restaurant_id: 'olifa-la-madre', name_is: 'Piccante', name_en: 'Piccante', description_is: 'Pelati, mozzarella, Spianata Calabrese (sterk pepperóní)', description_en: 'Pelati, mozzarella, Spianata Calabrese (spicy pepperoni)', price: 3499, category: 'Pizzur', sort_order: 2 },
  { id: 'ol-3', restaurant_id: 'olifa-la-madre', name_is: 'Fiducia', name_en: 'Fiducia', description_is: 'Pelati, mozzarella, rjómaostur, Calabrese, Cotto skinka, sveppir, jalapeño', description_en: 'Pelati, mozzarella, cream cheese, Calabrese, Cotto ham, mushrooms, jalapeño', price: 3799, category: 'Pizzur', sort_order: 3 },
  { id: 'ol-4', restaurant_id: 'olifa-la-madre', name_is: '4 Formaggi', name_en: '4 Formaggi', description_is: 'Mozzarella, Asiago, Gorgonzola, Parmigiano, Savini trufflur', description_en: 'Mozzarella, Asiago, Gorgonzola, Parmigiano, Savini truffles', price: 3999, category: 'Pizzur', sort_order: 4 },
  { id: 'ol-5', restaurant_id: 'olifa-la-madre', name_is: 'Cotto', name_en: 'Cotto', description_is: 'Mozzarella, burrata, Parmigiano, Cotto skinka, ofnbakaðir sveppir', description_en: 'Mozzarella, burrata, Parmigiano, Cotto ham, oven-baked mushrooms', price: 3699, category: 'Pizzur', sort_order: 5 },
  // ─── Daddi's Pizza ───
  { id: 'dp-1', restaurant_id: 'daddis-pizza', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2490, category: 'Pizzur', sort_order: 1 },
  { id: 'dp-2', restaurant_id: 'daddis-pizza', name_is: 'Mýfluga', name_en: 'Mosquito', description_is: 'Tómatsósa, ostur, reyktur silungur, furunhnetur, rjómaostur', description_en: 'Tomato sauce, cheese, smoked trout, pine nuts, cream cheese', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'dp-3', restaurant_id: 'daddis-pizza', name_is: 'Ítalinn', name_en: 'The Italian', description_is: 'Pizzusósa, buffaló-mozzarella, gæðaskinka, sveppir, basilíku-olía', description_en: 'Pizza sauce, buffalo mozzarella, quality ham, mushrooms, basil oil', price: 3490, category: 'Pizzur', sort_order: 3 },
  { id: 'dp-4', restaurant_id: 'daddis-pizza', name_is: 'Lúdent', name_en: 'The Lamb', description_is: 'Tómatsósa, ostur, lambakjöt, hvítlauks-sveppir, béarnaise', description_en: 'Tomato sauce, cheese, local lamb, garlic-butter mushrooms, béarnaise', price: 3590, category: 'Pizzur', sort_order: 4 },
  { id: 'dp-5', restaurant_id: 'daddis-pizza', name_is: 'Coronary', name_en: 'Coronary', description_is: 'Tómatsósa, ostur, pepperóní, beikon, skinka, nautahakk', description_en: 'Tomato sauce, cheese, pepperoni, bacon, ham, ground beef', price: 3690, category: 'Pizzur', sort_order: 5 },
  // ─── Eldofninn ───
  { id: 'el-1', restaurant_id: 'eldofninn', name_is: 'Margarita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2450, category: 'Pizzur', sort_order: 1 },
  { id: 'el-2', restaurant_id: 'eldofninn', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 3250, category: 'Pizzur', sort_order: 2 },
  { id: 'el-3', restaurant_id: 'eldofninn', name_is: 'Rúkkóla', name_en: 'Ruccola', description_is: 'Mozzarella, Parma-skinka, rúkkóla, parmesan, trufflolía', description_en: 'Mozzarella, Parma ham, arugula, parmesan, truffle oil', price: 3800, category: 'Pizzur', sort_order: 3 },
  { id: 'el-4', restaurant_id: 'eldofninn', name_is: 'Eldofninn', name_en: 'Eldofninn Special', description_is: 'Tómatsósa, mozzarella, skinka, sveppir, paprika, ólífur', description_en: 'Tomato sauce, mozzarella, ham, mushrooms, peppers, olives', price: 3440, category: 'Pizzur', sort_order: 4 },
  { id: 'el-5', restaurant_id: 'eldofninn', name_is: 'More Meat', name_en: 'More Meat', description_is: 'Tómatsósa, mozzarella, pepperóní, beikon, skinka, nautahakk', description_en: 'Tomato sauce, mozzarella, pepperoni, bacon, ham, ground beef', price: 4450, category: 'Pizzur', sort_order: 5 },
  // ─── Hornið ───
  { id: 'ho-1', restaurant_id: 'hornid', name_is: 'Pizza Classica', name_en: 'Classic Pizza', description_is: 'Tómatar, mozzarella, sveppir, paprika, ólífur', description_en: 'Tomato, mozzarella, mushrooms, peppers, olives', price: 2990, category: 'Pizzur', sort_order: 1 },
  { id: 'ho-2', restaurant_id: 'hornid', name_is: 'Pizza Hornið', name_en: 'Pizza Hornið', description_is: 'Einkennispizza með sölsu, jalapeño og pepperóní', description_en: 'Signature pizza with salsa, jalapeño and pepperoni', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'ho-3', restaurant_id: 'hornid', name_is: 'Pizza Roma', name_en: 'Pizza Roma', description_is: 'Pepperóní, bláostur, ananas, grænir piparkornar', description_en: 'Pepperoni, blue cheese, pineapple, green peppercorns', price: 3390, category: 'Pizzur', sort_order: 3 },
  { id: 'ho-4', restaurant_id: 'hornid', name_is: 'Pizza Vegetariana', name_en: 'Vegetarian Pizza', description_is: 'Tómatar, mozzarella, grænmetisblanda, ólífur, basilíka', description_en: 'Tomato, mozzarella, mixed vegetables, olives, basil', price: 2890, category: 'Pizzur', sort_order: 4 },
  // ─── Reykjavik Pizzeria ───
  { id: 'rp-1', restaurant_id: 'reykjavik-pizzeria', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2290, category: 'Pizzur', sort_order: 1 },
  { id: 'rp-2', restaurant_id: 'reykjavik-pizzeria', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2690, category: 'Pizzur', sort_order: 2 },
  { id: 'rp-3', restaurant_id: 'reykjavik-pizzeria', name_is: 'Vegan Grænmetis', name_en: 'Vegan Veggie', description_is: 'Tómatsósa, vegan-ostur, paprika, sveppir, laukur, ólífur', description_en: 'Tomato sauce, vegan cheese, peppers, mushrooms, onion, olives', price: 2790, category: 'Pizzur', sort_order: 3 },
  { id: 'rp-4', restaurant_id: 'reykjavik-pizzeria', name_is: 'Kjúklingur og beikon', name_en: 'Chicken & Bacon', description_is: 'Hvítlaukssósa, mozzarella, kjúklingur, beikon, rauðlaukur', description_en: 'Garlic sauce, mozzarella, chicken, bacon, red onion', price: 3090, category: 'Pizzur', sort_order: 4 },
  // ─── BakaBaka ───
  { id: 'bb-1', restaurant_id: 'bakabaka', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Súrdeigsbotn, San Marzano, mozzarella, basilíka', description_en: 'Sourdough crust, San Marzano, mozzarella, basil', price: 2790, category: 'Pizzur', sort_order: 1 },
  { id: 'bb-2', restaurant_id: 'bakabaka', name_is: 'Súrdeigssveppir', name_en: 'Sourdough Mushroom', description_is: 'Mozzarella, blandaðir sveppir, trufflolía, parmesan', description_en: 'Mozzarella, mixed mushrooms, truffle oil, parmesan', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'bb-3', restaurant_id: 'bakabaka', name_is: 'Nduja', name_en: 'Nduja', description_is: 'Tómatsósa, mozzarella, nduja pylsa, hunang, rúkkóla', description_en: 'Tomato sauce, mozzarella, nduja sausage, honey, arugula', price: 3490, category: 'Pizzur', sort_order: 3 },
  // ─── Blackbox Pizzeria ───
  { id: 'bx-1', restaurant_id: 'blackbox-pizzeria', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2190, category: 'Pizzur', sort_order: 1 },
  { id: 'bx-2', restaurant_id: 'blackbox-pizzeria', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2590, category: 'Pizzur', sort_order: 2 },
  { id: 'bx-3', restaurant_id: 'blackbox-pizzeria', name_is: 'BBQ kjúklingur', name_en: 'BBQ Chicken', description_is: 'BBQ-sósa, mozzarella, kjúklingur, rauðlaukur, kóríander', description_en: 'BBQ sauce, mozzarella, chicken, red onion, cilantro', price: 2890, category: 'Pizzur', sort_order: 3 },
  // ─── The Coocoo's Nest ───
  { id: 'cn-1', restaurant_id: 'coocoos-nest', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka, ólífuolía', description_en: 'Tomato sauce, mozzarella, basil, olive oil', price: 2790, category: 'Pizzur', sort_order: 1 },
  { id: 'cn-2', restaurant_id: 'coocoos-nest', name_is: 'Parma', name_en: 'Parma', description_is: 'Mozzarella, Parma-skinka, rúkkóla, parmesan', description_en: 'Mozzarella, Parma ham, arugula, parmesan', price: 3490, category: 'Pizzur', sort_order: 2 },
  { id: 'cn-3', restaurant_id: 'coocoos-nest', name_is: 'Trufflupizza', name_en: 'Truffle Pizza', description_is: 'Mozzarella, sveppir, trufflukrem, parmesan, þýmían', description_en: 'Mozzarella, mushrooms, truffle cream, parmesan, thyme', price: 3590, category: 'Pizzur', sort_order: 3 },
  // ─── Kaffi Laugalækur ───
  { id: 'kl-1', restaurant_id: 'kaffi-laugalaekur', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Súrdeig, tómatsósa, mozzarella, basilíka', description_en: 'Sourdough, tomato sauce, mozzarella, basil', price: 2590, category: 'Pizzur', sort_order: 1 },
  { id: 'kl-2', restaurant_id: 'kaffi-laugalaekur', name_is: 'Pepperóní og hunang', name_en: 'Pepperoni & Honey', description_is: 'Tómatsósa, mozzarella, pepperóní, hunang, chili', description_en: 'Tomato sauce, mozzarella, pepperoni, honey, chili', price: 3090, category: 'Pizzur', sort_order: 2 },
  { id: 'kl-3', restaurant_id: 'kaffi-laugalaekur', name_is: 'Hvítlauks-kjúklingur', name_en: 'Garlic Chicken', description_is: 'Hvítlaukssósa, mozzarella, kjúklingur, sólþurrkaðir tómatar', description_en: 'Garlic sauce, mozzarella, chicken, sun-dried tomatoes', price: 3190, category: 'Pizzur', sort_order: 3 },
  // ─── Rossopomodoro ───
  { id: 'rs-1', restaurant_id: 'rossopomodoro', name_is: 'Margherita DOC', name_en: 'Margherita DOC', description_is: 'San Marzano DOP, buffaló-mozzarella, basilíka, ólífuolía', description_en: 'San Marzano DOP, buffalo mozzarella, basil, olive oil', price: 2990, category: 'Pizzur', sort_order: 1 },
  { id: 'rs-2', restaurant_id: 'rossopomodoro', name_is: 'Diavola', name_en: 'Diavola', description_is: 'Tómatsósa, mozzarella, sterk salami, chili', description_en: 'Tomato sauce, mozzarella, spicy salami, chili', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'rs-3', restaurant_id: 'rossopomodoro', name_is: 'Napoli', name_en: 'Napoli', description_is: 'Tómatsósa, mozzarella, ansjósur, kapers, ólífur', description_en: 'Tomato sauce, mozzarella, anchovies, capers, olives', price: 3190, category: 'Pizzur', sort_order: 3 },
  { id: 'rs-4', restaurant_id: 'rossopomodoro', name_is: 'Calzone', name_en: 'Calzone', description_is: 'Samanbrotin pizza, ricotta, mozzarella, skinka, sveppir', description_en: 'Folded pizza, ricotta, mozzarella, ham, mushrooms', price: 3490, category: 'Pizzur', sort_order: 4 },
  // ─── Pizza With No Name ───
  { id: 'pn-1', restaurant_id: 'pizza-with-no-name', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2390, category: 'Pizzur', sort_order: 1 },
  { id: 'pn-2', restaurant_id: 'pizza-with-no-name', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní, hunang', description_en: 'Tomato sauce, mozzarella, pepperoni, honey', price: 2890, category: 'Pizzur', sort_order: 2 },
  { id: 'pn-3', restaurant_id: 'pizza-with-no-name', name_is: 'Hvíta', name_en: 'The White', description_is: 'Rjómastofn, mozzarella, ricotta, parmesan, svartpipar', description_en: 'Cream base, mozzarella, ricotta, parmesan, black pepper', price: 2990, category: 'Pizzur', sort_order: 3 },
  // ─── Napoli Pizza ───
  { id: 'np-1', restaurant_id: 'napoli-pizza-rvk', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2290, category: 'Pizzur', sort_order: 1 },
  { id: 'np-2', restaurant_id: 'napoli-pizza-rvk', name_is: 'Quattro Stagioni', name_en: 'Quattro Stagioni', description_is: 'Tómatsósa, mozzarella, skinka, sveppir, artisjóka, ólífur', description_en: 'Tomato sauce, mozzarella, ham, mushrooms, artichoke, olives', price: 2990, category: 'Pizzur', sort_order: 2 },
  { id: 'np-3', restaurant_id: 'napoli-pizza-rvk', name_is: 'Capricciosa', name_en: 'Capricciosa', description_is: 'Tómatsósa, mozzarella, skinka, sveppir, ólífur', description_en: 'Tomato sauce, mozzarella, ham, mushrooms, olives', price: 2790, category: 'Pizzur', sort_order: 3 },
  // ─── Glósteinn ───
  { id: 'gs-1', restaurant_id: 'glosteinnn', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, oreganó', description_en: 'Tomato sauce, mozzarella, oregano', price: 1890, category: 'Pizzur', sort_order: 1 },
  { id: 'gs-2', restaurant_id: 'glosteinnn', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2190, category: 'Pizzur', sort_order: 2 },
  { id: 'gs-3', restaurant_id: 'glosteinnn', name_is: 'Hawaii', name_en: 'Hawaiian', description_is: 'Tómatsósa, mozzarella, skinka, ananas', description_en: 'Tomato sauce, mozzarella, ham, pineapple', price: 2190, category: 'Pizzur', sort_order: 3 },
  { id: 'gs-4', restaurant_id: 'glosteinnn', name_is: 'Ofnbakað kjúklinga-pizza', name_en: 'Baked Chicken Pizza', description_is: 'Hvítlaukssósa, mozzarella, kjúklingur, beikon, laukur', description_en: 'Garlic sauce, mozzarella, chicken, bacon, onion', price: 2490, category: 'Pizzur', sort_order: 4 },
  // ─── Pizza Popolare ───
  { id: 'pp-1', restaurant_id: 'pizza-popolare', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano tómatar, mozzarella, basilíka', description_en: 'San Marzano tomatoes, mozzarella, basil', price: 2790, category: 'Pizzur', sort_order: 1 },
  { id: 'pp-2', restaurant_id: 'pizza-popolare', name_is: 'Diavola', name_en: 'Diavola', description_is: 'Tómatsósa, mozzarella, sterk salami, chili flögur', description_en: 'Tomato sauce, mozzarella, spicy salami, chili flakes', price: 3190, category: 'Pizzur', sort_order: 2 },
  { id: 'pp-3', restaurant_id: 'pizza-popolare', name_is: 'Parma e Rúkkóla', name_en: 'Parma & Arugula', description_is: 'Mozzarella, Parma-skinka, rúkkóla, parmesan', description_en: 'Mozzarella, Parma ham, arugula, parmesan', price: 3490, category: 'Pizzur', sort_order: 3 },
  // ─── Pizzasmiðjan Akureyri ───
  { id: 'pa-1', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2490, category: 'Pizzur', sort_order: 1 },
  { id: 'pa-2', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2890, category: 'Pizzur', sort_order: 2 },
  { id: 'pa-3', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Norðlenska', name_en: 'The Northern', description_is: 'Tómatsósa, mozzarella, reyktur lax, rjómastofn, dill', description_en: 'Tomato sauce, mozzarella, smoked salmon, cream base, dill', price: 3290, category: 'Pizzur', sort_order: 3 },
  { id: 'pa-4', restaurant_id: 'pizzasmidjan-akureyri', name_is: 'Sveppapizza', name_en: 'Mushroom Pizza', description_is: 'Mozzarella, blandaðir sveppir, hvítlaukur, þýmían, trufflolía', description_en: 'Mozzarella, mixed mushrooms, garlic, thyme, truffle oil', price: 3190, category: 'Pizzur', sort_order: 4 },
  // ─── Greifinn Akureyri ───
  { id: 'ga-1', restaurant_id: 'greifinn-akureyri', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, oreganó', description_en: 'Tomato sauce, mozzarella, oregano', price: 2390, category: 'Pizzur', sort_order: 1 },
  { id: 'ga-2', restaurant_id: 'greifinn-akureyri', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2690, category: 'Pizzur', sort_order: 2 },
  { id: 'ga-3', restaurant_id: 'greifinn-akureyri', name_is: 'Kjúklingapizza', name_en: 'Chicken Pizza', description_is: 'Hvítlaukssósa, mozzarella, kjúklingur, paprika, laukur', description_en: 'Garlic sauce, mozzarella, chicken, peppers, onion', price: 2890, category: 'Pizzur', sort_order: 3 },
  // ─── Antons Mamma Mia ───
  { id: 'am-1', restaurant_id: 'antons-mamma-mia', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2390, category: 'Pizzur', sort_order: 1 },
  { id: 'am-2', restaurant_id: 'antons-mamma-mia', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2690, category: 'Pizzur', sort_order: 2 },
  { id: 'am-3', restaurant_id: 'antons-mamma-mia', name_is: 'Calzone', name_en: 'Calzone', description_is: 'Samanbrotin, ricotta, mozzarella, skinka, sveppir', description_en: 'Folded, ricotta, mozzarella, ham, mushrooms', price: 2990, category: 'Pizzur', sort_order: 3 },
  // ─── Fernando's ───
  { id: 'fe-1', restaurant_id: 'fernandos-keflavik', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2290, category: 'Pizzur', sort_order: 1 },
  { id: 'fe-2', restaurant_id: 'fernandos-keflavik', name_is: 'Quattro Formaggi', name_en: 'Four Cheese', description_is: 'Mozzarella, gorgonzola, parmesan, ricotta', description_en: 'Mozzarella, gorgonzola, parmesan, ricotta', price: 2890, category: 'Pizzur', sort_order: 2 },
  { id: 'fe-3', restaurant_id: 'fernandos-keflavik', name_is: 'Hawaii', name_en: 'Hawaiian', description_is: 'Tómatsósa, mozzarella, skinka, ananas', description_en: 'Tomato sauce, mozzarella, ham, pineapple', price: 2590, category: 'Pizzur', sort_order: 3 },
  // ─── Pizzafjörður ───
  { id: 'pf-1', restaurant_id: 'pizzafjordur', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2190, category: 'Pizzur', sort_order: 1 },
  { id: 'pf-2', restaurant_id: 'pizzafjordur', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2490, category: 'Pizzur', sort_order: 2 },
  { id: 'pf-3', restaurant_id: 'pizzafjordur', name_is: 'Austfirska', name_en: 'East Iceland Special', description_is: 'Tómatsósa, mozzarella, reyktur lax, kapris, dill', description_en: 'Tomato sauce, mozzarella, smoked salmon, capers, dill', price: 2990, category: 'Pizzur', sort_order: 3 },
  // ─── Flatey Pizza Selfoss ───
  { id: 'fs-1', restaurant_id: 'flatey-pizza-selfoss', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano, fior di latte, basilíka, ólífuolía', description_en: 'San Marzano, fior di latte, basil, olive oil', price: 2590, category: 'Pizzur', sort_order: 1 },
  { id: 'fs-2', restaurant_id: 'flatey-pizza-selfoss', name_is: 'Padrino', name_en: 'Padrino', description_is: 'San Marzano, mozzarella, pepperóní, súr chili, hunang', description_en: 'San Marzano, mozzarella, pepperoni, pickled chili, honey', price: 3190, category: 'Pizzur', sort_order: 2 },
  { id: 'fs-3', restaurant_id: 'flatey-pizza-selfoss', name_is: 'Tartufo', name_en: 'Tartufo', description_is: 'Mozzarella, sveppir, ricotta, kartöflur, trufflolía', description_en: 'Mozzarella, mushrooms, ricotta, potatoes, truffle oil', price: 3490, category: 'Pizzur', sort_order: 3 },
  // ─── Kaffi Krús ───
  { id: 'kk-1', restaurant_id: 'kaffi-krus', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2290, category: 'Pizzur', sort_order: 1 },
  { id: 'kk-2', restaurant_id: 'kaffi-krus', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2590, category: 'Pizzur', sort_order: 2 },
  { id: 'kk-3', restaurant_id: 'kaffi-krus', name_is: 'Skinka og sveppir', name_en: 'Ham & Mushroom', description_is: 'Tómatsósa, mozzarella, skinka, sveppir', description_en: 'Tomato sauce, mozzarella, ham, mushrooms', price: 2590, category: 'Pizzur', sort_order: 3 },
  // ─── Pizza Kofinn ───
  { id: 'pk-1', restaurant_id: 'pizza-kofinn', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2390, category: 'Pizzur', sort_order: 1 },
  { id: 'pk-2', restaurant_id: 'pizza-kofinn', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2790, category: 'Pizzur', sort_order: 2 },
  { id: 'pk-3', restaurant_id: 'pizza-kofinn', name_is: 'Parma', name_en: 'Parma', description_is: 'Mozzarella, Parma-skinka, rúkkóla, parmesan', description_en: 'Mozzarella, Parma ham, arugula, parmesan', price: 3190, category: 'Pizzur', sort_order: 3 },
  // ─── Pítsugerðin ───
  { id: 'pg-1', restaurant_id: 'pitsugerdin', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano, mozzarella, basilíka', description_en: 'San Marzano, mozzarella, basil', price: 2490, category: 'Pizzur', sort_order: 1 },
  { id: 'pg-2', restaurant_id: 'pitsugerdin', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní, hunang', description_en: 'Tomato sauce, mozzarella, pepperoni, honey', price: 2890, category: 'Pizzur', sort_order: 2 },
  { id: 'pg-3', restaurant_id: 'pitsugerdin', name_is: 'Eyjapizza', name_en: 'Island Pizza', description_is: 'Tómatsósa, mozzarella, reyktur lambakjöt, laukur, sólþurrkaðir tómatar', description_en: 'Tomato sauce, mozzarella, smoked lamb, onion, sun-dried tomatoes', price: 3290, category: 'Pizzur', sort_order: 3 },
  // ─── Pizza 67 ───
  { id: 'p7-1', restaurant_id: 'pizza-67-vestmannaeyjar', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, oreganó', description_en: 'Tomato sauce, mozzarella, oregano', price: 1890, category: 'Pizzur', sort_order: 1 },
  { id: 'p7-2', restaurant_id: 'pizza-67-vestmannaeyjar', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2190, category: 'Pizzur', sort_order: 2 },
  { id: 'p7-3', restaurant_id: 'pizza-67-vestmannaeyjar', name_is: 'Hawaii', name_en: 'Hawaiian', description_is: 'Tómatsósa, mozzarella, skinka, ananas', description_en: 'Tomato sauce, mozzarella, ham, pineapple', price: 2190, category: 'Pizzur', sort_order: 3 },
  // ─── Hamraborg ───
  { id: 'hb-1', restaurant_id: 'hamraborg-isafjordur', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, oreganó', description_en: 'Tomato sauce, mozzarella, oregano', price: 2290, category: 'Pizzur', sort_order: 1 },
  { id: 'hb-2', restaurant_id: 'hamraborg-isafjordur', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2590, category: 'Pizzur', sort_order: 2 },
  { id: 'hb-3', restaurant_id: 'hamraborg-isafjordur', name_is: 'Vestfirska', name_en: 'Westfjords Special', description_is: 'Tómatsósa, mozzarella, rækjur, hvítlaukur, dill', description_en: 'Tomato sauce, mozzarella, shrimp, garlic, dill', price: 2990, category: 'Pizzur', sort_order: 3 },
  // ─── Askur Pizzeria ───
  { id: 'ap-1', restaurant_id: 'askur-pizzeria', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2390, category: 'Pizzur', sort_order: 1 },
  { id: 'ap-2', restaurant_id: 'askur-pizzeria', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2690, category: 'Pizzur', sort_order: 2 },
  { id: 'ap-3', restaurant_id: 'askur-pizzeria', name_is: 'Brugghúspizza', name_en: 'Brewery Pizza', description_is: 'Ölsósa, mozzarella, beikon, sveppir, rauðlaukur', description_en: 'Beer-based sauce, mozzarella, bacon, mushrooms, red onion', price: 3090, category: 'Pizzur', sort_order: 3 },
  // ─── Stykkið Pizzeria ───
  { id: 'sp-1', restaurant_id: 'stykkid-pizzeria', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2290, category: 'Pizzur', sort_order: 1 },
  { id: 'sp-2', restaurant_id: 'stykkid-pizzeria', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2590, category: 'Pizzur', sort_order: 2 },
  { id: 'sp-3', restaurant_id: 'stykkid-pizzeria', name_is: 'Snæfellspizza', name_en: 'Snæfellsnes Special', description_is: 'Tómatsósa, mozzarella, reyktur lax, rjómaostur, dill', description_en: 'Tomato sauce, mozzarella, smoked salmon, cream cheese, dill', price: 2990, category: 'Pizzur', sort_order: 3 },
  // ─── Pizzan Hafnarfjörður ───
  { id: 'ph-1', restaurant_id: 'pizzan-hafnarfjordur', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, oreganó', description_en: 'Tomato sauce, mozzarella, oregano', price: 2190, category: 'Pizzur', sort_order: 1 },
  { id: 'ph-2', restaurant_id: 'pizzan-hafnarfjordur', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2490, category: 'Pizzur', sort_order: 2 },
  { id: 'ph-3', restaurant_id: 'pizzan-hafnarfjordur', name_is: 'Ofurpizza', name_en: 'Supreme', description_is: 'Tómatsósa, mozzarella, skinka, pepperóní, sveppir, paprika, laukur', description_en: 'Tomato sauce, mozzarella, ham, pepperoni, mushrooms, peppers, onion', price: 2990, category: 'Pizzur', sort_order: 3 },
  // ─── Flatey Pizza Garðabær ───
  { id: 'fg-1', restaurant_id: 'flatey-pizza-gardabaer', name_is: 'Margherita', name_en: 'Margherita', description_is: 'San Marzano, fior di latte, basilíka, ólífuolía', description_en: 'San Marzano, fior di latte, basil, olive oil', price: 2590, category: 'Pizzur', sort_order: 1 },
  { id: 'fg-2', restaurant_id: 'flatey-pizza-gardabaer', name_is: 'Umberto', name_en: 'Umberto', description_is: 'San Marzano, mozzarella, pepperóní, döðlur, mascarpone', description_en: 'San Marzano, mozzarella, pepperoni, dates, mascarpone', price: 3290, category: 'Pizzur', sort_order: 2 },
  { id: 'fg-3', restaurant_id: 'flatey-pizza-gardabaer', name_is: 'Stracciatella', name_en: 'Stracciatella', description_is: 'Gráðaður skinka, mozzarella, stracciatella, basilíkuolía', description_en: 'Cured ham, mozzarella, stracciatella, basil oil', price: 3590, category: 'Pizzur', sort_order: 3 },
  // ─── Italiano Kópavogur ───
  { id: 'ik-1', restaurant_id: 'italiano-kopavogur', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2290, category: 'Pizzur', sort_order: 1 },
  { id: 'ik-2', restaurant_id: 'italiano-kopavogur', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2590, category: 'Pizzur', sort_order: 2 },
  { id: 'ik-3', restaurant_id: 'italiano-kopavogur', name_is: 'Quattro Formaggi', name_en: 'Four Cheese', description_is: 'Mozzarella, gorgonzola, parmesan, ricotta', description_en: 'Mozzarella, gorgonzola, parmesan, ricotta', price: 2890, category: 'Pizzur', sort_order: 3 },
  // ─── Íslenska Flatbakan ───
  { id: 'if-1', restaurant_id: 'islenska-flatbakan', name_is: 'Klassísk', name_en: 'Classic', description_is: 'Tómatsósa, mozzarella, oreganó', description_en: 'Tomato sauce, mozzarella, oregano', price: 1990, category: 'Pizzur', sort_order: 1 },
  { id: 'if-2', restaurant_id: 'islenska-flatbakan', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2290, category: 'Pizzur', sort_order: 2 },
  { id: 'if-3', restaurant_id: 'islenska-flatbakan', name_is: 'Lambaspes', name_en: 'Lamb Special', description_is: 'Tómatsósa, mozzarella, lambahakk, laukur, paprika', description_en: 'Tomato sauce, mozzarella, ground lamb, onion, peppers', price: 2590, category: 'Pizzur', sort_order: 3 },
  // ─── Pizza Bræður ───
  { id: 'pb-1', restaurant_id: 'pizza-braedur-mosfellsbaer', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, basilíka', description_en: 'Tomato sauce, mozzarella, basil', price: 2190, category: 'Pizzur', sort_order: 1 },
  { id: 'pb-2', restaurant_id: 'pizza-braedur-mosfellsbaer', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2490, category: 'Pizzur', sort_order: 2 },
  { id: 'pb-3', restaurant_id: 'pizza-braedur-mosfellsbaer', name_is: 'Bræðrapizza', name_en: 'Brothers Pizza', description_is: 'Tómatsósa, mozzarella, pepperóní, beikon, jalapeño, hunang', description_en: 'Tomato sauce, mozzarella, pepperoni, bacon, jalapeño, honey', price: 2890, category: 'Pizzur', sort_order: 3 },
  // ─── Castello ───
  { id: 'ca-1', restaurant_id: 'castello-hafnarfjordur', name_is: 'Margherita', name_en: 'Margherita', description_is: 'Tómatsósa, mozzarella, oreganó', description_en: 'Tomato sauce, mozzarella, oregano', price: 2190, category: 'Pizzur', sort_order: 1 },
  { id: 'ca-2', restaurant_id: 'castello-hafnarfjordur', name_is: 'Pepperóní', name_en: 'Pepperoni', description_is: 'Tómatsósa, mozzarella, pepperóní', description_en: 'Tomato sauce, mozzarella, pepperoni', price: 2490, category: 'Pizzur', sort_order: 2 },
  { id: 'ca-3', restaurant_id: 'castello-hafnarfjordur', name_is: 'Castello Special', name_en: 'Castello Special', description_is: 'Tómatsósa, mozzarella, skinka, pepperóní, sveppir, ólífur, paprika', description_en: 'Tomato sauce, mozzarella, ham, pepperoni, mushrooms, olives, peppers', price: 2890, category: 'Pizzur', sort_order: 3 },
];

export { allRecipes as mockRecipes } from './recipeData';

