import { Recipe } from '@/types/recipe';

/* eslint-disable @typescript-eslint/no-explicit-any */

// ══════════════════════════════════════════
// Uppskriftasafn Pizzadeig.is
// Heimildir: Opnar uppskriftir, aðlagaðar og þýddar.
// ══════════════════════════════════════════

export const allRecipes: Recipe[] = [

  // ─── DEIG ───────────────────────────────

  {
    id: 'sannkallad-napoli-deig',
    title_is: 'Sannkallað Napólí Deig',
    title_en: 'Authentic Neapolitan Dough',
    slug: 'sannkallad-napoli-deig',
    description_is: '4 hráefni, 48 klst hefun. Þetta er deigið sem pizzeríur í Napólí nota. 65% rakastig (hydration). Byggt á AVPN staðlinum.',
    description_en: '4 ingredients, 48hr cold ferment. The dough Neapolitan pizzerias use. 65% hydration. Based on the AVPN standard.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'midlungs', prep_time_min: 30, cook_time_min: 2, rest_time_min: 2880, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200'],
    published: true, category: 'deig', type: 'heildar',
    tags: ['Napólí', '00 Hveiti', 'Kald hefun', 'AVPN'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: '00 Hveiti (Caputo eða sambærilegt)', amount: '1000', unit: 'g' },
      { name: 'Kalt vatn', amount: '650', unit: 'ml' },
      { name: 'Sjávarsalt', amount: '30', unit: 'g' },
      { name: 'Ferskt ger', amount: '2', unit: 'g' },
    ],
    ingredients_en: [
      { name: '00 Flour (Caputo or similar)', amount: '1000', unit: 'g' },
      { name: 'Cold water', amount: '650', unit: 'ml' },
      { name: 'Sea salt', amount: '30', unit: 'g' },
      { name: 'Fresh yeast', amount: '2', unit: 'g' },
    ],
    steps_is: [
      'Leysðu gerið upp í köldu vatni og hrærðu.',
      'Bættu við um 10% af hveitinu og hrærðu vel.',
      'Bættu saltinu við og hrærðu.',
      'Bættu restinni af hveitinu í smáum skömmtum.',
      'Hnoðaðu í 15-20 mínútur þar til deigið er mjúkt og slétt.',
      'Hvíldu deigið í 2 klst. undir klæði.',
      'Mótaðu 250g kúlur og settu í loftþétta ílát.',
      'Kældu í 48 klst. (má allt að 72 klst.).',
      'Taktu úr kæli 2 klst. áður en þú bakar.',
    ],
    steps_en: [
      'Dissolve the yeast in cold water and stir.',
      'Add about 10% of the flour and mix well.',
      'Add the salt and stir.',
      'Add the rest of the flour in small batches.',
      'Knead for 15-20 minutes until smooth and elastic.',
      'Rest the dough for 2 hours covered.',
      'Form 250g dough balls and place in airtight container.',
      'Cold ferment for 48 hours (up to 72 hours).',
      'Remove from fridge 2 hours before baking.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'new-york-deig',
    title_is: 'New York Deig',
    title_en: 'New York Style Dough',
    slug: 'new-york-deig',
    description_is: 'Stórar, breyðkenndar sneiðar sem hægt er að brjóta saman. Olífuolía í deiginu gefur mjúkan botn og gyllt yfirborð.',
    description_en: 'Large, foldable slices with a bread-like chew. Olive oil in the dough gives a soft base and golden surface.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 20, cook_time_min: 12, rest_time_min: 1440, servings: 2,
    image_urls: ['https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=1200'],
    published: true, category: 'deig', type: 'heildar',
    tags: ['New York', 'Stórar sneiðar', 'Brauðkennt'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Sterkt brauðhveiti', amount: '500', unit: 'g' },
      { name: 'Hlýtt vatn', amount: '325', unit: 'ml' },
      { name: 'Ólífuolía', amount: '15', unit: 'ml' },
      { name: 'Sykur', amount: '10', unit: 'g' },
      { name: 'Salt', amount: '10', unit: 'g' },
      { name: 'Þurrger', amount: '5', unit: 'g' },
    ],
    ingredients_en: [
      { name: 'Bread flour', amount: '500', unit: 'g' },
      { name: 'Warm water', amount: '325', unit: 'ml' },
      { name: 'Olive oil', amount: '15', unit: 'ml' },
      { name: 'Sugar', amount: '10', unit: 'g' },
      { name: 'Salt', amount: '10', unit: 'g' },
      { name: 'Instant yeast', amount: '5', unit: 'g' },
    ],
    steps_is: [
      'Leysðu sykur og ger í hlýju vatni. Bíddu í 5 mín.',
      'Blandaðu hveitinu og saltinu saman.',
      'Helltu gerblöndunni og olíunni í og hnoðaðu í 10 mín.',
      'Hvíldu í 1 klst. við stofuhita.',
      'Mótaðu í kúlu, smyrðu olíu á og kældu í 24 klst.',
      'Taktu úr kæli 1 klst. áður en þú bakar á 250°C.',
    ],
    steps_en: [
      'Dissolve sugar and yeast in warm water. Wait 5 min.',
      'Combine flour and salt.',
      'Pour in yeast mixture and oil, knead for 10 min.',
      'Rest for 1 hour at room temperature.',
      'Form into a ball, oil it, and cold ferment 24 hours.',
      'Remove from fridge 1 hour before baking at 250°C.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'detroit-deig',
    title_is: 'Detroit Pönnu-Deig',
    title_en: 'Detroit Pan Dough',
    slug: 'detroit-deig',
    description_is: 'Þykkt, loftkennt deig bakað í stálpönnu. Osturinn fer alla leið að kanti og verður krispaður. 75% rakastig.',
    description_en: 'Thick, airy dough baked in a steel pan. Cheese goes to the edges and gets crispy. 75% hydration.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 15, cook_time_min: 15, rest_time_min: 1440, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=1200'],
    published: true, category: 'deig', type: 'heildar',
    tags: ['Detroit', 'Panna', 'Þykk skorpa'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Sterkt brauðhveiti', amount: '400', unit: 'g' },
      { name: 'Vatn', amount: '300', unit: 'ml' },
      { name: 'Ólífuolía', amount: '25', unit: 'ml' },
      { name: 'Salt', amount: '8', unit: 'g' },
      { name: 'Þurrger', amount: '5', unit: 'g' },
    ],
    ingredients_en: [
      { name: 'Bread flour', amount: '400', unit: 'g' },
      { name: 'Water', amount: '300', unit: 'ml' },
      { name: 'Olive oil', amount: '25', unit: 'ml' },
      { name: 'Salt', amount: '8', unit: 'g' },
      { name: 'Instant yeast', amount: '5', unit: 'g' },
    ],
    steps_is: [
      'Blandaðu öllum hráefnum saman. Deigið verður frekar blautt.',
      'Hvíldu í 1 klst. við stofuhita, brettu 2x á meðan.',
      'Smyrðu olíu í stálpönnu (25x35cm).',
      'Þrýstu deiginu út í hornin. Kældu í 24 klst.',
      'Taktu úr kæli, þrýstu aftur í horn. Hvíldu í 2 klst.',
      'Settu ost (brick/mozzarella) alla leið í kanta.',
      'Bakaðu á 250°C í 12-15 mín.',
    ],
    steps_en: [
      'Combine all ingredients. The dough will be quite wet.',
      'Rest 1 hour at room temp, fold 2x during that time.',
      'Oil a steel pan (10x14 inch).',
      'Press dough into corners. Cold ferment 24 hours.',
      'Remove, press into corners again. Rest 2 hours.',
      'Add cheese (brick/mozzarella) all the way to the edges.',
      'Bake at 250°C for 12-15 min.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'surdeigs-pizza-deig',
    title_is: 'Súrdeigsdeig fyrir Pizzu',
    title_en: 'Sourdough Pizza Dough',
    slug: 'surdeigs-pizza-deig',
    description_is: 'Notaðu súrdeigsmóður í stað gers. Djúpt og flókið bragð, lakar af sýru. 3ja daga ferli.',
    description_en: 'Use sourdough starter instead of yeast. Deep, complex flavor with tangy notes. 3-day process.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'erfitt', prep_time_min: 30, cook_time_min: 2, rest_time_min: 4320, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?q=80&w=1200'],
    published: true, category: 'deig', type: 'heildar',
    tags: ['Súrdeig', 'Langtímahefun', 'Gerlaust'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Virk súrdeigsmóðir', amount: '200', unit: 'g' },
      { name: '00 Hveiti', amount: '500', unit: 'g' },
      { name: 'Vatn', amount: '325', unit: 'ml' },
      { name: 'Salt', amount: '15', unit: 'g' },
    ],
    ingredients_en: [
      { name: 'Active sourdough starter', amount: '200', unit: 'g' },
      { name: '00 Flour', amount: '500', unit: 'g' },
      { name: 'Water', amount: '325', unit: 'ml' },
      { name: 'Salt', amount: '15', unit: 'g' },
    ],
    steps_is: [
      'Blandaðu súrdeigsmóður og vatni vel saman.',
      'Bættu hveitinu við og hrærðu þar til deig myndast.',
      'Hvíldu í 30 mín (autolyse).',
      'Bættu salti og hnoðaðu í 15 mín.',
      'Brettu deigið 3x yfir 3 klst (stretch & fold).',
      'Kældu í 48-72 klst.',
      'Mótaðu kúlur, hvíldu í 2-4 klst. á stofuhita.',
    ],
    steps_en: [
      'Mix sourdough starter and water well.',
      'Add flour and stir until a dough forms.',
      'Rest 30 min (autolyse).',
      'Add salt and knead for 15 min.',
      'Fold the dough 3x over 3 hours (stretch & fold).',
      'Cold ferment 48-72 hours.',
      'Form balls, rest 2-4 hours at room temperature.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  // ─── SÓSUR ──────────────────────────────

  {
    id: 'san-marzano-sosa',
    title_is: 'San Marzano Tómatsósa',
    title_en: 'San Marzano Tomato Sauce',
    slug: 'san-marzano-sosa',
    description_is: 'Klassísk napólítönsk sósa — ósoðin. San Marzano tómatar, hvítlaukur, ólífuolía. Einfalt og fullkomið.',
    description_en: 'Classic Neapolitan sauce — uncooked. San Marzano tomatoes, garlic, olive oil. Simple and perfect.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 10, cook_time_min: 0, rest_time_min: 0, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=1200'],
    published: true, category: 'sosur', type: 'heildar',
    tags: ['San Marzano', 'Ósoðin', 'Napólí'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'San Marzano tómatar (niðursoðnir)', amount: '400', unit: 'g' },
      { name: 'Extra virgin ólífuolía', amount: '15', unit: 'ml' },
      { name: 'Hvítlaukur (fínsmátt)', amount: '1', unit: 'geiri' },
      { name: 'Sjávarsalt', amount: '1', unit: 'tsk' },
      { name: 'Ferskt basil', amount: '5', unit: 'lauf' },
    ],
    ingredients_en: [
      { name: 'San Marzano tomatoes (canned)', amount: '400', unit: 'g' },
      { name: 'Extra virgin olive oil', amount: '15', unit: 'ml' },
      { name: 'Garlic (minced)', amount: '1', unit: 'clove' },
      { name: 'Sea salt', amount: '1', unit: 'tsp' },
      { name: 'Fresh basil', amount: '5', unit: 'leaves' },
    ],
    steps_is: [
      'Helltu tómatunum í skál og muldu þá með höndunum.',
      'Bættu við ólífuolíu, hvítlauk og salti.',
      'Rifðu basil í og hrærðu.',
      'Tilbúin! Engin eldun þarf. Settu á pizzu og bakaðu.',
    ],
    steps_en: [
      'Pour tomatoes into a bowl and crush by hand.',
      'Add olive oil, garlic, and salt.',
      'Tear in basil and stir.',
      'Ready! No cooking needed. Spread on pizza and bake.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'hvit-sosa',
    title_is: 'Hvít Sósa (Béchamel)',
    title_en: 'White Sauce (Béchamel)',
    slug: 'hvit-sosa',
    description_is: 'Rjómakekkjuð hvít sósa með parmesan og hvítlauk. Frábær grunnur á hvítri pizzu.',
    description_en: 'Creamy white sauce with parmesan and garlic. Perfect base for white pizza.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 5, cook_time_min: 10, rest_time_min: 0, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?q=80&w=1200'],
    published: true, category: 'sosur', type: 'heildar',
    tags: ['Hvít', 'Béchamel', 'Rjómi'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Smjör', amount: '30', unit: 'g' },
      { name: 'Hveiti', amount: '30', unit: 'g' },
      { name: 'Mjólk', amount: '300', unit: 'ml' },
      { name: 'Parmesan (rifinn)', amount: '50', unit: 'g' },
      { name: 'Hvítlaukur (fínsmátt)', amount: '2', unit: 'geiri' },
      { name: 'Salt og pipar', amount: '', unit: 'ad smekk' },
    ],
    ingredients_en: [
      { name: 'Butter', amount: '30', unit: 'g' },
      { name: 'Flour', amount: '30', unit: 'g' },
      { name: 'Milk', amount: '300', unit: 'ml' },
      { name: 'Parmesan (grated)', amount: '50', unit: 'g' },
      { name: 'Garlic (minced)', amount: '2', unit: 'cloves' },
      { name: 'Salt and pepper', amount: '', unit: 'to taste' },
    ],
    steps_is: [
      'Bráðaðu smjörið á meðalhita og steiktu hvítlaukinn í 1 mín.',
      'Hrærðu hveitinu í og eldaðu í 1 mín (roux).',
      'Bættu mjólkinni við í smáum skömmtum og hrærðu stöðugt.',
      'Eldaðu í 5-7 mín þar til sósan þykknar.',
      'Taktu af hita, hrærðu parmesaninn í, bragðbættu.',
    ],
    steps_en: [
      'Melt butter over medium heat, sauté garlic for 1 min.',
      'Stir in flour and cook for 1 min (roux).',
      'Add milk gradually, stirring constantly.',
      'Cook 5-7 min until sauce thickens.',
      'Remove from heat, stir in parmesan, season to taste.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'pesto-sosa',
    title_is: 'Basil Pestó',
    title_en: 'Basil Pesto',
    slug: 'pesto-sosa',
    description_is: 'Ferskt pestó með basil, furuhnetur og parmesan. Frábært á hvíta pizzu eða sem dreypi.',
    description_en: 'Fresh pesto with basil, pine nuts, and parmesan. Great on white pizza or as a drizzle.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 10, cook_time_min: 0, rest_time_min: 0, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1476124369491-e7addf5db371?q=80&w=1200'],
    published: true, category: 'sosur', type: 'heildar',
    tags: ['Pestó', 'Basil', 'Furuhnetur'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Ferskt basil (lauf)', amount: '60', unit: 'g' },
      { name: 'Parmesan (rifinn)', amount: '50', unit: 'g' },
      { name: 'Furuhnetur (ristaðar)', amount: '30', unit: 'g' },
      { name: 'Hvítlaukur', amount: '2', unit: 'geiri' },
      { name: 'Extra virgin ólífuolía', amount: '100', unit: 'ml' },
      { name: 'Salt', amount: '1', unit: 'tsk' },
    ],
    ingredients_en: [
      { name: 'Fresh basil leaves', amount: '60', unit: 'g' },
      { name: 'Parmesan (grated)', amount: '50', unit: 'g' },
      { name: 'Pine nuts (toasted)', amount: '30', unit: 'g' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
      { name: 'Extra virgin olive oil', amount: '100', unit: 'ml' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
    ],
    steps_is: [
      'Settu basil, furuhnetur, hvítlauk og salt í matargerð.',
      'Keyrðu í smátt.',
      'Bættu parmesan við og keyrðu aftur.',
      'Helltu olíunni í rjúkandi þunnum straumi á meðan vélín keyrir.',
      'Bragðbættu. Geymist í 5 daga í kæli.',
    ],
    steps_en: [
      'Add basil, pine nuts, garlic and salt to food processor.',
      'Pulse until finely chopped.',
      'Add parmesan and pulse again.',
      'Drizzle in olive oil while running.',
      'Season to taste. Keeps 5 days refrigerated.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  // ─── OSTUR ──────────────────────────────

  {
    id: 'ostaleidbeiningar',
    title_is: 'Ostaleiðbeiningar fyrir Pizzu',
    title_en: 'Pizza Cheese Guide',
    slug: 'ostaleidbeiningar',
    description_is: 'Hvernig á að nota mozzarella, fior di latte, burrata og parmesan á pizzu.',
    description_en: 'How to use mozzarella, fior di latte, burrata, and parmesan on pizza.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 5, cook_time_min: 0, rest_time_min: 0, servings: 1,
    image_urls: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?q=80&w=1200'],
    published: true, category: 'ostur', type: 'heildar',
    tags: ['Mozzarella', 'Fior di latte', 'Burrata', 'Parmesan'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Fior di Latte (kúamjólk mozzarella)', amount: '125', unit: 'g' },
      { name: 'Mozzarella di Bufala', amount: '125', unit: 'g' },
      { name: 'Burrata', amount: '1', unit: 'kúla' },
      { name: 'Parmesan (rifinn)', amount: '30', unit: 'g' },
    ],
    ingredients_en: [
      { name: 'Fior di Latte (cow milk mozzarella)', amount: '125', unit: 'g' },
      { name: 'Mozzarella di Bufala', amount: '125', unit: 'g' },
      { name: 'Burrata', amount: '1', unit: 'ball' },
      { name: 'Parmesan (grated)', amount: '30', unit: 'g' },
    ],
    steps_is: [
      'FIOR DI LATTE: Sneiddu í sneiðar, látttu leka í 30 mín. Settu á pizzu ÁÐUR en hún fer í ofn. Bráðnar jafnt, myndar togkennt yfirborð.',
      'MOZZARELLA DI BUFALA: Rifðu í stykki, látttu leka vel. Notaðu á pizzu EFTIR bökunar eða á seinustu 60 sekúndunum. Annars verður botninn blautur.',
      'BURRATA: Settu ALLTAF á EFTIR bökunar. Rifðu í sundur á heitri pizzu og láttu rjómann renna.',
      'PARMESAN: Stráddu ríflega yfir eftir bökunar. Bráðnar ekki en gefur salt og umami bragð.',
    ],
    steps_en: [
      'FIOR DI LATTE: Slice and drain 30 min. Add BEFORE baking. Melts evenly, creates stretchy surface.',
      'MOZZARELLA DI BUFALA: Tear into pieces, drain well. Add AFTER baking or in last 60 seconds. Otherwise the base gets soggy.',
      'BURRATA: ALWAYS add AFTER baking. Tear open on hot pizza and let the cream flow.',
      'PARMESAN: Grate generously over after baking. Won\'t melt but adds salt and umami.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  // ─── ÁLEGG ──────────────────────────────

  {
    id: 'karamellusoðnir-laukur',
    title_is: 'Karamellusoðinn Laukur',
    title_en: 'Caramelized Onions',
    slug: 'karamellusoðnir-laukur',
    description_is: 'Hægeldaður, sætur laukur. Frábært álegg á hvíta, gorgonzola eða brie pizzu.',
    description_en: 'Slow-cooked, sweet onion. Great topping on white, gorgonzola, or brie pizza.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 5, cook_time_min: 40, rest_time_min: 0, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1518677900801-0f381e947b66?q=80&w=1200'],
    published: true, category: 'alegg', type: 'heildar',
    tags: ['Laukur', 'Sætt', 'Toppandi'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Stórir gullaukur', amount: '4', unit: 'stk' },
      { name: 'Smjör', amount: '30', unit: 'g' },
      { name: 'Ólífuolía', amount: '15', unit: 'ml' },
      { name: 'Salt', amount: '1', unit: 'tsk' },
      { name: 'Balsamík edik (valfrjálst)', amount: '15', unit: 'ml' },
    ],
    ingredients_en: [
      { name: 'Large yellow onions', amount: '4', unit: 'pcs' },
      { name: 'Butter', amount: '30', unit: 'g' },
      { name: 'Olive oil', amount: '15', unit: 'ml' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
      { name: 'Balsamic vinegar (optional)', amount: '15', unit: 'ml' },
    ],
    steps_is: [
      'Sneiddu laukinn í þunna hringa.',
      'Hitaðu smjör og olíu á meðalhita í stórri pönnu.',
      'Bættu lauknum við, saltaðu, hrærðu.',
      'Eldaðu á lághita í 35-40 mín, hrærðu á 5 mín fresti.',
      'Bættu við balsamík á seinustu 5 mín ef þú vilt.',
    ],
    steps_en: [
      'Slice onions into thin rings.',
      'Heat butter and oil over medium in a large pan.',
      'Add onions, salt, and stir.',
      'Cook on low heat 35-40 min, stirring every 5 min.',
      'Add balsamic in the last 5 min if desired.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'nduja-smjor',
    title_is: '\'Nduja Smjör',
    title_en: '\'Nduja Butter',
    slug: 'nduja-smjor',
    description_is: 'Kryddað kalabrísk pylsusmjör. Dreifðu á pizzu fyrir hitaloga. Einnig frábært á brauð.',
    description_en: 'Spicy Calabrian sausage butter. Spread on pizza for a kick of heat. Also great on bread.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 5, cook_time_min: 0, rest_time_min: 0, servings: 4,
    image_urls: ['https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=1200'],
    published: true, category: 'alegg', type: 'heildar',
    tags: ['Nduja', 'Kryddað', 'Kalabría'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: '\'Nduja', amount: '100', unit: 'g' },
      { name: 'Mjúkt smjör', amount: '50', unit: 'g' },
      { name: 'Hunang', amount: '10', unit: 'ml' },
    ],
    ingredients_en: [
      { name: '\'Nduja', amount: '100', unit: 'g' },
      { name: 'Soft butter', amount: '50', unit: 'g' },
      { name: 'Honey', amount: '10', unit: 'ml' },
    ],
    steps_is: [
      'Hrærðu \'nduja og smjör saman þar til slétt.',
      'Bættu hunangi við og hrærðu.',
      'Geymdu í kæli. Dreifðu á pizzu eftir bökunar.',
    ],
    steps_en: [
      'Mix \'nduja and butter until smooth.',
      'Add honey and stir.',
      'Store in fridge. Spread on pizza after baking.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  // ─── HEILDAR PIZZUR ─────────────────────

  {
    id: 'klassisk-margherita',
    title_is: 'Klassísk Margherita',
    title_en: 'Classic Margherita',
    slug: 'klassisk-margherita',
    description_is: 'Drottningin sjálf. Tómat, mozzarella, basil — ekkert meira, ekkert minna. AVPN staðall.',
    description_en: 'The queen herself. Tomato, mozzarella, basil — nothing more, nothing less. AVPN standard.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 10, cook_time_min: 2, rest_time_min: 0, servings: 1,
    image_urls: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200'],
    published: true, category: 'pizzur', type: 'heildar',
    tags: ['Margherita', 'Klassísk', 'Napólí'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Napólí deigkúla', amount: '250', unit: 'g' },
      { name: 'San Marzano sósa', amount: '80', unit: 'g' },
      { name: 'Fior di Latte', amount: '100', unit: 'g' },
      { name: 'Ferskt basil', amount: '5', unit: 'lauf' },
      { name: 'Ólífuolía', amount: '1', unit: 'msk' },
    ],
    ingredients_en: [
      { name: 'Neapolitan dough ball', amount: '250', unit: 'g' },
      { name: 'San Marzano sauce', amount: '80', unit: 'g' },
      { name: 'Fior di Latte', amount: '100', unit: 'g' },
      { name: 'Fresh basil', amount: '5', unit: 'leaves' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
    ],
    steps_is: [
      'Hitaðu ofninn á hámarkshita (250°C+ eða pizzuofn 450°C).',
      'Flattu deigkúlunni út í hring, þykkari á köntum.',
      'Dreifðu sósunni jafnt, skildu 2cm kant.',
      'Rifðu Fior di Latte í bita og dreifðu yfir.',
      'Bakaðu í 60-90 sek í pizzuofni (eða 8-10 mín í venjulegum).',
      'Settu ferskt basil og ólífuolíu á eftir bökunar.',
    ],
    steps_en: [
      'Heat oven to max (250°C+ or pizza oven 450°C).',
      'Stretch dough ball into a circle, thicker at edges.',
      'Spread sauce evenly, leave 2cm border.',
      'Tear Fior di Latte into pieces and distribute.',
      'Bake 60-90 sec in pizza oven (8-10 min in regular).',
      'Add fresh basil and olive oil after baking.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'hvita-pizzan',
    title_is: 'Hvít Pizza með Ricotta og Sveppum',
    title_en: 'White Pizza with Ricotta & Mushrooms',
    slug: 'hvita-pizzan',
    description_is: 'Engin tómatsósa — hvít sósa, ricotta, steiktir sveppir og trufflolía. Elegant og bragðmikil.',
    description_en: 'No tomato sauce — white sauce, ricotta, sautéed mushrooms, and truffle oil. Elegant and flavorful.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'midlungs', prep_time_min: 20, cook_time_min: 10, rest_time_min: 0, servings: 1,
    image_urls: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200'],
    published: true, category: 'pizzur', type: 'heildar',
    tags: ['Hvít', 'Sveppir', 'Trufflolía'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Deigkúla', amount: '250', unit: 'g' },
      { name: 'Hvít sósa', amount: '60', unit: 'ml' },
      { name: 'Ricotta', amount: '80', unit: 'g' },
      { name: 'Mozzarella', amount: '80', unit: 'g' },
      { name: 'Blandaðir sveppir (steiktir)', amount: '100', unit: 'g' },
      { name: 'Trufflolía', amount: '1', unit: 'tsk' },
      { name: 'Þýmían', amount: '1', unit: 'tsk' },
    ],
    ingredients_en: [
      { name: 'Dough ball', amount: '250', unit: 'g' },
      { name: 'White sauce', amount: '60', unit: 'ml' },
      { name: 'Ricotta', amount: '80', unit: 'g' },
      { name: 'Mozzarella', amount: '80', unit: 'g' },
      { name: 'Mixed mushrooms (sautéed)', amount: '100', unit: 'g' },
      { name: 'Truffle oil', amount: '1', unit: 'tsp' },
      { name: 'Thyme', amount: '1', unit: 'tsp' },
    ],
    steps_is: [
      'Steiktu sveppina á háum hita í olíu og smjöri í 5 mín.',
      'Flattu deiginu og dreifðu hvítu sósunni.',
      'Settu mozzarella, síðan skeið af ricotta í klumpum.',
      'Bættu sveppunum á og stráddu þýmían yfir.',
      'Bakaðu á hámarkshita í 8-10 mín.',
      'Dreyptu trufflolíu yfir eftir bökunar.',
    ],
    steps_en: [
      'Sauté mushrooms in oil and butter on high heat for 5 min.',
      'Stretch dough and spread white sauce.',
      'Add mozzarella, then dollops of ricotta.',
      'Top with mushrooms and sprinkle thyme.',
      'Bake at max heat for 8-10 min.',
      'Drizzle truffle oil after baking.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'diavola-pizza',
    title_is: 'Diavola — Eldheitur Pepperóní',
    title_en: 'Diavola — Spicy Pepperoni',
    slug: 'diavola-pizza',
    description_is: 'Pepperóní sem krökknar, chili flökur, hunang. Eldsheitur og ómótstæðilegur.',
    description_en: 'Pepperoni that cups and crisps, chili flakes, honey drizzle. Fiery and irresistible.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 10, cook_time_min: 2, rest_time_min: 0, servings: 1,
    image_urls: ['https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?q=80&w=1200'],
    published: true, category: 'pizzur', type: 'heildar',
    tags: ['Diavola', 'Pepperóní', 'Kryddað'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Deigkúla', amount: '250', unit: 'g' },
      { name: 'San Marzano sósa', amount: '80', unit: 'g' },
      { name: 'Fior di Latte', amount: '100', unit: 'g' },
      { name: 'Pepperóní (natural casing)', amount: '50', unit: 'g' },
      { name: 'Chili flögur', amount: '1', unit: 'tsk' },
      { name: 'Hunang', amount: '1', unit: 'msk' },
    ],
    ingredients_en: [
      { name: 'Dough ball', amount: '250', unit: 'g' },
      { name: 'San Marzano sauce', amount: '80', unit: 'g' },
      { name: 'Fior di Latte', amount: '100', unit: 'g' },
      { name: 'Pepperoni (natural casing)', amount: '50', unit: 'g' },
      { name: 'Chili flakes', amount: '1', unit: 'tsp' },
      { name: 'Honey', amount: '1', unit: 'tbsp' },
    ],
    steps_is: [
      'Flattu deiginu og dreifðu sósu.',
      'Settu mozzarella og pepperóní á.',
      'Stráddu chili flökum yfir.',
      'Bakaðu á hámarkshita þar til pepperónín krökknar.',
      'Dreyptu hunangi yfir strax eftir bökunar.',
    ],
    steps_en: [
      'Stretch dough and spread sauce.',
      'Add mozzarella and pepperoni.',
      'Sprinkle chili flakes.',
      'Bake at max heat until pepperoni cups and crisps.',
      'Drizzle honey immediately after baking.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'quattro-formaggi',
    title_is: 'Quattro Formaggi',
    title_en: 'Four Cheese Pizza',
    slug: 'quattro-formaggi',
    description_is: '4 ostar, engin sósa. Mozzarella, gorgonzola, parmesan og fontina. Hvít pizza á sínu besta.',
    description_en: '4 cheeses, no sauce. Mozzarella, gorgonzola, parmesan, and fontina. White pizza at its best.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 10, cook_time_min: 8, rest_time_min: 0, servings: 1,
    image_urls: ['https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?q=80&w=1200'],
    published: true, category: 'pizzur', type: 'heildar',
    tags: ['Quattro Formaggi', '4 Ostar', 'Hvít'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Deigkúla', amount: '250', unit: 'g' },
      { name: 'Mozzarella', amount: '60', unit: 'g' },
      { name: 'Gorgonzola', amount: '40', unit: 'g' },
      { name: 'Parmesan (rifinn)', amount: '30', unit: 'g' },
      { name: 'Fontina eða brie', amount: '40', unit: 'g' },
      { name: 'Hunang', amount: '1', unit: 'msk' },
      { name: 'Valhnetur', amount: '4', unit: 'stk' },
    ],
    ingredients_en: [
      { name: 'Dough ball', amount: '250', unit: 'g' },
      { name: 'Mozzarella', amount: '60', unit: 'g' },
      { name: 'Gorgonzola', amount: '40', unit: 'g' },
      { name: 'Parmesan (grated)', amount: '30', unit: 'g' },
      { name: 'Fontina or brie', amount: '40', unit: 'g' },
      { name: 'Honey', amount: '1', unit: 'tbsp' },
      { name: 'Walnuts', amount: '4', unit: 'pcs' },
    ],
    steps_is: [
      'Flattu deiginu. Engin sósa!',
      'Rifðu mozzarella og dreifðu.',
      'Bættu gorgonzola og fontina/brie í litlum klumpum.',
      'Bakaðu á hámarkshita í 8-10 mín.',
      'Stráddu parmesan, brúðuðum valhnetum og hunangi yfir.',
    ],
    steps_en: [
      'Stretch dough. No sauce!',
      'Tear mozzarella and spread.',
      'Add gorgonzola and fontina/brie in small chunks.',
      'Bake at max heat for 8-10 min.',
      'Top with parmesan, crushed walnuts, and honey.',
    ],
    created_at: null as any, updated_at: null as any,
  },

  {
    id: 'prosciutto-rucola',
    title_is: 'Prosciutto e Rucola',
    title_en: 'Prosciutto & Arugula',
    slug: 'prosciutto-rucola',
    description_is: 'Bakað tómat og mozzarella, toppað eftir bökunar með prosciutto, rúkólu og parmesan. Elegant.',
    description_en: 'Baked tomato and mozzarella, topped after baking with prosciutto, arugula, and parmesan. Elegant.',
    author_uid: 'pizzadeig', author_name: 'Pizzadeig.is',
    difficulty: 'audvelt', prep_time_min: 10, cook_time_min: 2, rest_time_min: 0, servings: 1,
    image_urls: ['https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=1200'],
    published: true, category: 'pizzur', type: 'heildar',
    tags: ['Prosciutto', 'Rúkóla', 'Elegant'],
    rating_avg: 0, rating_count: 0, likes_count: 0,
    ingredients_is: [
      { name: 'Deigkúla', amount: '250', unit: 'g' },
      { name: 'San Marzano sósa', amount: '80', unit: 'g' },
      { name: 'Fior di Latte', amount: '100', unit: 'g' },
      { name: 'Prosciutto di Parma', amount: '60', unit: 'g' },
      { name: 'Rúkóla (baby)', amount: '30', unit: 'g' },
      { name: 'Parmesan flögur', amount: '20', unit: 'g' },
      { name: 'Ólífuolía', amount: '1', unit: 'msk' },
    ],
    ingredients_en: [
      { name: 'Dough ball', amount: '250', unit: 'g' },
      { name: 'San Marzano sauce', amount: '80', unit: 'g' },
      { name: 'Fior di Latte', amount: '100', unit: 'g' },
      { name: 'Prosciutto di Parma', amount: '60', unit: 'g' },
      { name: 'Baby arugula', amount: '30', unit: 'g' },
      { name: 'Parmesan shavings', amount: '20', unit: 'g' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
    ],
    steps_is: [
      'Flattu deiginu, dreifðu sósu og mozzarella.',
      'Bakaðu á hámarkshita þar til kantarnir brúnka.',
      'EFTIR bökunar: leggðu prosciutto sneiðar yfir.',
      'Stráddu rúkólu og parmesan flögum á.',
      'Dreyptu ólífuolíu yfir.',
    ],
    steps_en: [
      'Stretch dough, spread sauce and mozzarella.',
      'Bake at max heat until edges char.',
      'AFTER baking: lay prosciutto slices on top.',
      'Scatter arugula and parmesan shavings.',
      'Drizzle olive oil.',
    ],
    created_at: null as any, updated_at: null as any,
  },
];
